// Code generated by cmd/genapis; DO NOT EDIT.

package kioom

import (
	"context"
	"net/http"
)

// USStockListRequest is the request payload for usa10099 (미국주식 종목리스트).
type USStockListRequest struct {
	StexTp string `json:"stex_tp"`
}

// USStockListResponse is the response payload for usa10099 (미국주식 종목리스트).
type USStockListResponse struct {
	List       []USStockListResponseListItem `json:"list"`
	ReturnCode int                           `json:"return_code"`
	ReturnMsg  string                        `json:"return_msg"`
}

// USStockListResponseListItem is a list row in USStockListResponse.
type USStockListResponseListItem struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
	StkNm  string `json:"stk_nm"`
	StkEnm string `json:"stk_enm"`
	Mkgb   string `json:"mkgb"`
	Upgb   string `json:"upgb"`
	IsEtf  string `json:"isEtf"`
}

// GetUSStockList calls Kiwoom usa10099 — 미국주식 종목리스트.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockList(ctx context.Context, req *USStockListRequest) (*USStockListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10099", req)
	if err != nil {
		return nil, err
	}
	var res USStockListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockLookupRequest is the request payload for usa10100 (미국주식 종목 조회).
type USStockLookupRequest struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockLookupResponse is the response payload for usa10100 (미국주식 종목 조회).
type USStockLookupResponse struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	Mkgb       string `json:"mkgb"`
	Upgb       string `json:"upgb"`
	IsEtf      string `json:"isEtf"`
	ReturnCode int    `json:"return_code"`
	ReturnMsg  string `json:"return_msg"`
}

// GetUSStockLookup calls Kiwoom usa10100 — 미국주식 종목 조회.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockLookup(ctx context.Context, req *USStockLookupRequest) (*USStockLookupResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10100", req)
	if err != nil {
		return nil, err
	}
	var res USStockLookupResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockSectorListRequest is the request payload for usa10101 (미국주식 업종리스트).
type USStockSectorListRequest struct {
	Gubun string `json:"gubun"`
}

// USStockSectorListResponse is the response payload for usa10101 (미국주식 업종리스트).
type USStockSectorListResponse struct {
	List       []USStockSectorListResponseListItem `json:"list"`
	ReturnCode int                                 `json:"return_code"`
	ReturnMsg  string                              `json:"return_msg"`
}

// USStockSectorListResponseListItem is a list row in USStockSectorListResponse.
type USStockSectorListResponseListItem struct {
	IndsCd  string `json:"inds_cd"`
	IndsNm  string `json:"inds_nm"`
	IndsEnm string `json:"inds_enm"`
}

// GetUSStockSectorList calls Kiwoom usa10101 — 미국주식 업종리스트.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockSectorList(ctx context.Context, req *USStockSectorListRequest) (*USStockSectorListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10101", req)
	if err != nil {
		return nil, err
	}
	var res USStockSectorListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USIndexListRequest is the request payload for usa10102 (미국지수 리스트).
type USIndexListRequest struct {
	IndexQryTp string `json:"index_qry_tp"`
}

// USIndexListResponse is the response payload for usa10102 (미국지수 리스트).
type USIndexListResponse struct {
	List       []USIndexListResponseListItem `json:"list"`
	ReturnCode int                           `json:"return_code"`
	ReturnMsg  string                        `json:"return_msg"`
}

// USIndexListResponseListItem is a list row in USIndexListResponse.
type USIndexListResponseListItem struct {
	IndexCd  string `json:"index_cd"`
	IndexNm  string `json:"index_nm"`
	IndexEnm string `json:"index_enm"`
}

// GetUSIndexList calls Kiwoom usa10102 — 미국지수 리스트.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSIndexList(ctx context.Context, req *USIndexListRequest) (*USIndexListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10102", req)
	if err != nil {
		return nil, err
	}
	var res USIndexListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockMemoRequest is the request payload for usa10103 (미국주식 종목메모 조회).
type USStockMemoRequest struct {
}

// USStockMemoRequestInputListItem is a list row in USStockMemoRequest.
type USStockMemoRequestInputListItem struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockMemoResponse is the response payload for usa10103 (미국주식 종목메모 조회).
type USStockMemoResponse struct {
	Rtcd       string                              `json:"rtcd"`
	ResultList []USStockMemoResponseResultListItem `json:"result_list"`
	ReturnCode int                                 `json:"return_code"`
	ReturnMsg  string                              `json:"return_msg"`
}

// USStockMemoResponseResultListItem is a list row in USStockMemoResponse.
type USStockMemoResponseResultListItem struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
	Memo   string `json:"memo"`
}

// GetUSStockMemo calls Kiwoom usa10103 — 미국주식 종목메모 조회.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockMemo(ctx context.Context, req *USStockMemoRequest) (*USStockMemoResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10103", req)
	if err != nil {
		return nil, err
	}
	var res USStockMemoResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFETNListRequest is the request payload for usa10104 (미국 ETF,ETN 리스트 ).
type USETFETNListRequest struct {
	StexTp string `json:"stex_tp"`
}

// USETFETNListResponse is the response payload for usa10104 (미국 ETF,ETN 리스트 ).
type USETFETNListResponse struct {
	List       []USETFETNListResponseListItem `json:"list"`
	ReturnCode int                            `json:"return_code"`
	ReturnMsg  string                         `json:"return_msg"`
}

// USETFETNListResponseListItem is a list row in USETFETNListResponse.
type USETFETNListResponseListItem struct {
	StexTp string `json:"stex_tp"`
	Code   string `json:"code"`
	Cate1  string `json:"cate1"`
	Cate2  string `json:"cate2"`
	Etn    string `json:"etn"`
	Mkgb   string `json:"mkgb"`
	Upnm   string `json:"upnm"`
}

// GetUSETFETNList calls Kiwoom usa10104 — 미국 ETF,ETN 리스트 .
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFETNList(ctx context.Context, req *USETFETNListRequest) (*USETFETNListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10104", req)
	if err != nil {
		return nil, err
	}
	var res USETFETNListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFCategoryListRequest is the request payload for usa10105 (미국 ETF 카테고리 리스트).
type USETFCategoryListRequest struct {
	Gubun string `json:"gubun"`
}

// USETFCategoryListResponse is the response payload for usa10105 (미국 ETF 카테고리 리스트).
type USETFCategoryListResponse struct {
	List       []USETFCategoryListResponseListItem `json:"list"`
	ReturnCode int                                 `json:"return_code"`
	ReturnMsg  string                              `json:"return_msg"`
}

// USETFCategoryListResponseListItem is a list row in USETFCategoryListResponse.
type USETFCategoryListResponseListItem struct {
	Gubun    string `json:"gubun"`
	Cate1    string `json:"cate1"`
	Cate1nam string `json:"cate1nam"`
	Cate2    string `json:"cate2"`
	Cate2nam string `json:"cate2nam"`
}

// GetUSETFCategoryList calls Kiwoom usa10105 — 미국 ETF 카테고리 리스트.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFCategoryList(ctx context.Context, req *USETFCategoryListRequest) (*USETFCategoryListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10105", req)
	if err != nil {
		return nil, err
	}
	var res USETFCategoryListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockCurrentInfoRequest is the request payload for usa20100 (미국주식 현재가 종목정보).
type USStockCurrentInfoRequest struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockCurrentInfoResponse is the response payload for usa20100 (미국주식 현재가 종목정보).
type USStockCurrentInfoResponse struct {
	StexTp             string `json:"stex_tp"`
	StkCd              string `json:"stk_cd"`
	StkNm              string `json:"stk_nm"`
	StkEnm             string `json:"stk_enm"`
	N52wkHgstPric      string `json:"52wk_hgst_pric"`
	N52wkHgstPricPreRt string `json:"52wk_hgst_pric_pre_rt"`
	N52wkHgstPricDt    string `json:"52wk_hgst_pric_dt"`
	N52wkLwstPric      string `json:"52wk_lwst_pric"`
	N52wkLwstPricPreRt string `json:"52wk_lwst_pric_pre_rt"`
	N52wkLwstPricDt    string `json:"52wk_lwst_pric_dt"`
	StkCnt             string `json:"stk_cnt"`
	Mac                string `json:"mac"`
	SetlMm             string `json:"setl_mm"`
	LgIndsCd           string `json:"lg_inds_cd"`
	SmIndsCd           string `json:"sm_inds_cd"`
	CurPrc             string `json:"cur_prc"`
	PredPreSig         string `json:"pred_pre_sig"`
	PredPre            string `json:"pred_pre"`
	FluRt              string `json:"flu_rt"`
	AccTrdeQty         string `json:"acc_trde_qty"`
	OyrHgst            string `json:"oyr_hgst"`
	OyrHgstDt          string `json:"oyr_hgst_dt"`
	OyrHgstPreRt       string `json:"oyr_hgst_pre_rt"`
	OyrLwst            string `json:"oyr_lwst"`
	OyrLwstDt          string `json:"oyr_lwst_dt"`
	OyrLwstPreRt       string `json:"oyr_lwst_pre_rt"`
	PreOpenPric        string `json:"pre_open_pric"`
	PreHighPric        string `json:"pre_high_pric"`
	PreLowPric         string `json:"pre_low_pric"`
	BaseClosePric      string `json:"base_close_pric"`
	UplPric            string `json:"upl_pric"`
	LstPric            string `json:"lst_pric"`
	TrdeQtyUnit        string `json:"trde_qty_unit"`
	UncertLv           string `json:"uncert_lv"`
	CompAdvTp          string `json:"comp_adv_tp"`
	CurrUnit           string `json:"curr_unit"`
	OpenPric           string `json:"open_pric"`
	HighPric           string `json:"high_pric"`
	LowPric            string `json:"low_pric"`
	TrdSuspTp          string `json:"trd_susp_tp"`
	BaseExrt           string `json:"base_exrt"`
	ReturnCode         int    `json:"return_code"`
	ReturnMsg          string `json:"return_msg"`
}

// GetUSStockCurrentInfo calls Kiwoom usa20100 — 미국주식 현재가 종목정보.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetUSStockCurrentInfo(ctx context.Context, req *USStockCurrentInfoRequest) (*USStockCurrentInfoResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/mrkcond", "usa20100", req)
	if err != nil {
		return nil, err
	}
	var res USStockCurrentInfoResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockQuote10Request is the request payload for usa20101 (미국주식 현재가 10호가).
type USStockQuote10Request struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockQuote10Response is the response payload for usa20101 (미국주식 현재가 10호가).
type USStockQuote10Response struct {
	StexTp             string `json:"stex_tp"`
	StkCd              string `json:"stk_cd"`
	StkNm              string `json:"stk_nm"`
	StkEnm             string `json:"stk_enm"`
	CurPrc             string `json:"cur_prc"`
	PredPre            string `json:"pred_pre"`
	FluRt              string `json:"flu_rt"`
	TrdeQty            string `json:"trde_qty"`
	TrdePrica          string `json:"trde_prica"`
	OpenPric           string `json:"open_pric"`
	HighPric           string `json:"high_pric"`
	LowPric            string `json:"low_pric"`
	BidTm              string `json:"bid_tm"`
	Dt                 string `json:"dt"`
	PredPreSig         string `json:"pred_pre_sig"`
	FprSelBid          string `json:"fpr_sel_bid"`
	FprBuyBid          string `json:"fpr_buy_bid"`
	PreTrdeRt          string `json:"pre_trde_rt"`
	TrdeTernRt         string `json:"trde_tern_rt"`
	SelN1bid           string `json:"sel_1bid"`
	SelN2bid           string `json:"sel_2bid"`
	SelN3bid           string `json:"sel_3bid"`
	SelN4bid           string `json:"sel_4bid"`
	SelN5bid           string `json:"sel_5bid"`
	SelN6bid           string `json:"sel_6bid"`
	SelN7bid           string `json:"sel_7bid"`
	SelN8bid           string `json:"sel_8bid"`
	SelN9bid           string `json:"sel_9bid"`
	SelN10bid          string `json:"sel_10bid"`
	BuyN1bid           string `json:"buy_1bid"`
	BuyN2bid           string `json:"buy_2bid"`
	BuyN3bid           string `json:"buy_3bid"`
	BuyN4bid           string `json:"buy_4bid"`
	BuyN5bid           string `json:"buy_5bid"`
	BuyN6bid           string `json:"buy_6bid"`
	BuyN7bid           string `json:"buy_7bid"`
	BuyN8bid           string `json:"buy_8bid"`
	BuyN9bid           string `json:"buy_9bid"`
	BuyN10bid          string `json:"buy_10bid"`
	SelN1bidReq        string `json:"sel_1bid_req"`
	SelN2bidReq        string `json:"sel_2bid_req"`
	SelN3bidReq        string `json:"sel_3bid_req"`
	SelN4bidReq        string `json:"sel_4bid_req"`
	SelN5bidReq        string `json:"sel_5bid_req"`
	SelN6bidReq        string `json:"sel_6bid_req"`
	SelN7bidReq        string `json:"sel_7bid_req"`
	SelN8bidReq        string `json:"sel_8bid_req"`
	SelN9bidReq        string `json:"sel_9bid_req"`
	SelN10bidReq       string `json:"sel_10bid_req"`
	BuyN1bidReq        string `json:"buy_1bid_req"`
	BuyN2bidReq        string `json:"buy_2bid_req"`
	BuyN3bidReq        string `json:"buy_3bid_req"`
	BuyN4bidReq        string `json:"buy_4bid_req"`
	BuyN5bidReq        string `json:"buy_5bid_req"`
	BuyN6bidReq        string `json:"buy_6bid_req"`
	BuyN7bidReq        string `json:"buy_7bid_req"`
	BuyN8bidReq        string `json:"buy_8bid_req"`
	BuyN9bidReq        string `json:"buy_9bid_req"`
	BuyN10bidReq       string `json:"buy_10bid_req"`
	SelN1bidJubPre     string `json:"sel_1bid_jub_pre"`
	SelN2bidJubPre     string `json:"sel_2bid_jub_pre"`
	SelN3bidJubPre     string `json:"sel_3bid_jub_pre"`
	SelN4bidJubPre     string `json:"sel_4bid_jub_pre"`
	SelN5bidJubPre     string `json:"sel_5bid_jub_pre"`
	SelN6bidJubPre     string `json:"sel_6bid_jub_pre"`
	SelN7bidJubPre     string `json:"sel_7bid_jub_pre"`
	SelN8bidJubPre     string `json:"sel_8bid_jub_pre"`
	SelN9bidJubPre     string `json:"sel_9bid_jub_pre"`
	SelN10bidJubPre    string `json:"sel_10bid_jub_pre"`
	BuyN1thPreReqPre   string `json:"buy_1th_pre_req_pre"`
	BuyN1bidJubPre     string `json:"buy_1bid_jub_pre"`
	BuyN2bidJubPre     string `json:"buy_2bid_jub_pre"`
	BuyN3bidJubPre     string `json:"buy_3bid_jub_pre"`
	BuyN4bidJubPre     string `json:"buy_4bid_jub_pre"`
	BuyN5bidJubPre     string `json:"buy_5bid_jub_pre"`
	BuyN6bidJubPre     string `json:"buy_6bid_jub_pre"`
	BuyN7bidJubPre     string `json:"buy_7bid_jub_pre"`
	BuyN8bidJubPre     string `json:"buy_8bid_jub_pre"`
	BuyN9bidJubPre     string `json:"buy_9bid_jub_pre"`
	BuyN10bidJubPre    string `json:"buy_10bid_jub_pre"`
	TotSelReq          string `json:"tot_sel_req"`
	SelBidTotReqJubPre string `json:"sel_bid_tot_req_jub_pre"`
	TotBuyReq          string `json:"tot_buy_req"`
	BuyBidTotReqJubPre string `json:"buy_bid_tot_req_jub_pre"`
	NetprpsReq         string `json:"netprps_req"`
	NetslmtReq         string `json:"netslmt_req"`
	UplPric            string `json:"upl_pric"`
	BasePric           string `json:"base_pric"`
	ReturnCode         int    `json:"return_code"`
	ReturnMsg          string `json:"return_msg"`
}

// GetUSStockQuote10 calls Kiwoom usa20101 — 미국주식 현재가 10호가.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetUSStockQuote10(ctx context.Context, req *USStockQuote10Request) (*USStockQuote10Response, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/mrkcond", "usa20101", req)
	if err != nil {
		return nil, err
	}
	var res USStockQuote10Response
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockDetailedExecutionsRequest is the request payload for usa20150 (미국주식 상세 체결내역).
type USStockDetailedExecutionsRequest struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockDetailedExecutionsResponse is the response payload for usa20150 (미국주식 상세 체결내역).
type USStockDetailedExecutionsResponse struct {
	ResultList []USStockDetailedExecutionsResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USStockDetailedExecutionsResponseResultListItem is a list row in USStockDetailedExecutionsResponse.
type USStockDetailedExecutionsResponseResultListItem struct {
	CurPrc     string `json:"cur_prc"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	TrdeQty    string `json:"trde_qty"`
	CntrTm     string `json:"cntr_tm"`
	PredPreSig string `json:"pred_pre_sig"`
}

// GetUSStockDetailedExecutions calls Kiwoom usa20150 — 미국주식 상세 체결내역.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetUSStockDetailedExecutions(ctx context.Context, req *USStockDetailedExecutionsRequest) (*USStockDetailedExecutionsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/mrkcond", "usa20150", req)
	if err != nil {
		return nil, err
	}
	var res USStockDetailedExecutionsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockDailyExecutionsRequest is the request payload for usa20151 (미국주식 일별 체결내역).
type USStockDailyExecutionsRequest struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
	BaseDt string `json:"base_dt"`
}

// USStockDailyExecutionsResponse is the response payload for usa20151 (미국주식 일별 체결내역).
type USStockDailyExecutionsResponse struct {
	ResultList []USStockDailyExecutionsResponseResultListItem `json:"result_list"`
	ReturnCode int                                            `json:"return_code"`
	ReturnMsg  string                                         `json:"return_msg"`
}

// USStockDailyExecutionsResponseResultListItem is a list row in USStockDailyExecutionsResponse.
type USStockDailyExecutionsResponseResultListItem struct {
	Dt         string `json:"dt"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
}

// GetUSStockDailyExecutions calls Kiwoom usa20151 — 미국주식 일별 체결내역.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetUSStockDailyExecutions(ctx context.Context, req *USStockDailyExecutionsRequest) (*USStockDailyExecutionsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/mrkcond", "usa20151", req)
	if err != nil {
		return nil, err
	}
	var res USStockDailyExecutionsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockWatchlistGroupsRequest is the request payload for usa20200 (미국주식 관심종목 그룹 리스트 조회).
type USStockWatchlistGroupsRequest struct {
}

// USStockWatchlistGroupsResponse is the response payload for usa20200 (미국주식 관심종목 그룹 리스트 조회).
type USStockWatchlistGroupsResponse struct {
	Rtcd       string                                   `json:"rtcd"`
	Nofi       []USStockWatchlistGroupsResponseNofiItem `json:"nofi"`
	ReturnCode int                                      `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
}

// USStockWatchlistGroupsResponseNofiItem is a list row in USStockWatchlistGroupsResponse.
type USStockWatchlistGroupsResponseNofiItem struct {
	Gcod string `json:"gcod"`
	Name string `json:"name"`
}

// GetUSStockWatchlistGroups calls Kiwoom usa20200 — 미국주식 관심종목 그룹 리스트 조회.
// 관심종목 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockWatchlistGroups(ctx context.Context, req *USStockWatchlistGroupsRequest) (*USStockWatchlistGroupsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/watchlist", "usa20200", req)
	if err != nil {
		return nil, err
	}
	var res USStockWatchlistGroupsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockWatchlistGroupDetailRequest is the request payload for usa20201 (미국주식 관심종목 그룹 상세 조회).
type USStockWatchlistGroupDetailRequest struct {
	ArnGrpId string `json:"arn_grp_id"`
}

// USStockWatchlistGroupDetailResponse is the response payload for usa20201 (미국주식 관심종목 그룹 상세 조회).
type USStockWatchlistGroupDetailResponse struct {
	Rtcd       string                                        `json:"rtcd"`
	Nofj       []USStockWatchlistGroupDetailResponseNofjItem `json:"nofj"`
	ReturnCode int                                           `json:"return_code"`
	ReturnMsg  string                                        `json:"return_msg"`
}

// USStockWatchlistGroupDetailResponseNofjItem is a list row in USStockWatchlistGroupDetailResponse.
type USStockWatchlistGroupDetailResponseNofjItem struct {
	Cod2   string `json:"cod2"`
	Bgb    string `json:"bgb"`
	BgbClr string `json:"bgb_clr"`
	StexTp string `json:"stex_tp"`
}

// GetUSStockWatchlistGroupDetail calls Kiwoom usa20201 — 미국주식 관심종목 그룹 상세 조회.
// 관심종목 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockWatchlistGroupDetail(ctx context.Context, req *USStockWatchlistGroupDetailRequest) (*USStockWatchlistGroupDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/watchlist", "usa20201", req)
	if err != nil {
		return nil, err
	}
	var res USStockWatchlistGroupDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockConditionSearchListRequest is the request payload for usa20280 (미국주식 조건검색 목록조회).
type USStockConditionSearchListRequest struct {
	Trnm string `json:"trnm"`
}

// USStockConditionSearchListResponse is the response payload for usa20280 (미국주식 조건검색 목록조회).
type USStockConditionSearchListResponse struct {
	ReturnCode string                                       `json:"return_code"`
	ReturnMsg  string                                       `json:"return_msg"`
	Trnm       string                                       `json:"trnm"`
	Data       []USStockConditionSearchListResponseDataItem `json:"data"`
}

// USStockConditionSearchListResponseDataItem is a list row in USStockConditionSearchListResponse.
type USStockConditionSearchListResponseDataItem struct {
	Seq  string `json:"seq"`
	Name string `json:"name"`
}

// GetUSStockConditionSearchList calls Kiwoom usa20280 — 미국주식 조건검색 목록조회.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockConditionSearchList(ctx context.Context, req *USStockConditionSearchListRequest) (*USStockConditionSearchListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/websocket", "usa20280", req)
	if err != nil {
		return nil, err
	}
	var res USStockConditionSearchListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockConditionSearchRequest is the request payload for usa20281 (미국주식 조건검색 요청 일반).
type USStockConditionSearchRequest struct {
	Trnm       string `json:"trnm"`
	Seq        string `json:"seq"`
	SearchType string `json:"search_type"`
	ContYn     string `json:"cont_yn"`
	NextKey    string `json:"next_key"`
}

// USStockConditionSearchResponse is the response payload for usa20281 (미국주식 조건검색 요청 일반).
type USStockConditionSearchResponse struct {
	ReturnCode string                                   `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
	Trnm       string                                   `json:"trnm"`
	Seq        string                                   `json:"seq"`
	ContYn     string                                   `json:"cont_yn"`
	NextKey    string                                   `json:"next_key"`
	Data       []USStockConditionSearchResponseDataItem `json:"data"`
}

// USStockConditionSearchResponseDataItem is a list row in USStockConditionSearchResponse.
type USStockConditionSearchResponseDataItem struct {
	N9001  string `json:"9001"`
	N302   string `json:"302"`
	N10    string `json:"10"`
	N25    string `json:"25"`
	N11    string `json:"11"`
	N12    string `json:"12"`
	N13    string `json:"13"`
	N16    string `json:"16"`
	N17    string `json:"17"`
	N18    string `json:"18"`
	N318   string `json:"318"`
	StexTp string `json:"stex_tp"`
}

// GetUSStockConditionSearch calls Kiwoom usa20281 — 미국주식 조건검색 요청 일반.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockConditionSearch(ctx context.Context, req *USStockConditionSearchRequest) (*USStockConditionSearchResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/websocket", "usa20281", req)
	if err != nil {
		return nil, err
	}
	var res USStockConditionSearchResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockConditionSearchRealtimeRequest is the request payload for usa20290 (미국주식 조건검색 요청 실시간).
type USStockConditionSearchRealtimeRequest struct {
	Trnm       string `json:"trnm"`
	Seq        string `json:"seq"`
	SearchType string `json:"search_type"`
}

// USStockConditionSearchRealtimeResponse is the response payload for usa20290 (미국주식 조건검색 요청 실시간).
type USStockConditionSearchRealtimeResponse struct {
	ReturnCode string                                           `json:"return_code"`
	ReturnMsg  string                                           `json:"return_msg"`
	Trnm       string                                           `json:"trnm"`
	Seq        string                                           `json:"seq"`
	Data       []USStockConditionSearchRealtimeResponseDataItem `json:"data"`
}

// USStockConditionSearchRealtimeResponseDataItem is a list row in USStockConditionSearchRealtimeResponse.
type USStockConditionSearchRealtimeResponseDataItem struct {
	Jmcode string `json:"jmcode"`
	StexTp string `json:"stexTp"`
}

// GetUSStockConditionSearchRealtime calls Kiwoom usa20290 — 미국주식 조건검색 요청 실시간.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockConditionSearchRealtime(ctx context.Context, req *USStockConditionSearchRealtimeRequest) (*USStockConditionSearchRealtimeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/websocket", "usa20290", req)
	if err != nil {
		return nil, err
	}
	var res USStockConditionSearchRealtimeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ReleaseUSStockConditionSearchRealtimeRequest is the request payload for usa20291 (미국주식 조건검색 실시간 해제).
type ReleaseUSStockConditionSearchRealtimeRequest struct {
	Trnm string `json:"trnm"`
	Seq  string `json:"seq"`
}

// ReleaseUSStockConditionSearchRealtimeResponse is the response payload for usa20291 (미국주식 조건검색 실시간 해제).
type ReleaseUSStockConditionSearchRealtimeResponse struct {
	ReturnCode string `json:"return_code"`
	ReturnMsg  string `json:"return_msg"`
	Trnm       string `json:"trnm"`
	Seq        string `json:"seq"`
}

// ReleaseUSStockConditionSearchRealtime calls Kiwoom usa20291 — 미국주식 조건검색 실시간 해제.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) ReleaseUSStockConditionSearchRealtime(ctx context.Context, req *ReleaseUSStockConditionSearchRealtimeRequest) (*ReleaseUSStockConditionSearchRealtimeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/websocket", "usa20291", req)
	if err != nil {
		return nil, err
	}
	var res ReleaseUSStockConditionSearchRealtimeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockPeriodChangeRateRankRequest is the request payload for usa20510 (미국주식 기간별 등락률상위(주식/업종)).
type USStockPeriodChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	Tm           string `json:"tm"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockPeriodChangeRateRankResponse is the response payload for usa20510 (미국주식 기간별 등락률상위(주식/업종)).
type USStockPeriodChangeRateRankResponse struct {
	ResultList []USStockPeriodChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                 `json:"return_code"`
	ReturnMsg  string                                              `json:"return_msg"`
}

// USStockPeriodChangeRateRankResponseResultListItem is a list row in USStockPeriodChangeRateRankResponse.
type USStockPeriodChangeRateRankResponseResultListItem struct {
	Rank         string `json:"rank"`
	StexTp       string `json:"stex_tp"`
	StkCd        string `json:"stk_cd"`
	StkNm        string `json:"stk_nm"`
	StkEnm       string `json:"stk_enm"`
	StdtBasePric string `json:"stdt_base_pric"`
	EndtBasePric string `json:"endt_base_pric"`
	PredPreSig   string `json:"pred_pre_sig"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	StdtTrdeQty  string `json:"stdt_trde_qty"`
	EndtTrdeQty  string `json:"endt_trde_qty"`
}

// GetUSStockPeriodChangeRateRank calls Kiwoom usa20510 — 미국주식 기간별 등락률상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockPeriodChangeRateRank(ctx context.Context, req *USStockPeriodChangeRateRankRequest) (*USStockPeriodChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20510", req)
	if err != nil {
		return nil, err
	}
	var res USStockPeriodChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFPeriodChangeRateRankRequest is the request payload for usa20511 (미국주식 기간별 등락률상위(ETF)).
type USETFPeriodChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	StkCnd       string `json:"stk_cnd"`
	Tm           string `json:"tm"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFPeriodChangeRateRankResponse is the response payload for usa20511 (미국주식 기간별 등락률상위(ETF)).
type USETFPeriodChangeRateRankResponse struct {
	ResultList []USETFPeriodChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USETFPeriodChangeRateRankResponseResultListItem is a list row in USETFPeriodChangeRateRankResponse.
type USETFPeriodChangeRateRankResponseResultListItem struct {
	Rank         string `json:"rank"`
	StexTp       string `json:"stex_tp"`
	StkCd        string `json:"stk_cd"`
	StkNm        string `json:"stk_nm"`
	StkEnm       string `json:"stk_enm"`
	StdtBasePric string `json:"stdt_base_pric"`
	EndtBasePric string `json:"endt_base_pric"`
	PredPreSig   string `json:"pred_pre_sig"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	StdtTrdeQty  string `json:"stdt_trde_qty"`
	EndtTrdeQty  string `json:"endt_trde_qty"`
}

// GetUSETFPeriodChangeRateRank calls Kiwoom usa20511 — 미국주식 기간별 등락률상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFPeriodChangeRateRank(ctx context.Context, req *USETFPeriodChangeRateRankRequest) (*USETFPeriodChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20511", req)
	if err != nil {
		return nil, err
	}
	var res USETFPeriodChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USWatchlistPeriodChangeRateRankRequest is the request payload for usa20512 (미국주식 기간별 등락률상위(관심종목)).
type USWatchlistPeriodChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	Tm           string `json:"tm"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USWatchlistPeriodChangeRateRankRequestStkCdItem is a list row in USWatchlistPeriodChangeRateRankRequest.
type USWatchlistPeriodChangeRateRankRequestStkCdItem struct {
}

// USWatchlistPeriodChangeRateRankResponse is the response payload for usa20512 (미국주식 기간별 등락률상위(관심종목)).
type USWatchlistPeriodChangeRateRankResponse struct {
	ResultList []USWatchlistPeriodChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                     `json:"return_code"`
	ReturnMsg  string                                                  `json:"return_msg"`
}

// USWatchlistPeriodChangeRateRankResponseResultListItem is a list row in USWatchlistPeriodChangeRateRankResponse.
type USWatchlistPeriodChangeRateRankResponseResultListItem struct {
	Rank         string `json:"rank"`
	StexTp       string `json:"stex_tp"`
	StkCd        string `json:"stk_cd"`
	StkNm        string `json:"stk_nm"`
	StkEnm       string `json:"stk_enm"`
	StdtBasePric string `json:"stdt_base_pric"`
	EndtBasePric string `json:"endt_base_pric"`
	PredPreSig   string `json:"pred_pre_sig"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	StdtTrdeQty  string `json:"stdt_trde_qty"`
	EndtTrdeQty  string `json:"endt_trde_qty"`
}

// GetUSWatchlistPeriodChangeRateRank calls Kiwoom usa20512 — 미국주식 기간별 등락률상위(관심종목).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSWatchlistPeriodChangeRateRank(ctx context.Context, req *USWatchlistPeriodChangeRateRankRequest) (*USWatchlistPeriodChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20512", req)
	if err != nil {
		return nil, err
	}
	var res USWatchlistPeriodChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockVolumeSurgeRequest is the request payload for usa20520 (미국주식 거래량급등락(주식/업종)).
type USStockVolumeSurgeRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	Tm           string `json:"tm"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
}

// USStockVolumeSurgeResponse is the response payload for usa20520 (미국주식 거래량급등락(주식/업종)).
type USStockVolumeSurgeResponse struct {
	ResultList []USStockVolumeSurgeResponseResultListItem `json:"result_list"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// USStockVolumeSurgeResponseResultListItem is a list row in USStockVolumeSurgeResponse.
type USStockVolumeSurgeResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SdninRt    string `json:"sdnin_rt"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
}

// GetUSStockVolumeSurge calls Kiwoom usa20520 — 미국주식 거래량급등락(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockVolumeSurge(ctx context.Context, req *USStockVolumeSurgeRequest) (*USStockVolumeSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20520", req)
	if err != nil {
		return nil, err
	}
	var res USStockVolumeSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFVolumeSurgeRequest is the request payload for usa20521 (미국주식 거래량급등락(ETF)).
type USETFVolumeSurgeRequest struct {
	StexTp       string `json:"stex_tp"`
	Tm           string `json:"tm"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
}

// USETFVolumeSurgeResponse is the response payload for usa20521 (미국주식 거래량급등락(ETF)).
type USETFVolumeSurgeResponse struct {
	ResultList []USETFVolumeSurgeResponseResultListItem `json:"result_list"`
	ReturnCode int                                      `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
}

// USETFVolumeSurgeResponseResultListItem is a list row in USETFVolumeSurgeResponse.
type USETFVolumeSurgeResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SdninRt    string `json:"sdnin_rt"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
}

// GetUSETFVolumeSurge calls Kiwoom usa20521 — 미국주식 거래량급등락(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFVolumeSurge(ctx context.Context, req *USETFVolumeSurgeRequest) (*USETFVolumeSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20521", req)
	if err != nil {
		return nil, err
	}
	var res USETFVolumeSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockTodayVolumeRankRequest is the request payload for usa20530 (미국주식 당일 거래량 상위(주식/업종)).
type USStockTodayVolumeRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	QryTp        string `json:"qry_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockTodayVolumeRankResponse is the response payload for usa20530 (미국주식 당일 거래량 상위(주식/업종)).
type USStockTodayVolumeRankResponse struct {
	ResultList []USStockTodayVolumeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                            `json:"return_code"`
	ReturnMsg  string                                         `json:"return_msg"`
}

// USStockTodayVolumeRankResponseResultListItem is a list row in USStockTodayVolumeRankResponse.
type USStockTodayVolumeRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	PredRt     string `json:"pred_rt"`
	TrdePrica  string `json:"trde_prica"`
}

// GetUSStockTodayVolumeRank calls Kiwoom usa20530 — 미국주식 당일 거래량 상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockTodayVolumeRank(ctx context.Context, req *USStockTodayVolumeRankRequest) (*USStockTodayVolumeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20530", req)
	if err != nil {
		return nil, err
	}
	var res USStockTodayVolumeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFTodayVolumeRankRequest is the request payload for usa20531 (미국주식 당일 거래량 상위(ETF)).
type USETFTodayVolumeRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	QryTp        string `json:"qry_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFTodayVolumeRankResponse is the response payload for usa20531 (미국주식 당일 거래량 상위(ETF)).
type USETFTodayVolumeRankResponse struct {
	ResultList []USETFTodayVolumeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                          `json:"return_code"`
	ReturnMsg  string                                       `json:"return_msg"`
}

// USETFTodayVolumeRankResponseResultListItem is a list row in USETFTodayVolumeRankResponse.
type USETFTodayVolumeRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	PredRt     string `json:"pred_rt"`
	TrdePrica  string `json:"trde_prica"`
}

// GetUSETFTodayVolumeRank calls Kiwoom usa20531 — 미국주식 당일 거래량 상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFTodayVolumeRank(ctx context.Context, req *USETFTodayVolumeRankRequest) (*USETFTodayVolumeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20531", req)
	if err != nil {
		return nil, err
	}
	var res USETFTodayVolumeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockTodayTradingValueRankRequest is the request payload for usa20540 (미국주식 당일 거래대금 상위(주식/업종)).
type USStockTodayTradingValueRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockTodayTradingValueRankResponse is the response payload for usa20540 (미국주식 당일 거래대금 상위(주식/업종)).
type USStockTodayTradingValueRankResponse struct {
	ResultList []USStockTodayTradingValueRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                  `json:"return_code"`
	ReturnMsg  string                                               `json:"return_msg"`
}

// USStockTodayTradingValueRankResponseResultListItem is a list row in USStockTodayTradingValueRankResponse.
type USStockTodayTradingValueRankResponseResultListItem struct {
	Rank        string `json:"rank"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	PredTrdeQty string `json:"pred_trde_qty"`
	TrdePrica   string `json:"trde_prica"`
}

// GetUSStockTodayTradingValueRank calls Kiwoom usa20540 — 미국주식 당일 거래대금 상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockTodayTradingValueRank(ctx context.Context, req *USStockTodayTradingValueRankRequest) (*USStockTodayTradingValueRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20540", req)
	if err != nil {
		return nil, err
	}
	var res USStockTodayTradingValueRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFTodayTradingValueRankRequest is the request payload for usa20541 (미국주식 당일 거래대금 상위(ETF)).
type USETFTodayTradingValueRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFTodayTradingValueRankResponse is the response payload for usa20541 (미국주식 당일 거래대금 상위(ETF)).
type USETFTodayTradingValueRankResponse struct {
	ResultList []USETFTodayTradingValueRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                `json:"return_code"`
	ReturnMsg  string                                             `json:"return_msg"`
}

// USETFTodayTradingValueRankResponseResultListItem is a list row in USETFTodayTradingValueRankResponse.
type USETFTodayTradingValueRankResponseResultListItem struct {
	Rank        string `json:"rank"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	PredTrdeQty string `json:"pred_trde_qty"`
	TrdePrica   string `json:"trde_prica"`
}

// GetUSETFTodayTradingValueRank calls Kiwoom usa20541 — 미국주식 당일 거래대금 상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFTodayTradingValueRank(ctx context.Context, req *USETFTodayTradingValueRankRequest) (*USETFTodayTradingValueRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20541", req)
	if err != nil {
		return nil, err
	}
	var res USETFTodayTradingValueRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockMarketCapRankRequest is the request payload for usa20550 (미국주식 시가총액상위(주식/업종)).
type USStockMarketCapRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockMarketCapRankResponse is the response payload for usa20550 (미국주식 시가총액상위(주식/업종)).
type USStockMarketCapRankResponse struct {
	ResultList []USStockMarketCapRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                          `json:"return_code"`
	ReturnMsg  string                                       `json:"return_msg"`
}

// USStockMarketCapRankResponseResultListItem is a list row in USStockMarketCapRankResponse.
type USStockMarketCapRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	Mac        string `json:"mac"`
	TrdePreRt  string `json:"trde_pre_rt"`
	MacWght    string `json:"mac_wght"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
}

// GetUSStockMarketCapRank calls Kiwoom usa20550 — 미국주식 시가총액상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockMarketCapRank(ctx context.Context, req *USStockMarketCapRankRequest) (*USStockMarketCapRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20550", req)
	if err != nil {
		return nil, err
	}
	var res USStockMarketCapRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFMarketCapRankRequest is the request payload for usa20551 (미국주식 시가총액상위(ETF)).
type USETFMarketCapRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFMarketCapRankResponse is the response payload for usa20551 (미국주식 시가총액상위(ETF)).
type USETFMarketCapRankResponse struct {
	ResultList []USETFMarketCapRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// USETFMarketCapRankResponseResultListItem is a list row in USETFMarketCapRankResponse.
type USETFMarketCapRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	Mac        string `json:"mac"`
	TrdePreRt  string `json:"trde_pre_rt"`
	MacWght    string `json:"mac_wght"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
}

// GetUSETFMarketCapRank calls Kiwoom usa20551 — 미국주식 시가총액상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFMarketCapRank(ctx context.Context, req *USETFMarketCapRankRequest) (*USETFMarketCapRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20551", req)
	if err != nil {
		return nil, err
	}
	var res USETFMarketCapRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockPriceRangeRequest is the request payload for usa20570 (미국주식 가격대별주가(주식/업종)).
type USStockPriceRangeRequest struct {
	StexTp       string `json:"stex_tp"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	IndsCd       string `json:"inds_cd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd1     string `json:"pric_cnd1"`
	PricCnd2     string `json:"pric_cnd2"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockPriceRangeResponse is the response payload for usa20570 (미국주식 가격대별주가(주식/업종)).
type USStockPriceRangeResponse struct {
	StkNum       string                                    `json:"stk_num"`
	RisingStkNum string                                    `json:"rising_stk_num"`
	FlatStkNum   string                                    `json:"flat_stk_num"`
	FallStkNum   string                                    `json:"fall_stk_num"`
	ResultList   []USStockPriceRangeResponseResultListItem `json:"result_list"`
	ReturnCode   int                                       `json:"return_code"`
	ReturnMsg    string                                    `json:"return_msg"`
}

// USStockPriceRangeResponseResultListItem is a list row in USStockPriceRangeResponse.
type USStockPriceRangeResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
}

// GetUSStockPriceRange calls Kiwoom usa20570 — 미국주식 가격대별주가(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockPriceRange(ctx context.Context, req *USStockPriceRangeRequest) (*USStockPriceRangeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20570", req)
	if err != nil {
		return nil, err
	}
	var res USStockPriceRangeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFPriceRangeRequest is the request payload for usa20571 (미국주식 가격대별주가(ETF)).
type USETFPriceRangeRequest struct {
	StexTp       string `json:"stex_tp"`
	StkCnd       string `json:"stk_cnd"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd1     string `json:"pric_cnd1"`
	PricCnd2     string `json:"pric_cnd2"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFPriceRangeResponse is the response payload for usa20571 (미국주식 가격대별주가(ETF)).
type USETFPriceRangeResponse struct {
	StkNum       string                                  `json:"stk_num"`
	RisingStkNum string                                  `json:"rising_stk_num"`
	FlatStkNum   string                                  `json:"flat_stk_num"`
	FallStkNum   string                                  `json:"fall_stk_num"`
	ResultList   []USETFPriceRangeResponseResultListItem `json:"result_list"`
	ReturnCode   int                                     `json:"return_code"`
	ReturnMsg    string                                  `json:"return_msg"`
}

// USETFPriceRangeResponseResultListItem is a list row in USETFPriceRangeResponse.
type USETFPriceRangeResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
}

// GetUSETFPriceRange calls Kiwoom usa20571 — 미국주식 가격대별주가(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFPriceRange(ctx context.Context, req *USETFPriceRangeRequest) (*USETFPriceRangeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20571", req)
	if err != nil {
		return nil, err
	}
	var res USETFPriceRangeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockDailyPriceRequest is the request payload for usa20590 (미국주식 일별주가).
type USStockDailyPriceRequest struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
	BaseDt string `json:"base_dt"`
}

// USStockDailyPriceResponse is the response payload for usa20590 (미국주식 일별주가).
type USStockDailyPriceResponse struct {
	ResultList []USStockDailyPriceResponseResultListItem `json:"result_list"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// USStockDailyPriceResponseResultListItem is a list row in USStockDailyPriceResponse.
type USStockDailyPriceResponseResultListItem struct {
	Dt            string `json:"dt"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	TrdePrica     string `json:"trde_prica"`
	OpenPric      string `json:"open_pric"`
	HighPric      string `json:"high_pric"`
	LowPric       string `json:"low_pric"`
	BasePric      string `json:"base_pric"`
	BaseOpenFluRt string `json:"base_open_flu_rt"`
	BaseHighFluRt string `json:"base_high_flu_rt"`
	BaseLowFluRt  string `json:"base_low_flu_rt"`
}

// GetUSStockDailyPrice calls Kiwoom usa20590 — 미국주식 일별주가.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetUSStockDailyPrice(ctx context.Context, req *USStockDailyPriceRequest) (*USStockDailyPriceResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/mrkcond", "usa20590", req)
	if err != nil {
		return nil, err
	}
	var res USStockDailyPriceResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// KiwoomTopTradedUSStocksRequest is the request payload for usa20880 (키움 거래 상위 종목(미국주식)).
type KiwoomTopTradedUSStocksRequest struct {
	QryTp    string `json:"qry_tp"`
	DtUnitTp string `json:"dt_unit_tp"`
}

// KiwoomTopTradedUSStocksResponse is the response payload for usa20880 (키움 거래 상위 종목(미국주식)).
type KiwoomTopTradedUSStocksResponse struct {
	ResultList []KiwoomTopTradedUSStocksResponseResultListItem `json:"result_list"`
	ReturnCode int                                             `json:"return_code"`
	ReturnMsg  string                                          `json:"return_msg"`
}

// KiwoomTopTradedUSStocksResponseResultListItem is a list row in KiwoomTopTradedUSStocksResponse.
type KiwoomTopTradedUSStocksResponseResultListItem struct {
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	KwHighRank    string `json:"kw_high_rank"`
	KwHighRankSig string `json:"kw_high_rank_sig"`
	KwHighRankHl  string `json:"kw_high_rank_hl"`
	CurPrc        string `json:"cur_prc"`
	FluRt         string `json:"flu_rt"`
}

// GetKiwoomTopTradedUSStocks calls Kiwoom usa20880 — 키움 거래 상위 종목(미국주식).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetKiwoomTopTradedUSStocks(ctx context.Context, req *KiwoomTopTradedUSStocksRequest) (*KiwoomTopTradedUSStocksResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20880", req)
	if err != nil {
		return nil, err
	}
	var res KiwoomTopTradedUSStocksResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// KiwoomTopTradedUSETFsRequest is the request payload for usa20881 (키움 거래 상위 종목(미국 ETF)).
type KiwoomTopTradedUSETFsRequest struct {
	QryTp    string `json:"qry_tp"`
	DtUnitTp string `json:"dt_unit_tp"`
}

// KiwoomTopTradedUSETFsResponse is the response payload for usa20881 (키움 거래 상위 종목(미국 ETF)).
type KiwoomTopTradedUSETFsResponse struct {
	ResultList []KiwoomTopTradedUSETFsResponseResultListItem `json:"result_list"`
	ReturnCode int                                           `json:"return_code"`
	ReturnMsg  string                                        `json:"return_msg"`
}

// KiwoomTopTradedUSETFsResponseResultListItem is a list row in KiwoomTopTradedUSETFsResponse.
type KiwoomTopTradedUSETFsResponseResultListItem struct {
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	KwHighRank    string `json:"kw_high_rank"`
	KwHighRankSig string `json:"kw_high_rank_sig"`
	KwHighRankHl  string `json:"kw_high_rank_hl"`
	CurPrc        string `json:"cur_prc"`
	FluRt         string `json:"flu_rt"`
}

// GetKiwoomTopTradedUSETFs calls Kiwoom usa20881 — 키움 거래 상위 종목(미국 ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetKiwoomTopTradedUSETFs(ctx context.Context, req *KiwoomTopTradedUSETFsRequest) (*KiwoomTopTradedUSETFsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20881", req)
	if err != nil {
		return nil, err
	}
	var res KiwoomTopTradedUSETFsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockPreviousDayChangeRateRankRequest is the request payload for usa20910 (미국주식 전일대비 등락률상위(주식/업종)).
type USStockPreviousDayChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	IndsClsTp    string `json:"inds_cls_tp"`
	SortTp       string `json:"sort_tp"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
}

// USStockPreviousDayChangeRateRankResponse is the response payload for usa20910 (미국주식 전일대비 등락률상위(주식/업종)).
type USStockPreviousDayChangeRateRankResponse struct {
	ResultList []USStockPreviousDayChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                      `json:"return_code"`
	ReturnMsg  string                                                   `json:"return_msg"`
}

// USStockPreviousDayChangeRateRankResponseResultListItem is a list row in USStockPreviousDayChangeRateRankResponse.
type USStockPreviousDayChangeRateRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	SelReq     string `json:"sel_req"`
	BuyReq     string `json:"buy_req"`
	TrdeQty    string `json:"trde_qty"`
	Cnt        string `json:"cnt"`
}

// GetUSStockPreviousDayChangeRateRank calls Kiwoom usa20910 — 미국주식 전일대비 등락률상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockPreviousDayChangeRateRank(ctx context.Context, req *USStockPreviousDayChangeRateRankRequest) (*USStockPreviousDayChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20910", req)
	if err != nil {
		return nil, err
	}
	var res USStockPreviousDayChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFPreviousDayChangeRateRankRequest is the request payload for usa20911 (미국주식 전일대비 등락률상위(ETF)).
type USETFPreviousDayChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	SortTp       string `json:"sort_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
}

// USETFPreviousDayChangeRateRankResponse is the response payload for usa20911 (미국주식 전일대비 등락률상위(ETF)).
type USETFPreviousDayChangeRateRankResponse struct {
	ResultList []USETFPreviousDayChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                    `json:"return_code"`
	ReturnMsg  string                                                 `json:"return_msg"`
}

// USETFPreviousDayChangeRateRankResponseResultListItem is a list row in USETFPreviousDayChangeRateRankResponse.
type USETFPreviousDayChangeRateRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	SelReq     string `json:"sel_req"`
	BuyReq     string `json:"buy_req"`
	TrdeQty    string `json:"trde_qty"`
	Cnt        string `json:"cnt"`
}

// GetUSETFPreviousDayChangeRateRank calls Kiwoom usa20911 — 미국주식 전일대비 등락률상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFPreviousDayChangeRateRank(ctx context.Context, req *USETFPreviousDayChangeRateRankRequest) (*USETFPreviousDayChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20911", req)
	if err != nil {
		return nil, err
	}
	var res USETFPreviousDayChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockOpenChangeRateRankRequest is the request payload for usa20920 (미국주식 시가대비 등락률상위(주식/업종)).
type USStockOpenChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	SortTp       string `json:"sort_tp"`
}

// USStockOpenChangeRateRankResponse is the response payload for usa20920 (미국주식 시가대비 등락률상위(주식/업종)).
type USStockOpenChangeRateRankResponse struct {
	ResultList []USStockOpenChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USStockOpenChangeRateRankResponseResultListItem is a list row in USStockOpenChangeRateRankResponse.
type USStockOpenChangeRateRankResponseResultListItem struct {
	Rank        string `json:"rank"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	HighPric    string `json:"high_pric"`
	LowPric     string `json:"low_pric"`
	OpenPricPre string `json:"open_pric_pre"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	CntrTm      string `json:"cntr_tm"`
	OpenPric    string `json:"open_pric"`
}

// GetUSStockOpenChangeRateRank calls Kiwoom usa20920 — 미국주식 시가대비 등락률상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockOpenChangeRateRank(ctx context.Context, req *USStockOpenChangeRateRankRequest) (*USStockOpenChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20920", req)
	if err != nil {
		return nil, err
	}
	var res USStockOpenChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFOpenChangeRateRankRequest is the request payload for usa20921 (미국주식 시가대비 등락률상위(ETF)).
type USETFOpenChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	SortTp       string `json:"sort_tp"`
}

// USETFOpenChangeRateRankResponse is the response payload for usa20921 (미국주식 시가대비 등락률상위(ETF)).
type USETFOpenChangeRateRankResponse struct {
	ResultList []USETFOpenChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                             `json:"return_code"`
	ReturnMsg  string                                          `json:"return_msg"`
}

// USETFOpenChangeRateRankResponseResultListItem is a list row in USETFOpenChangeRateRankResponse.
type USETFOpenChangeRateRankResponseResultListItem struct {
	Rank        string `json:"rank"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	HighPric    string `json:"high_pric"`
	LowPric     string `json:"low_pric"`
	OpenPricPre string `json:"open_pric_pre"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	CntrTm      string `json:"cntr_tm"`
	OpenPric    string `json:"open_pric"`
}

// GetUSETFOpenChangeRateRank calls Kiwoom usa20921 — 미국주식 시가대비 등락률상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFOpenChangeRateRank(ctx context.Context, req *USETFOpenChangeRateRankRequest) (*USETFOpenChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20921", req)
	if err != nil {
		return nil, err
	}
	var res USETFOpenChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USWatchlistOpenChangeRateRankRequest is the request payload for usa20922 (미국주식 시가대비 등락률상위(관심종목)).
type USWatchlistOpenChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	SortTp       string `json:"sort_tp"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
}

// USWatchlistOpenChangeRateRankRequestStkCdItem is a list row in USWatchlistOpenChangeRateRankRequest.
type USWatchlistOpenChangeRateRankRequestStkCdItem struct {
}

// USWatchlistOpenChangeRateRankResponse is the response payload for usa20922 (미국주식 시가대비 등락률상위(관심종목)).
type USWatchlistOpenChangeRateRankResponse struct {
	ResultList []USWatchlistOpenChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                   `json:"return_code"`
	ReturnMsg  string                                                `json:"return_msg"`
}

// USWatchlistOpenChangeRateRankResponseResultListItem is a list row in USWatchlistOpenChangeRateRankResponse.
type USWatchlistOpenChangeRateRankResponseResultListItem struct {
	Rank        string `json:"rank"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	LowPric     string `json:"low_pric"`
	HighPric    string `json:"high_pric"`
	OpenPricPre string `json:"open_pric_pre"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	CntrTm      string `json:"cntr_tm"`
	OpenPric    string `json:"open_pric"`
}

// GetUSWatchlistOpenChangeRateRank calls Kiwoom usa20922 — 미국주식 시가대비 등락률상위(관심종목).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSWatchlistOpenChangeRateRank(ctx context.Context, req *USWatchlistOpenChangeRateRankRequest) (*USWatchlistOpenChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20922", req)
	if err != nil {
		return nil, err
	}
	var res USWatchlistOpenChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockPriceSurgeRequest is the request payload for usa20930 (미국주식 가격급등락(주식/업종)).
type USStockPriceSurgeRequest struct {
	StexTp       string `json:"stex_tp"`
	StkTp        string `json:"stk_tp"`
	IndsCd       string `json:"inds_cd"`
	StkCnd       string `json:"stk_cnd"`
	FluTp        string `json:"flu_tp"`
	TmTp         string `json:"tm_tp"`
	Tm           string `json:"tm"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockPriceSurgeResponse is the response payload for usa20930 (미국주식 가격급등락(주식/업종)).
type USStockPriceSurgeResponse struct {
	ResultList []USStockPriceSurgeResponseResultListItem `json:"result_list"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// USStockPriceSurgeResponseResultListItem is a list row in USStockPriceSurgeResponse.
type USStockPriceSurgeResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	BasePric   string `json:"base_pric"`
	CurPrc     string `json:"cur_prc"`
	BasePre    string `json:"base_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SdninRt    string `json:"sdnin_rt"`
}

// GetUSStockPriceSurge calls Kiwoom usa20930 — 미국주식 가격급등락(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockPriceSurge(ctx context.Context, req *USStockPriceSurgeRequest) (*USStockPriceSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20930", req)
	if err != nil {
		return nil, err
	}
	var res USStockPriceSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFPriceSurgeRequest is the request payload for usa20931 (미국주식 가격급등락(ETF)).
type USETFPriceSurgeRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	StkCnd       string `json:"stk_cnd"`
	FluTp        string `json:"flu_tp"`
	TmTp         string `json:"tm_tp"`
	Tm           string `json:"tm"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFPriceSurgeResponse is the response payload for usa20931 (미국주식 가격급등락(ETF)).
type USETFPriceSurgeResponse struct {
	ResultList []USETFPriceSurgeResponseResultListItem `json:"result_list"`
	ReturnCode int                                     `json:"return_code"`
	ReturnMsg  string                                  `json:"return_msg"`
}

// USETFPriceSurgeResponseResultListItem is a list row in USETFPriceSurgeResponse.
type USETFPriceSurgeResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	BasePric   string `json:"base_pric"`
	CurPrc     string `json:"cur_prc"`
	BasePre    string `json:"base_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SdninRt    string `json:"sdnin_rt"`
}

// GetUSETFPriceSurge calls Kiwoom usa20931 — 미국주식 가격급등락(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFPriceSurge(ctx context.Context, req *USETFPriceSurgeRequest) (*USETFPriceSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20931", req)
	if err != nil {
		return nil, err
	}
	var res USETFPriceSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
