// Code generated by cmd/genapis; DO NOT EDIT.

package kioom

import (
	"context"
	"net/http"
)

// MemberFirmListRequest is the request payload for ka10102 (회원사 리스트).
type MemberFirmListRequest struct {
}

// MemberFirmListResponse is the response payload for ka10102 (회원사 리스트).
type MemberFirmListResponse struct {
	List       []MemberFirmListResponseListItem `json:"list"`
	ReturnCode int                              `json:"return_code"`
	ReturnMsg  string                           `json:"return_msg"`
}

// MemberFirmListResponseListItem is a list row in MemberFirmListResponse.
type MemberFirmListResponseListItem struct {
	Code string `json:"code"`
	Name string `json:"name"`
	Gb   string `json:"gb"`
}

// GetMemberFirmList calls Kiwoom ka10102 — 회원사 리스트.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetMemberFirmList(ctx context.Context, req *MemberFirmListRequest) (*MemberFirmListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10102", req)
	if err != nil {
		return nil, err
	}
	var res MemberFirmListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockMemoRequest is the request payload for ka10103 (종목메모 조회).
type StockMemoRequest struct {
}

// StockMemoRequestInputListItem is a list row in StockMemoRequest.
type StockMemoRequestInputListItem struct {
	StkCd string `json:"stk_cd"`
}

// StockMemoResponse is the response payload for ka10103 (종목메모 조회).
type StockMemoResponse struct {
	Rtcd       string                            `json:"rtcd"`
	ResultList []StockMemoResponseResultListItem `json:"result_list"`
	ReturnCode int                               `json:"return_code"`
	ReturnMsg  string                            `json:"return_msg"`
}

// StockMemoResponseResultListItem is a list row in StockMemoResponse.
type StockMemoResponseResultListItem struct {
	StkCd string `json:"stk_cd"`
	Memo  string `json:"memo"`
}

// GetStockMemo calls Kiwoom ka10103 — 종목메모 조회.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetStockMemo(ctx context.Context, req *StockMemoRequest) (*StockMemoResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10103", req)
	if err != nil {
		return nil, err
	}
	var res StockMemoResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TodayTradingJournalRequest is the request payload for ka10170 (당일매매일지요청).
type TodayTradingJournalRequest struct {
	BaseDt  string `json:"base_dt"`
	OttksTp string `json:"ottks_tp"`
	ChCrdTp string `json:"ch_crd_tp"`
}

// TodayTradingJournalResponse is the response payload for ka10170 (당일매매일지요청).
type TodayTradingJournalResponse struct {
	TotSellAmt   string                                        `json:"tot_sell_amt"`
	TotBuyAmt    string                                        `json:"tot_buy_amt"`
	TotCmsnTax   string                                        `json:"tot_cmsn_tax"`
	TotExctAmt   string                                        `json:"tot_exct_amt"`
	TotPlAmt     string                                        `json:"tot_pl_amt"`
	TotPrftRt    string                                        `json:"tot_prft_rt"`
	TdyTrdeDiary []TodayTradingJournalResponseTdyTrdeDiaryItem `json:"tdy_trde_diary"`
	ReturnCode   int                                           `json:"return_code"`
	ReturnMsg    string                                        `json:"return_msg"`
}

// TodayTradingJournalResponseTdyTrdeDiaryItem is a list row in TodayTradingJournalResponse.
type TodayTradingJournalResponseTdyTrdeDiaryItem struct {
	StkNm      string `json:"stk_nm"`
	BuyAvgPric string `json:"buy_avg_pric"`
	BuyQty     string `json:"buy_qty"`
	SelAvgPric string `json:"sel_avg_pric"`
	SellQty    string `json:"sell_qty"`
	CmsnAlmTax string `json:"cmsn_alm_tax"`
	PlAmt      string `json:"pl_amt"`
	SellAmt    string `json:"sell_amt"`
	BuyAmt     string `json:"buy_amt"`
	PrftRt     string `json:"prft_rt"`
	StkCd      string `json:"stk_cd"`
}

// GetTodayTradingJournal calls Kiwoom ka10170 — 당일매매일지요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetTodayTradingJournal(ctx context.Context, req *TodayTradingJournalRequest) (*TodayTradingJournalResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10170", req)
	if err != nil {
		return nil, err
	}
	var res TodayTradingJournalResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ConditionSearchListRequest is the request payload for ka10171 (조건검색 목록조회).
type ConditionSearchListRequest struct {
	Trnm string `json:"trnm"`
}

// ConditionSearchListResponse is the response payload for ka10171 (조건검색 목록조회).
type ConditionSearchListResponse struct {
	ReturnCode string                                `json:"return_code"`
	ReturnMsg  string                                `json:"return_msg"`
	Trnm       string                                `json:"trnm"`
	Data       []ConditionSearchListResponseDataItem `json:"data"`
}

// ConditionSearchListResponseDataItem is a list row in ConditionSearchListResponse.
type ConditionSearchListResponseDataItem struct {
	Seq  string `json:"seq"`
	Name string `json:"name"`
}

// GetConditionSearchList calls Kiwoom ka10171 — 조건검색 목록조회.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) GetConditionSearchList(ctx context.Context, req *ConditionSearchListRequest) (*ConditionSearchListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/websocket", "ka10171", req)
	if err != nil {
		return nil, err
	}
	var res ConditionSearchListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ConditionSearchRequest is the request payload for ka10172 (조건검색 요청 일반).
type ConditionSearchRequest struct {
	Trnm       string `json:"trnm"`
	Seq        string `json:"seq"`
	SearchType string `json:"search_type"`
	StexTp     string `json:"stex_tp"`
	ContYn     string `json:"cont_yn"`
	NextKey    string `json:"next_key"`
}

// ConditionSearchResponse is the response payload for ka10172 (조건검색 요청 일반).
type ConditionSearchResponse struct {
	ReturnCode string                            `json:"return_code"`
	ReturnMsg  string                            `json:"return_msg"`
	Trnm       string                            `json:"trnm"`
	Seq        string                            `json:"seq"`
	ContYn     string                            `json:"cont_yn"`
	NextKey    string                            `json:"next_key"`
	Data       []ConditionSearchResponseDataItem `json:"data"`
}

// ConditionSearchResponseDataItem is a list row in ConditionSearchResponse.
type ConditionSearchResponseDataItem struct {
	N9001 string `json:"9001"`
	N302  string `json:"302"`
	N10   string `json:"10"`
	N25   string `json:"25"`
	N11   string `json:"11"`
	N12   string `json:"12"`
	N13   string `json:"13"`
	N16   string `json:"16"`
	N17   string `json:"17"`
	N18   string `json:"18"`
}

// GetConditionSearch calls Kiwoom ka10172 — 조건검색 요청 일반.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) GetConditionSearch(ctx context.Context, req *ConditionSearchRequest) (*ConditionSearchResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/websocket", "ka10172", req)
	if err != nil {
		return nil, err
	}
	var res ConditionSearchResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ConditionSearchRealtimeRequest is the request payload for ka10173 (조건검색 요청 실시간).
type ConditionSearchRealtimeRequest struct {
	Trnm       string `json:"trnm"`
	Seq        string `json:"seq"`
	SearchType string `json:"search_type"`
	StexTp     string `json:"stex_tp"`
}

// ConditionSearchRealtimeResponse is the response payload for ka10173 (조건검색 요청 실시간).
type ConditionSearchRealtimeResponse struct {
	ReturnCode string                                    `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
	Trnm       string                                    `json:"trnm"`
	Seq        string                                    `json:"seq"`
	Data       []ConditionSearchRealtimeResponseDataItem `json:"data"`
}

// ConditionSearchRealtimeResponseDataItem is a list row in ConditionSearchRealtimeResponse.
type ConditionSearchRealtimeResponseDataItem struct {
	Jmcode string `json:"jmcode"`
}

// GetConditionSearchRealtime calls Kiwoom ka10173 — 조건검색 요청 실시간.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) GetConditionSearchRealtime(ctx context.Context, req *ConditionSearchRealtimeRequest) (*ConditionSearchRealtimeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/websocket", "ka10173", req)
	if err != nil {
		return nil, err
	}
	var res ConditionSearchRealtimeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ReleaseConditionSearchRealtimeRequest is the request payload for ka10174 (조건검색 실시간 해제).
type ReleaseConditionSearchRealtimeRequest struct {
	Trnm string `json:"trnm"`
	Seq  string `json:"seq"`
}

// ReleaseConditionSearchRealtimeResponse is the response payload for ka10174 (조건검색 실시간 해제).
type ReleaseConditionSearchRealtimeResponse struct {
	ReturnCode string `json:"return_code"`
	ReturnMsg  string `json:"return_msg"`
	Trnm       string `json:"trnm"`
	Seq        string `json:"seq"`
}

// ReleaseConditionSearchRealtime calls Kiwoom ka10174 — 조건검색 실시간 해제.
// 조건검색 정보를 확인할 수 있습니다.
func (c *Client) ReleaseConditionSearchRealtime(ctx context.Context, req *ReleaseConditionSearchRealtimeRequest) (*ReleaseConditionSearchRealtimeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/websocket", "ka10174", req)
	if err != nil {
		return nil, err
	}
	var res ReleaseConditionSearchRealtimeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFReturnRateRequest is the request payload for ka40001 (ETF수익율요청).
type ETFReturnRateRequest struct {
	StkCd         string `json:"stk_cd"`
	EtfobjtIdexCd string `json:"etfobjt_idex_cd"`
	Dt            string `json:"dt"`
}

// ETFReturnRateResponse is the response payload for ka40001 (ETF수익율요청).
type ETFReturnRateResponse struct {
	EtfprftRtLst []ETFReturnRateResponseEtfprftRtLstItem `json:"etfprft_rt_lst"`
	ReturnCode   int                                     `json:"return_code"`
	ReturnMsg    string                                  `json:"return_msg"`
}

// ETFReturnRateResponseEtfprftRtLstItem is a list row in ETFReturnRateResponse.
type ETFReturnRateResponseEtfprftRtLstItem struct {
	EtfprftRt      string `json:"etfprft_rt"`
	CntrPrftRt     string `json:"cntr_prft_rt"`
	ForNetprpsQty  string `json:"for_netprps_qty"`
	OrgnNetprpsQty string `json:"orgn_netprps_qty"`
}

// GetETFReturnRate calls Kiwoom ka40001 — ETF수익율요청.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFReturnRate(ctx context.Context, req *ETFReturnRateRequest) (*ETFReturnRateResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40001", req)
	if err != nil {
		return nil, err
	}
	var res ETFReturnRateResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFStockInfoRequest is the request payload for ka40002 (ETF종목정보요청).
type ETFStockInfoRequest struct {
	StkCd string `json:"stk_cd"`
}

// ETFStockInfoResponse is the response payload for ka40002 (ETF종목정보요청).
type ETFStockInfoResponse struct {
	StkNm         string `json:"stk_nm"`
	EtfobjtIdexNm string `json:"etfobjt_idex_nm"`
	WonjuPric     string `json:"wonju_pric"`
	EtftxonType   string `json:"etftxon_type"`
	EtntxonType   string `json:"etntxon_type"`
	ReturnCode    int    `json:"return_code"`
	ReturnMsg     string `json:"return_msg"`
}

// GetETFStockInfo calls Kiwoom ka40002 — ETF종목정보요청.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFStockInfo(ctx context.Context, req *ETFStockInfoRequest) (*ETFStockInfoResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40002", req)
	if err != nil {
		return nil, err
	}
	var res ETFStockInfoResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFDailyTrendRequest is the request payload for ka40003 (ETF일별추이요청).
type ETFDailyTrendRequest struct {
	StkCd string `json:"stk_cd"`
}

// ETFDailyTrendResponse is the response payload for ka40003 (ETF일별추이요청).
type ETFDailyTrendResponse struct {
	EtfdalyTrnsn []ETFDailyTrendResponseEtfdalyTrnsnItem `json:"etfdaly_trnsn"`
	ReturnCode   int                                     `json:"return_code"`
	ReturnMsg    string                                  `json:"return_msg"`
}

// ETFDailyTrendResponseEtfdalyTrnsnItem is a list row in ETFDailyTrendResponse.
type ETFDailyTrendResponseEtfdalyTrnsnItem struct {
	CntrDt          string `json:"cntr_dt"`
	CurPrc          string `json:"cur_prc"`
	PreSig          string `json:"pre_sig"`
	PredPre         string `json:"pred_pre"`
	PreRt           string `json:"pre_rt"`
	TrdeQty         string `json:"trde_qty"`
	Nav             string `json:"nav"`
	AccTrdePrica    string `json:"acc_trde_prica"`
	NavidexDisptyRt string `json:"navidex_dispty_rt"`
	NavetfdisptyRt  string `json:"navetfdispty_rt"`
	TraceEorRt      string `json:"trace_eor_rt"`
	TraceCurPrc     string `json:"trace_cur_prc"`
	TracePredPre    string `json:"trace_pred_pre"`
	TracePreSig     string `json:"trace_pre_sig"`
}

// GetETFDailyTrend calls Kiwoom ka40003 — ETF일별추이요청.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFDailyTrend(ctx context.Context, req *ETFDailyTrendRequest) (*ETFDailyTrendResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40003", req)
	if err != nil {
		return nil, err
	}
	var res ETFDailyTrendResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFFullQuoteRequest is the request payload for ka40004 (ETF전체시세요청).
type ETFFullQuoteRequest struct {
	TxonType  string `json:"txon_type"`
	Navpre    string `json:"navpre"`
	Mngmcomp  string `json:"mngmcomp"`
	TxonYn    string `json:"txon_yn"`
	TraceIdex string `json:"trace_idex"`
	StexTp    string `json:"stex_tp"`
}

// ETFFullQuoteResponse is the response payload for ka40004 (ETF전체시세요청).
type ETFFullQuoteResponse struct {
	EtfallMrpr []ETFFullQuoteResponseEtfallMrprItem `json:"etfall_mrpr"`
	ReturnCode int                                  `json:"return_code"`
	ReturnMsg  string                               `json:"return_msg"`
}

// ETFFullQuoteResponseEtfallMrprItem is a list row in ETFFullQuoteResponse.
type ETFFullQuoteResponseEtfallMrprItem struct {
	StkCd       string `json:"stk_cd"`
	StkCls      string `json:"stk_cls"`
	StkNm       string `json:"stk_nm"`
	ClosePric   string `json:"close_pric"`
	PreSig      string `json:"pre_sig"`
	PredPre     string `json:"pred_pre"`
	PreRt       string `json:"pre_rt"`
	TrdeQty     string `json:"trde_qty"`
	Nav         string `json:"nav"`
	TraceEorRt  string `json:"trace_eor_rt"`
	Txbs        string `json:"txbs"`
	DvidBfBase  string `json:"dvid_bf_base"`
	PredDvida   string `json:"pred_dvida"`
	TraceIdexNm string `json:"trace_idex_nm"`
	Drng        string `json:"drng"`
	TraceIdexCd string `json:"trace_idex_cd"`
	TraceIdex   string `json:"trace_idex"`
	TraceFluRt  string `json:"trace_flu_rt"`
}

// GetETFFullQuote calls Kiwoom ka40004 — ETF전체시세요청.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFFullQuote(ctx context.Context, req *ETFFullQuoteRequest) (*ETFFullQuoteResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40004", req)
	if err != nil {
		return nil, err
	}
	var res ETFFullQuoteResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFIntradayTrendRequest is the request payload for ka40006 (ETF시간대별추이요청).
type ETFIntradayTrendRequest struct {
	StkCd string `json:"stk_cd"`
}

// ETFIntradayTrendResponse is the response payload for ka40006 (ETF시간대별추이요청).
type ETFIntradayTrendResponse struct {
	StkNm         string                                     `json:"stk_nm"`
	EtfobjtIdexNm string                                     `json:"etfobjt_idex_nm"`
	WonjuPric     string                                     `json:"wonju_pric"`
	EtftxonType   string                                     `json:"etftxon_type"`
	EtntxonType   string                                     `json:"etntxon_type"`
	EtftislTrnsn  []ETFIntradayTrendResponseEtftislTrnsnItem `json:"etftisl_trnsn"`
	ReturnCode    int                                        `json:"return_code"`
	ReturnMsg     string                                     `json:"return_msg"`
}

// ETFIntradayTrendResponseEtftislTrnsnItem is a list row in ETFIntradayTrendResponse.
type ETFIntradayTrendResponseEtftislTrnsnItem struct {
	Tm                  string `json:"tm"`
	ClosePric           string `json:"close_pric"`
	PreSig              string `json:"pre_sig"`
	PredPre             string `json:"pred_pre"`
	FluRt               string `json:"flu_rt"`
	TrdeQty             string `json:"trde_qty"`
	Nav                 string `json:"nav"`
	TrdePrica           string `json:"trde_prica"`
	Navidex             string `json:"navidex"`
	Navetf              string `json:"navetf"`
	Trace               string `json:"trace"`
	TraceIdex           string `json:"trace_idex"`
	TraceIdexPredPre    string `json:"trace_idex_pred_pre"`
	TraceIdexPredPreSig string `json:"trace_idex_pred_pre_sig"`
}

// GetETFIntradayTrend calls Kiwoom ka40006 — ETF시간대별추이요청.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFIntradayTrend(ctx context.Context, req *ETFIntradayTrendRequest) (*ETFIntradayTrendResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40006", req)
	if err != nil {
		return nil, err
	}
	var res ETFIntradayTrendResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFIntradayExecutionsRequest is the request payload for ka40007 (ETF시간대별체결요청).
type ETFIntradayExecutionsRequest struct {
	StkCd string `json:"stk_cd"`
}

// ETFIntradayExecutionsResponse is the response payload for ka40007 (ETF시간대별체결요청).
type ETFIntradayExecutionsResponse struct {
	StkCls           string                                              `json:"stk_cls"`
	StkNm            string                                              `json:"stk_nm"`
	EtfobjtIdexNm    string                                              `json:"etfobjt_idex_nm"`
	EtfobjtIdexCd    string                                              `json:"etfobjt_idex_cd"`
	ObjtIdexPreRt    string                                              `json:"objt_idex_pre_rt"`
	WonjuPric        string                                              `json:"wonju_pric"`
	EtftislCntrArray []ETFIntradayExecutionsResponseEtftislCntrArrayItem `json:"etftisl_cntr_array"`
	ReturnCode       int                                                 `json:"return_code"`
	ReturnMsg        string                                              `json:"return_msg"`
}

// ETFIntradayExecutionsResponseEtftislCntrArrayItem is a list row in ETFIntradayExecutionsResponse.
type ETFIntradayExecutionsResponseEtftislCntrArrayItem struct {
	CntrTm  string `json:"cntr_tm"`
	CurPrc  string `json:"cur_prc"`
	PreSig  string `json:"pre_sig"`
	PredPre string `json:"pred_pre"`
	TrdeQty string `json:"trde_qty"`
	StexTp  string `json:"stex_tp"`
}

// GetETFIntradayExecutions calls Kiwoom ka40007 — ETF시간대별체결요청.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFIntradayExecutions(ctx context.Context, req *ETFIntradayExecutionsRequest) (*ETFIntradayExecutionsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40007", req)
	if err != nil {
		return nil, err
	}
	var res ETFIntradayExecutionsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFDailyExecutionsRequest is the request payload for ka40008 (ETF일자별체결요청).
type ETFDailyExecutionsRequest struct {
	StkCd string `json:"stk_cd"`
}

// ETFDailyExecutionsResponse is the response payload for ka40008 (ETF일자별체결요청).
type ETFDailyExecutionsResponse struct {
	CntrTm             string                                             `json:"cntr_tm"`
	CurPrc             string                                             `json:"cur_prc"`
	PreSig             string                                             `json:"pre_sig"`
	PredPre            string                                             `json:"pred_pre"`
	TrdeQty            string                                             `json:"trde_qty"`
	EtfnetprpsQtyArray []ETFDailyExecutionsResponseEtfnetprpsQtyArrayItem `json:"etfnetprps_qty_array"`
	ReturnCode         int                                                `json:"return_code"`
	ReturnMsg          string                                             `json:"return_msg"`
}

// ETFDailyExecutionsResponseEtfnetprpsQtyArrayItem is a list row in ETFDailyExecutionsResponse.
type ETFDailyExecutionsResponseEtfnetprpsQtyArrayItem struct {
	Dt             string `json:"dt"`
	CurPrcN        string `json:"cur_prc_n"`
	PreSigN        string `json:"pre_sig_n"`
	PredPreN       string `json:"pred_pre_n"`
	AccTrdeQty     string `json:"acc_trde_qty"`
	ForNetprpsQty  string `json:"for_netprps_qty"`
	OrgnNetprpsQty string `json:"orgn_netprps_qty"`
}

// GetETFDailyExecutions calls Kiwoom ka40008 — ETF일자별체결요청.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFDailyExecutions(ctx context.Context, req *ETFDailyExecutionsRequest) (*ETFDailyExecutionsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40008", req)
	if err != nil {
		return nil, err
	}
	var res ETFDailyExecutionsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFIntradayNAVRequest is the request payload for ka40009 (ETF시간대별NAV현황).
type ETFIntradayNAVRequest struct {
	StkCd string `json:"stk_cd"`
}

// ETFIntradayNAVResponse is the response payload for ka40009 (ETF시간대별NAV현황).
type ETFIntradayNAVResponse struct {
	Etfnavarray []ETFIntradayNAVResponseEtfnavarrayItem `json:"etfnavarray"`
	ReturnCode  int                                     `json:"return_code"`
	ReturnMsg   string                                  `json:"return_msg"`
}

// ETFIntradayNAVResponseEtfnavarrayItem is a list row in ETFIntradayNAVResponse.
type ETFIntradayNAVResponseEtfnavarrayItem struct {
	Nav        string `json:"nav"`
	NavpredPre string `json:"navpred_pre"`
	NavfluRt   string `json:"navflu_rt"`
	TraceEorRt string `json:"trace_eor_rt"`
	DisptyRt   string `json:"dispty_rt"`
	Stkcnt     string `json:"stkcnt"`
	BasePric   string `json:"base_pric"`
	ForRmndQty string `json:"for_rmnd_qty"`
	ReplPric   string `json:"repl_pric"`
	ConvPric   string `json:"conv_pric"`
	Drstk      string `json:"drstk"`
	WonjuPric  string `json:"wonju_pric"`
}

// GetETFIntradayNAV calls Kiwoom ka40009 — ETF시간대별NAV현황.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFIntradayNAV(ctx context.Context, req *ETFIntradayNAVRequest) (*ETFIntradayNAVResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40009", req)
	if err != nil {
		return nil, err
	}
	var res ETFIntradayNAVResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ETFIntradaySupplyDemandRequest is the request payload for ka40010 (ETF시간대별수급현황).
type ETFIntradaySupplyDemandRequest struct {
	StkCd string `json:"stk_cd"`
}

// ETFIntradaySupplyDemandResponse is the response payload for ka40010 (ETF시간대별수급현황).
type ETFIntradaySupplyDemandResponse struct {
	EtftislTrnsn []ETFIntradaySupplyDemandResponseEtftislTrnsnItem `json:"etftisl_trnsn"`
	ReturnCode   int                                               `json:"return_code"`
	ReturnMsg    string                                            `json:"return_msg"`
}

// ETFIntradaySupplyDemandResponseEtftislTrnsnItem is a list row in ETFIntradaySupplyDemandResponse.
type ETFIntradaySupplyDemandResponseEtftislTrnsnItem struct {
	CurPrc     string `json:"cur_prc"`
	PreSig     string `json:"pre_sig"`
	PredPre    string `json:"pred_pre"`
	TrdeQty    string `json:"trde_qty"`
	ForNetprps string `json:"for_netprps"`
}

// GetETFIntradaySupplyDemand calls Kiwoom ka40010 — ETF시간대별수급현황.
// ETF 정보를 확인할 수 있습니다.
func (c *Client) GetETFIntradaySupplyDemand(ctx context.Context, req *ETFIntradaySupplyDemandRequest) (*ETFIntradaySupplyDemandResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/etf", "ka40010", req)
	if err != nil {
		return nil, err
	}
	var res ETFIntradaySupplyDemandResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyEstimatedCustodyAssetsRequest is the request payload for kt00002 (일별추정예탁자산현황요청).
type DailyEstimatedCustodyAssetsRequest struct {
	StartDt string `json:"start_dt"`
	EndDt   string `json:"end_dt"`
}

// DailyEstimatedCustodyAssetsResponse is the response payload for kt00002 (일별추정예탁자산현황요청).
type DailyEstimatedCustodyAssetsResponse struct {
	DalyPrsmDpstAsetAmtPrst []DailyEstimatedCustodyAssetsResponseDalyPrsmDpstAsetAmtPrstItem `json:"daly_prsm_dpst_aset_amt_prst"`
	ReturnCode              int                                                              `json:"return_code"`
	ReturnMsg               string                                                           `json:"return_msg"`
}

// DailyEstimatedCustodyAssetsResponseDalyPrsmDpstAsetAmtPrstItem is a list row in DailyEstimatedCustodyAssetsResponse.
type DailyEstimatedCustodyAssetsResponseDalyPrsmDpstAsetAmtPrstItem struct {
	Dt                      string `json:"dt"`
	Entr                    string `json:"entr"`
	GrntUseAmt              string `json:"grnt_use_amt"`
	CrdLoan                 string `json:"crd_loan"`
	LsGrnt                  string `json:"ls_grnt"`
	ReplAmt                 string `json:"repl_amt"`
	PrsmDpstAsetAmt         string `json:"prsm_dpst_aset_amt"`
	PrsmDpstAsetAmtBncrSkip string `json:"prsm_dpst_aset_amt_bncr_skip"`
}

// GetDailyEstimatedCustodyAssets calls Kiwoom kt00002 — 일별추정예탁자산현황요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetDailyEstimatedCustodyAssets(ctx context.Context, req *DailyEstimatedCustodyAssetsRequest) (*DailyEstimatedCustodyAssetsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00002", req)
	if err != nil {
		return nil, err
	}
	var res DailyEstimatedCustodyAssetsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// EstimatedAssetsRequest is the request payload for kt00003 (추정자산조회요청).
type EstimatedAssetsRequest struct {
	QryTp string `json:"qry_tp"`
}

// EstimatedAssetsResponse is the response payload for kt00003 (추정자산조회요청).
type EstimatedAssetsResponse struct {
	PrsmDpstAsetAmt string `json:"prsm_dpst_aset_amt"`
	ReturnCode      int    `json:"return_code"`
	ReturnMsg       string `json:"return_msg"`
}

// GetEstimatedAssets calls Kiwoom kt00003 — 추정자산조회요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetEstimatedAssets(ctx context.Context, req *EstimatedAssetsRequest) (*EstimatedAssetsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00003", req)
	if err != nil {
		return nil, err
	}
	var res EstimatedAssetsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccountEvaluationRequest is the request payload for kt00004 (계좌평가현황요청).
type AccountEvaluationRequest struct {
	QryTp      string `json:"qry_tp"`
	DmstStexTp string `json:"dmst_stex_tp"`
}

// AccountEvaluationResponse is the response payload for kt00004 (계좌평가현황요청).
type AccountEvaluationResponse struct {
	AcntNm          string                                         `json:"acnt_nm"`
	BrchNm          string                                         `json:"brch_nm"`
	Entr            string                                         `json:"entr"`
	D2Entra         string                                         `json:"d2_entra"`
	TotEstAmt       string                                         `json:"tot_est_amt"`
	AsetEvltAmt     string                                         `json:"aset_evlt_amt"`
	TotPurAmt       string                                         `json:"tot_pur_amt"`
	PrsmDpstAsetAmt string                                         `json:"prsm_dpst_aset_amt"`
	TotGrntSella    string                                         `json:"tot_grnt_sella"`
	TdyLspftAmt     string                                         `json:"tdy_lspft_amt"`
	InvtBsamt       string                                         `json:"invt_bsamt"`
	LspftAmt        string                                         `json:"lspft_amt"`
	TdyLspft        string                                         `json:"tdy_lspft"`
	Lspft2          string                                         `json:"lspft2"`
	Lspft           string                                         `json:"lspft"`
	TdyLspftRt      string                                         `json:"tdy_lspft_rt"`
	LspftRatio      string                                         `json:"lspft_ratio"`
	LspftRt         string                                         `json:"lspft_rt"`
	StkAcntEvltPrst []AccountEvaluationResponseStkAcntEvltPrstItem `json:"stk_acnt_evlt_prst"`
	ReturnCode      int                                            `json:"return_code"`
	ReturnMsg       string                                         `json:"return_msg"`
}

// AccountEvaluationResponseStkAcntEvltPrstItem is a list row in AccountEvaluationResponse.
type AccountEvaluationResponseStkAcntEvltPrstItem struct {
	StkCd     string `json:"stk_cd"`
	StkNm     string `json:"stk_nm"`
	RmndQty   string `json:"rmnd_qty"`
	AvgPrc    string `json:"avg_prc"`
	CurPrc    string `json:"cur_prc"`
	EvltAmt   string `json:"evlt_amt"`
	PlAmt     string `json:"pl_amt"`
	PlRt      string `json:"pl_rt"`
	LoanDt    string `json:"loan_dt"`
	PurAmt    string `json:"pur_amt"`
	SetlRemn  string `json:"setl_remn"`
	PredBuyq  string `json:"pred_buyq"`
	PredSellq string `json:"pred_sellq"`
	TdyBuyq   string `json:"tdy_buyq"`
	TdySellq  string `json:"tdy_sellq"`
}

// GetAccountEvaluation calls Kiwoom kt00004 — 계좌평가현황요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetAccountEvaluation(ctx context.Context, req *AccountEvaluationRequest) (*AccountEvaluationResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00004", req)
	if err != nil {
		return nil, err
	}
	var res AccountEvaluationResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExecutionBalanceRequest is the request payload for kt00005 (체결잔고요청).
type ExecutionBalanceRequest struct {
	DmstStexTp string `json:"dmst_stex_tp"`
}

// ExecutionBalanceResponse is the response payload for kt00005 (체결잔고요청).
type ExecutionBalanceResponse struct {
	Entr              string                                    `json:"entr"`
	EntrD1            string                                    `json:"entr_d1"`
	EntrD2            string                                    `json:"entr_d2"`
	PymnAlowAmt       string                                    `json:"pymn_alow_amt"`
	UnclStkAmt        string                                    `json:"uncl_stk_amt"`
	ReplAmt           string                                    `json:"repl_amt"`
	RghtReplAmt       string                                    `json:"rght_repl_amt"`
	OrdAlowa          string                                    `json:"ord_alowa"`
	ChUncla           string                                    `json:"ch_uncla"`
	CrdIntNpayGold    string                                    `json:"crd_int_npay_gold"`
	EtcLoana          string                                    `json:"etc_loana"`
	NrpyLoan          string                                    `json:"nrpy_loan"`
	ProfaCh           string                                    `json:"profa_ch"`
	ReplProfa         string                                    `json:"repl_profa"`
	StkBuyTotAmt      string                                    `json:"stk_buy_tot_amt"`
	EvltAmtTot        string                                    `json:"evlt_amt_tot"`
	TotPlTot          string                                    `json:"tot_pl_tot"`
	TotPlRt           string                                    `json:"tot_pl_rt"`
	TotReBuyAlowa     string                                    `json:"tot_re_buy_alowa"`
	N20ordAlowAmt     string                                    `json:"20ord_alow_amt"`
	N30ordAlowAmt     string                                    `json:"30ord_alow_amt"`
	N40ordAlowAmt     string                                    `json:"40ord_alow_amt"`
	N50ordAlowAmt     string                                    `json:"50ord_alow_amt"`
	N60ordAlowAmt     string                                    `json:"60ord_alow_amt"`
	N100ordAlowAmt    string                                    `json:"100ord_alow_amt"`
	CrdLoanTot        string                                    `json:"crd_loan_tot"`
	CrdLoanLsTot      string                                    `json:"crd_loan_ls_tot"`
	CrdGrntRt         string                                    `json:"crd_grnt_rt"`
	DpstGrntUseAmtAmt string                                    `json:"dpst_grnt_use_amt_amt"`
	GrntLoanAmt       string                                    `json:"grnt_loan_amt"`
	StkCntrRemn       []ExecutionBalanceResponseStkCntrRemnItem `json:"stk_cntr_remn"`
	ReturnCode        int                                       `json:"return_code"`
	ReturnMsg         string                                    `json:"return_msg"`
}

// ExecutionBalanceResponseStkCntrRemnItem is a list row in ExecutionBalanceResponse.
type ExecutionBalanceResponseStkCntrRemnItem struct {
	CrdTp     string `json:"crd_tp"`
	LoanDt    string `json:"loan_dt"`
	ExprDt    string `json:"expr_dt"`
	StkCd     string `json:"stk_cd"`
	StkNm     string `json:"stk_nm"`
	SetlRemn  string `json:"setl_remn"`
	CurQty    string `json:"cur_qty"`
	CurPrc    string `json:"cur_prc"`
	BuyUv     string `json:"buy_uv"`
	PurAmt    string `json:"pur_amt"`
	EvltAmt   string `json:"evlt_amt"`
	EvltvPrft string `json:"evltv_prft"`
	PlRt      string `json:"pl_rt"`
}

// GetExecutionBalance calls Kiwoom kt00005 — 체결잔고요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetExecutionBalance(ctx context.Context, req *ExecutionBalanceRequest) (*ExecutionBalanceResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00005", req)
	if err != nil {
		return nil, err
	}
	var res ExecutionBalanceResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccountOrderExecutionDetailRequest is the request payload for kt00007 (계좌별주문체결내역상세요청).
type AccountOrderExecutionDetailRequest struct {
	OrdDt      string `json:"ord_dt"`
	QryTp      string `json:"qry_tp"`
	StkBondTp  string `json:"stk_bond_tp"`
	SellTp     string `json:"sell_tp"`
	StkCd      string `json:"stk_cd"`
	FrOrdNo    string `json:"fr_ord_no"`
	DmstStexTp string `json:"dmst_stex_tp"`
}

// AccountOrderExecutionDetailResponse is the response payload for kt00007 (계좌별주문체결내역상세요청).
type AccountOrderExecutionDetailResponse struct {
	AcntOrdCntrPrpsDtl []AccountOrderExecutionDetailResponseAcntOrdCntrPrpsDtlItem `json:"acnt_ord_cntr_prps_dtl"`
	ReturnCode         int                                                         `json:"return_code"`
	ReturnMsg          string                                                      `json:"return_msg"`
}

// AccountOrderExecutionDetailResponseAcntOrdCntrPrpsDtlItem is a list row in AccountOrderExecutionDetailResponse.
type AccountOrderExecutionDetailResponseAcntOrdCntrPrpsDtlItem struct {
	OrdNo      string `json:"ord_no"`
	StkCd      string `json:"stk_cd"`
	TrdeTp     string `json:"trde_tp"`
	CrdTp      string `json:"crd_tp"`
	OrdQty     string `json:"ord_qty"`
	OrdUv      string `json:"ord_uv"`
	CnfmQty    string `json:"cnfm_qty"`
	AcptTp     string `json:"acpt_tp"`
	RsrvTp     string `json:"rsrv_tp"`
	OrdTm      string `json:"ord_tm"`
	OriOrd     string `json:"ori_ord"`
	StkNm      string `json:"stk_nm"`
	IoTpNm     string `json:"io_tp_nm"`
	LoanDt     string `json:"loan_dt"`
	CntrQty    string `json:"cntr_qty"`
	CntrUv     string `json:"cntr_uv"`
	OrdRemnq   string `json:"ord_remnq"`
	CommOrdTp  string `json:"comm_ord_tp"`
	MdfyCncl   string `json:"mdfy_cncl"`
	CnfmTm     string `json:"cnfm_tm"`
	DmstStexTp string `json:"dmst_stex_tp"`
	CondUv     string `json:"cond_uv"`
}

// GetAccountOrderExecutionDetail calls Kiwoom kt00007 — 계좌별주문체결내역상세요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetAccountOrderExecutionDetail(ctx context.Context, req *AccountOrderExecutionDetailRequest) (*AccountOrderExecutionDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00007", req)
	if err != nil {
		return nil, err
	}
	var res AccountOrderExecutionDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccountNextDaySettlementRequest is the request payload for kt00008 (계좌별익일결제예정내역요청).
type AccountNextDaySettlementRequest struct {
	StrtDcdSeq string `json:"strt_dcd_seq"`
}

// AccountNextDaySettlementResponse is the response payload for kt00008 (계좌별익일결제예정내역요청).
type AccountNextDaySettlementResponse struct {
	TrdeDt                    string                                                          `json:"trde_dt"`
	SetlDt                    string                                                          `json:"setl_dt"`
	SellAmtSum                string                                                          `json:"sell_amt_sum"`
	BuyAmtSum                 string                                                          `json:"buy_amt_sum"`
	AcntNxdySetlFrcsPrpsArray []AccountNextDaySettlementResponseAcntNxdySetlFrcsPrpsArrayItem `json:"acnt_nxdy_setl_frcs_prps_array"`
	ReturnCode                int                                                             `json:"return_code"`
	ReturnMsg                 string                                                          `json:"return_msg"`
}

// AccountNextDaySettlementResponseAcntNxdySetlFrcsPrpsArrayItem is a list row in AccountNextDaySettlementResponse.
type AccountNextDaySettlementResponseAcntNxdySetlFrcsPrpsArrayItem struct {
	Seq     string `json:"seq"`
	StkCd   string `json:"stk_cd"`
	LoanDt  string `json:"loan_dt"`
	Qty     string `json:"qty"`
	EnggAmt string `json:"engg_amt"`
	Cmsn    string `json:"cmsn"`
	IncmTax string `json:"incm_tax"`
	Rstx    string `json:"rstx"`
	StkNm   string `json:"stk_nm"`
	SellTp  string `json:"sell_tp"`
	Unp     string `json:"unp"`
	ExctAmt string `json:"exct_amt"`
	TrdeTax string `json:"trde_tax"`
	ResiTax string `json:"resi_tax"`
	CrdTp   string `json:"crd_tp"`
}

// GetAccountNextDaySettlement calls Kiwoom kt00008 — 계좌별익일결제예정내역요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetAccountNextDaySettlement(ctx context.Context, req *AccountNextDaySettlementRequest) (*AccountNextDaySettlementResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00008", req)
	if err != nil {
		return nil, err
	}
	var res AccountNextDaySettlementResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccountOrderExecutionStatusRequest is the request payload for kt00009 (계좌별주문체결현황요청).
type AccountOrderExecutionStatusRequest struct {
	OrdDt      string `json:"ord_dt"`
	StkBondTp  string `json:"stk_bond_tp"`
	MrktTp     string `json:"mrkt_tp"`
	SellTp     string `json:"sell_tp"`
	QryTp      string `json:"qry_tp"`
	StkCd      string `json:"stk_cd"`
	FrOrdNo    string `json:"fr_ord_no"`
	DmstStexTp string `json:"dmst_stex_tp"`
}

// AccountOrderExecutionStatusResponse is the response payload for kt00009 (계좌별주문체결현황요청).
type AccountOrderExecutionStatusResponse struct {
	SellGrntlEnggAmt     string                                                        `json:"sell_grntl_engg_amt"`
	BuyEnggAmt           string                                                        `json:"buy_engg_amt"`
	EnggAmt              string                                                        `json:"engg_amt"`
	AcntOrdCntrPrstArray []AccountOrderExecutionStatusResponseAcntOrdCntrPrstArrayItem `json:"acnt_ord_cntr_prst_array"`
	ReturnCode           int                                                           `json:"return_code"`
	ReturnMsg            string                                                        `json:"return_msg"`
}

// AccountOrderExecutionStatusResponseAcntOrdCntrPrstArrayItem is a list row in AccountOrderExecutionStatusResponse.
type AccountOrderExecutionStatusResponseAcntOrdCntrPrstArrayItem struct {
	StkBondTp  string `json:"stk_bond_tp"`
	OrdNo      string `json:"ord_no"`
	StkCd      string `json:"stk_cd"`
	TrdeTp     string `json:"trde_tp"`
	IoTpNm     string `json:"io_tp_nm"`
	OrdQty     string `json:"ord_qty"`
	OrdUv      string `json:"ord_uv"`
	CnfmQty    string `json:"cnfm_qty"`
	RsrvOppo   string `json:"rsrv_oppo"`
	CntrNo     string `json:"cntr_no"`
	AcptTp     string `json:"acpt_tp"`
	OrigOrdNo  string `json:"orig_ord_no"`
	StkNm      string `json:"stk_nm"`
	SetlTp     string `json:"setl_tp"`
	CrdDealTp  string `json:"crd_deal_tp"`
	CntrQty    string `json:"cntr_qty"`
	CntrUv     string `json:"cntr_uv"`
	CommOrdTp  string `json:"comm_ord_tp"`
	MdfyCnclTp string `json:"mdfy_cncl_tp"`
	CntrTm     string `json:"cntr_tm"`
	DmstStexTp string `json:"dmst_stex_tp"`
	CondUv     string `json:"cond_uv"`
}

// GetAccountOrderExecutionStatus calls Kiwoom kt00009 — 계좌별주문체결현황요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetAccountOrderExecutionStatus(ctx context.Context, req *AccountOrderExecutionStatusRequest) (*AccountOrderExecutionStatusResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00009", req)
	if err != nil {
		return nil, err
	}
	var res AccountOrderExecutionStatusResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// WithdrawableOrderAmountRequest is the request payload for kt00010 (주문인출가능금액요청).
type WithdrawableOrderAmountRequest struct {
	IoAmt     string `json:"io_amt"`
	StkCd     string `json:"stk_cd"`
	TrdeTp    string `json:"trde_tp"`
	TrdeQty   string `json:"trde_qty"`
	Uv        string `json:"uv"`
	ExpBuyUnp string `json:"exp_buy_unp"`
}

// WithdrawableOrderAmountResponse is the response payload for kt00010 (주문인출가능금액요청).
type WithdrawableOrderAmountResponse struct {
	ProfaN20ordAlowAmt     string `json:"profa_20ord_alow_amt"`
	ProfaN20ordAlowq       string `json:"profa_20ord_alowq"`
	ProfaN30ordAlowAmt     string `json:"profa_30ord_alow_amt"`
	ProfaN30ordAlowq       string `json:"profa_30ord_alowq"`
	ProfaN40ordAlowAmt     string `json:"profa_40ord_alow_amt"`
	ProfaN40ordAlowq       string `json:"profa_40ord_alowq"`
	ProfaN50ordAlowAmt     string `json:"profa_50ord_alow_amt"`
	ProfaN50ordAlowq       string `json:"profa_50ord_alowq"`
	ProfaN60ordAlowAmt     string `json:"profa_60ord_alow_amt"`
	ProfaN60ordAlowq       string `json:"profa_60ord_alowq"`
	ProfaRdexN60ordAlowAmt string `json:"profa_rdex_60ord_alow_amt"`
	ProfaRdexN60ordAlowq   string `json:"profa_rdex_60ord_alowq"`
	ProfaN100ordAlowAmt    string `json:"profa_100ord_alow_amt"`
	ProfaN100ordAlowq      string `json:"profa_100ord_alowq"`
	PredReuAlowa           string `json:"pred_reu_alowa"`
	TdyReuAlowa            string `json:"tdy_reu_alowa"`
	Entr                   string `json:"entr"`
	ReplAmt                string `json:"repl_amt"`
	Uncla                  string `json:"uncla"`
	OrdPosRepl             string `json:"ord_pos_repl"`
	OrdAlowa               string `json:"ord_alowa"`
	WthdAlowa              string `json:"wthd_alowa"`
	NxdyWthdAlowa          string `json:"nxdy_wthd_alowa"`
	PurAmt                 string `json:"pur_amt"`
	Cmsn                   string `json:"cmsn"`
	PurExctAmt             string `json:"pur_exct_amt"`
	D2entra                string `json:"d2entra"`
	ProfaRdexAplcTp        string `json:"profa_rdex_aplc_tp"`
	ReturnCode             int    `json:"return_code"`
	ReturnMsg              string `json:"return_msg"`
}

// GetWithdrawableOrderAmount calls Kiwoom kt00010 — 주문인출가능금액요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetWithdrawableOrderAmount(ctx context.Context, req *WithdrawableOrderAmountRequest) (*WithdrawableOrderAmountResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00010", req)
	if err != nil {
		return nil, err
	}
	var res WithdrawableOrderAmountResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// OrderableQtyByMarginRateRequest is the request payload for kt00011 (증거금율별주문가능수량조회요청).
type OrderableQtyByMarginRateRequest struct {
	StkCd string `json:"stk_cd"`
	Uv    string `json:"uv"`
}

// OrderableQtyByMarginRateResponse is the response payload for kt00011 (증거금율별주문가능수량조회요청).
type OrderableQtyByMarginRateResponse struct {
	StkProfaRt          string `json:"stk_profa_rt"`
	ProfaRt             string `json:"profa_rt"`
	AplcRt              string `json:"aplc_rt"`
	ProfaN20ordAlowAmt  string `json:"profa_20ord_alow_amt"`
	ProfaN20ordAlowq    string `json:"profa_20ord_alowq"`
	ProfaN20predReuAmt  string `json:"profa_20pred_reu_amt"`
	ProfaN20tdyReuAmt   string `json:"profa_20tdy_reu_amt"`
	ProfaN30ordAlowAmt  string `json:"profa_30ord_alow_amt"`
	ProfaN30ordAlowq    string `json:"profa_30ord_alowq"`
	ProfaN30predReuAmt  string `json:"profa_30pred_reu_amt"`
	ProfaN30tdyReuAmt   string `json:"profa_30tdy_reu_amt"`
	ProfaN40ordAlowAmt  string `json:"profa_40ord_alow_amt"`
	ProfaN40ordAlowq    string `json:"profa_40ord_alowq"`
	ProfaN40predReuAmt  string `json:"profa_40pred_reu_amt"`
	ProfaN40tdyReuAmt   string `json:"profa_40tdy_reu_amt"`
	ProfaN50ordAlowAmt  string `json:"profa_50ord_alow_amt"`
	ProfaN50ordAlowq    string `json:"profa_50ord_alowq"`
	ProfaN50predReuAmt  string `json:"profa_50pred_reu_amt"`
	ProfaN50tdyReuAmt   string `json:"profa_50tdy_reu_amt"`
	ProfaN60ordAlowAmt  string `json:"profa_60ord_alow_amt"`
	ProfaN60ordAlowq    string `json:"profa_60ord_alowq"`
	ProfaN60predReuAmt  string `json:"profa_60pred_reu_amt"`
	ProfaN60tdyReuAmt   string `json:"profa_60tdy_reu_amt"`
	ProfaN100ordAlowAmt string `json:"profa_100ord_alow_amt"`
	ProfaN100ordAlowq   string `json:"profa_100ord_alowq"`
	ProfaN100predReuAmt string `json:"profa_100pred_reu_amt"`
	ProfaN100tdyReuAmt  string `json:"profa_100tdy_reu_amt"`
	MinOrdAlowAmt       string `json:"min_ord_alow_amt"`
	MinOrdAlowq         string `json:"min_ord_alowq"`
	MinPredReuAmt       string `json:"min_pred_reu_amt"`
	MinTdyReuAmt        string `json:"min_tdy_reu_amt"`
	Entr                string `json:"entr"`
	ReplAmt             string `json:"repl_amt"`
	Uncla               string `json:"uncla"`
	OrdPosRepl          string `json:"ord_pos_repl"`
	OrdAlowa            string `json:"ord_alowa"`
	ReturnCode          int    `json:"return_code"`
	ReturnMsg           string `json:"return_msg"`
}

// GetOrderableQtyByMarginRate calls Kiwoom kt00011 — 증거금율별주문가능수량조회요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetOrderableQtyByMarginRate(ctx context.Context, req *OrderableQtyByMarginRateRequest) (*OrderableQtyByMarginRateResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00011", req)
	if err != nil {
		return nil, err
	}
	var res OrderableQtyByMarginRateResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// OrderableQtyByCreditMarginRateRequest is the request payload for kt00012 (신용보증금율별주문가능수량조회요청).
type OrderableQtyByCreditMarginRateRequest struct {
	StkCd string `json:"stk_cd"`
	Uv    string `json:"uv"`
}

// OrderableQtyByCreditMarginRateResponse is the response payload for kt00012 (신용보증금율별주문가능수량조회요청).
type OrderableQtyByCreditMarginRateResponse struct {
	StkAssrRt         string `json:"stk_assr_rt"`
	StkAssrRtNm       string `json:"stk_assr_rt_nm"`
	AssrN30ordAlowAmt string `json:"assr_30ord_alow_amt"`
	AssrN30ordAlowq   string `json:"assr_30ord_alowq"`
	AssrN30predReuAmt string `json:"assr_30pred_reu_amt"`
	AssrN30tdyReuAmt  string `json:"assr_30tdy_reu_amt"`
	AssrN40ordAlowAmt string `json:"assr_40ord_alow_amt"`
	AssrN40ordAlowq   string `json:"assr_40ord_alowq"`
	AssrN40predReuAmt string `json:"assr_40pred_reu_amt"`
	AssrN40tdyReuAmt  string `json:"assr_40tdy_reu_amt"`
	AssrN50ordAlowAmt string `json:"assr_50ord_alow_amt"`
	AssrN50ordAlowq   string `json:"assr_50ord_alowq"`
	AssrN50predReuAmt string `json:"assr_50pred_reu_amt"`
	AssrN50tdyReuAmt  string `json:"assr_50tdy_reu_amt"`
	AssrN60ordAlowAmt string `json:"assr_60ord_alow_amt"`
	AssrN60ordAlowq   string `json:"assr_60ord_alowq"`
	AssrN60predReuAmt string `json:"assr_60pred_reu_amt"`
	AssrN60tdyReuAmt  string `json:"assr_60tdy_reu_amt"`
	Entr              string `json:"entr"`
	ReplAmt           string `json:"repl_amt"`
	Uncla             string `json:"uncla"`
	OrdPosRepl        string `json:"ord_pos_repl"`
	OrdAlowa          string `json:"ord_alowa"`
	OutAlowa          string `json:"out_alowa"`
	OutPosQty         string `json:"out_pos_qty"`
	MinAmt            string `json:"min_amt"`
	MinQty            string `json:"min_qty"`
	ReturnCode        int    `json:"return_code"`
	ReturnMsg         string `json:"return_msg"`
}

// GetOrderableQtyByCreditMarginRate calls Kiwoom kt00012 — 신용보증금율별주문가능수량조회요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetOrderableQtyByCreditMarginRate(ctx context.Context, req *OrderableQtyByCreditMarginRateRequest) (*OrderableQtyByCreditMarginRateResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00012", req)
	if err != nil {
		return nil, err
	}
	var res OrderableQtyByCreditMarginRateResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// MarginDetailRequest is the request payload for kt00013 (증거금세부내역조회요청).
type MarginDetailRequest struct {
}

// MarginDetailResponse is the response payload for kt00013 (증거금세부내역조회요청).
type MarginDetailResponse struct {
	TdyReuObjtAmt           string `json:"tdy_reu_objt_amt"`
	TdyReuUseAmt            string `json:"tdy_reu_use_amt"`
	TdyReuAlowa             string `json:"tdy_reu_alowa"`
	TdyReuLmttAmt           string `json:"tdy_reu_lmtt_amt"`
	TdyReuAlowaFin          string `json:"tdy_reu_alowa_fin"`
	PredReuObjtAmt          string `json:"pred_reu_objt_amt"`
	PredReuUseAmt           string `json:"pred_reu_use_amt"`
	PredReuAlowa            string `json:"pred_reu_alowa"`
	PredReuLmttAmt          string `json:"pred_reu_lmtt_amt"`
	PredReuAlowaFin         string `json:"pred_reu_alowa_fin"`
	ChAmt                   string `json:"ch_amt"`
	ChProfa                 string `json:"ch_profa"`
	UsePosCh                string `json:"use_pos_ch"`
	ChUseLmttAmt            string `json:"ch_use_lmtt_amt"`
	UsePosChFin             string `json:"use_pos_ch_fin"`
	ReplAmtAmt              string `json:"repl_amt_amt"`
	ReplProfa               string `json:"repl_profa"`
	UsePosRepl              string `json:"use_pos_repl"`
	ReplUseLmttAmt          string `json:"repl_use_lmtt_amt"`
	UsePosReplFin           string `json:"use_pos_repl_fin"`
	CrdGrntaCh              string `json:"crd_grnta_ch"`
	CrdGrntaRepl            string `json:"crd_grnta_repl"`
	CrdGrntCh               string `json:"crd_grnt_ch"`
	CrdGrntRepl             string `json:"crd_grnt_repl"`
	Uncla                   string `json:"uncla"`
	LsGrntReuGold           string `json:"ls_grnt_reu_gold"`
	N20ordAlowAmt           string `json:"20ord_alow_amt"`
	N30ordAlowAmt           string `json:"30ord_alow_amt"`
	N40ordAlowAmt           string `json:"40ord_alow_amt"`
	N50ordAlowAmt           string `json:"50ord_alow_amt"`
	N60ordAlowAmt           string `json:"60ord_alow_amt"`
	N100ordAlowAmt          string `json:"100ord_alow_amt"`
	TdyCrdRpyaLossAmt       string `json:"tdy_crd_rpya_loss_amt"`
	PredCrdRpyaLossAmt      string `json:"pred_crd_rpya_loss_amt"`
	TdyLsRpyaLossReplProfa  string `json:"tdy_ls_rpya_loss_repl_profa"`
	PredLsRpyaLossReplProfa string `json:"pred_ls_rpya_loss_repl_profa"`
	EvltReplAmtSpgUseSkip   string `json:"evlt_repl_amt_spg_use_skip"`
	EvltReplRt              string `json:"evlt_repl_rt"`
	CrdReplProfa            string `json:"crd_repl_profa"`
	ChOrdReplProfa          string `json:"ch_ord_repl_profa"`
	CrdOrdReplProfa         string `json:"crd_ord_repl_profa"`
	CrdReplConvGold         string `json:"crd_repl_conv_gold"`
	ReplAlowa               string `json:"repl_alowa"`
	ReplAlowaN2             string `json:"repl_alowa_2"`
	ChReplLckGold           string `json:"ch_repl_lck_gold"`
	CrdReplLckGold          string `json:"crd_repl_lck_gold"`
	ChOrdAlowRepla          string `json:"ch_ord_alow_repla"`
	CrdOrdAlowRepla         string `json:"crd_ord_alow_repla"`
	D2vexctEntr             string `json:"d2vexct_entr"`
	D2chOrdAlowAmt          string `json:"d2ch_ord_alow_amt"`
	ReturnCode              int    `json:"return_code"`
	ReturnMsg               string `json:"return_msg"`
}

// GetMarginDetail calls Kiwoom kt00013 — 증거금세부내역조회요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetMarginDetail(ctx context.Context, req *MarginDetailRequest) (*MarginDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00013", req)
	if err != nil {
		return nil, err
	}
	var res MarginDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ConsolidatedTradeHistoryRequest is the request payload for kt00015 (위탁종합거래내역요청).
type ConsolidatedTradeHistoryRequest struct {
	StrtDt       string `json:"strt_dt"`
	EndDt        string `json:"end_dt"`
	Tp           string `json:"tp"`
	StkCd        string `json:"stk_cd"`
	CrncCd       string `json:"crnc_cd"`
	GdsTp        string `json:"gds_tp"`
	FrgnStexCode string `json:"frgn_stex_code"`
	DmstStexTp   string `json:"dmst_stex_tp"`
	QrySortTp    string `json:"qry_sort_tp"`
}

// ConsolidatedTradeHistoryResponse is the response payload for kt00015 (위탁종합거래내역요청).
type ConsolidatedTradeHistoryResponse struct {
	TrstOvrlTrdePrpsArray []ConsolidatedTradeHistoryResponseTrstOvrlTrdePrpsArrayItem `json:"trst_ovrl_trde_prps_array"`
	ReturnCode            int                                                         `json:"return_code"`
	ReturnMsg             string                                                      `json:"return_msg"`
}

// ConsolidatedTradeHistoryResponseTrstOvrlTrdePrpsArrayItem is a list row in ConsolidatedTradeHistoryResponse.
type ConsolidatedTradeHistoryResponseTrstOvrlTrdePrpsArrayItem struct {
	TrdeDt        string `json:"trde_dt"`
	TrdeNo        string `json:"trde_no"`
	RmrkNm        string `json:"rmrk_nm"`
	CrdDealTpNm   string `json:"crd_deal_tp_nm"`
	ExctAmt       string `json:"exct_amt"`
	LoanAmtRpya   string `json:"loan_amt_rpya"`
	FcTrdeAmt     string `json:"fc_trde_amt"`
	FcExctAmt     string `json:"fc_exct_amt"`
	EntraRemn     string `json:"entra_remn"`
	CrncCd        string `json:"crnc_cd"`
	TrdeOcrTp     string `json:"trde_ocr_tp"`
	TrdeKindNm    string `json:"trde_kind_nm"`
	StkNm         string `json:"stk_nm"`
	TrdeAmt       string `json:"trde_amt"`
	TrdeAgriTax   string `json:"trde_agri_tax"`
	RpyDiffa      string `json:"rpy_diffa"`
	FcTrdeTax     string `json:"fc_trde_tax"`
	DlySum        string `json:"dly_sum"`
	FcEntra       string `json:"fc_entra"`
	MdiaTpNm      string `json:"mdia_tp_nm"`
	IoTp          string `json:"io_tp"`
	IoTpNm        string `json:"io_tp_nm"`
	OrigDealNo    string `json:"orig_deal_no"`
	StkCd         string `json:"stk_cd"`
	TrdeQtyJwaCnt string `json:"trde_qty_jwa_cnt"`
	Cmsn          string `json:"cmsn"`
	IntLsUsfe     string `json:"int_ls_usfe"`
	FcCmsn        string `json:"fc_cmsn"`
	FcDlySum      string `json:"fc_dly_sum"`
	VlblNowrm     string `json:"vlbl_nowrm"`
	ProcTm        string `json:"proc_tm"`
	IsinCd        string `json:"isin_cd"`
	StexCd        string `json:"stex_cd"`
	StexNm        string `json:"stex_nm"`
	TrdeUnit      string `json:"trde_unit"`
	IncmResiTax   string `json:"incm_resi_tax"`
	LoanDt        string `json:"loan_dt"`
	UnclOcr       string `json:"uncl_ocr"`
	RpymSum       string `json:"rpym_sum"`
	CntrDt        string `json:"cntr_dt"`
	RcpyNo        string `json:"rcpy_no"`
	Prcsr         string `json:"prcsr"`
	ProcBrch      string `json:"proc_brch"`
	TrdeStle      string `json:"trde_stle"`
	TxonBasePric  string `json:"txon_base_pric"`
	TaxSumCmsn    string `json:"tax_sum_cmsn"`
	FrgnPayTxam   string `json:"frgn_pay_txam"`
	FcUnclOcr     string `json:"fc_uncl_ocr"`
	RpymSumFr     string `json:"rpym_sum_fr"`
	Rcpmnyer      string `json:"rcpmnyer"`
	TrdePrtcTp    string `json:"trde_prtc_tp"`
}

// GetConsolidatedTradeHistory calls Kiwoom kt00015 — 위탁종합거래내역요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetConsolidatedTradeHistory(ctx context.Context, req *ConsolidatedTradeHistoryRequest) (*ConsolidatedTradeHistoryResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00015", req)
	if err != nil {
		return nil, err
	}
	var res ConsolidatedTradeHistoryResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyAccountReturnDetailRequest is the request payload for kt00016 (일별계좌수익률상세현황요청).
type DailyAccountReturnDetailRequest struct {
	FrDt string `json:"fr_dt"`
	ToDt string `json:"to_dt"`
}

// DailyAccountReturnDetailResponse is the response payload for kt00016 (일별계좌수익률상세현황요청).
type DailyAccountReturnDetailResponse struct {
	MangEmpno        string `json:"mang_empno"`
	MngrNm           string `json:"mngr_nm"`
	DeptNm           string `json:"dept_nm"`
	EntrFr           string `json:"entr_fr"`
	EntrTo           string `json:"entr_to"`
	ScrtEvltAmtFr    string `json:"scrt_evlt_amt_fr"`
	ScrtEvltAmtTo    string `json:"scrt_evlt_amt_to"`
	LsGrntFr         string `json:"ls_grnt_fr"`
	LsGrntTo         string `json:"ls_grnt_to"`
	CrdLoanFr        string `json:"crd_loan_fr"`
	CrdLoanTo        string `json:"crd_loan_to"`
	ChUnclaFr        string `json:"ch_uncla_fr"`
	ChUnclaTo        string `json:"ch_uncla_to"`
	KrwAsgnaFr       string `json:"krw_asgna_fr"`
	KrwAsgnaTo       string `json:"krw_asgna_to"`
	LsEvltaFr        string `json:"ls_evlta_fr"`
	LsEvltaTo        string `json:"ls_evlta_to"`
	RghtEvltaFr      string `json:"rght_evlta_fr"`
	RghtEvltaTo      string `json:"rght_evlta_to"`
	LoanAmtFr        string `json:"loan_amt_fr"`
	LoanAmtTo        string `json:"loan_amt_to"`
	EtcLoanaFr       string `json:"etc_loana_fr"`
	EtcLoanaTo       string `json:"etc_loana_to"`
	CrdIntNpayGoldFr string `json:"crd_int_npay_gold_fr"`
	CrdIntNpayGoldTo string `json:"crd_int_npay_gold_to"`
	CrdIntFr         string `json:"crd_int_fr"`
	CrdIntTo         string `json:"crd_int_to"`
	TotAmtFr         string `json:"tot_amt_fr"`
	TotAmtTo         string `json:"tot_amt_to"`
	InvtBsamt        string `json:"invt_bsamt"`
	EvltvPrft        string `json:"evltv_prft"`
	PrftRt           string `json:"prft_rt"`
	TernRt           string `json:"tern_rt"`
	TerminTotTrns    string `json:"termin_tot_trns"`
	TerminTotPymn    string `json:"termin_tot_pymn"`
	TerminTotInq     string `json:"termin_tot_inq"`
	TerminTotOutq    string `json:"termin_tot_outq"`
	FutrReplSella    string `json:"futr_repl_sella"`
	TrstReplSella    string `json:"trst_repl_sella"`
	ReturnCode       int    `json:"return_code"`
	ReturnMsg        string `json:"return_msg"`
}

// GetDailyAccountReturnDetail calls Kiwoom kt00016 — 일별계좌수익률상세현황요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetDailyAccountReturnDetail(ctx context.Context, req *DailyAccountReturnDetailRequest) (*DailyAccountReturnDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00016", req)
	if err != nil {
		return nil, err
	}
	var res DailyAccountReturnDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccountTodayStatusRequest is the request payload for kt00017 (계좌별당일현황요청).
type AccountTodayStatusRequest struct {
}

// AccountTodayStatusResponse is the response payload for kt00017 (계좌별당일현황요청).
type AccountTodayStatusResponse struct {
	D2Entra                   string `json:"d2_entra"`
	CrdIntNpayGold            string `json:"crd_int_npay_gold"`
	EtcLoana                  string `json:"etc_loana"`
	GnrlStkEvltAmtD2          string `json:"gnrl_stk_evlt_amt_d2"`
	DpstGrntUseAmtD2          string `json:"dpst_grnt_use_amt_d2"`
	CrdStkEvltAmtD2           string `json:"crd_stk_evlt_amt_d2"`
	CrdLoanD2                 string `json:"crd_loan_d2"`
	CrdLoanEvltaD2            string `json:"crd_loan_evlta_d2"`
	CrdLsGrntD2               string `json:"crd_ls_grnt_d2"`
	CrdLsEvltaD2              string `json:"crd_ls_evlta_d2"`
	InaAmt                    string `json:"ina_amt"`
	Outa                      string `json:"outa"`
	InqAmt                    string `json:"inq_amt"`
	OutqAmt                   string `json:"outq_amt"`
	SellAmt                   string `json:"sell_amt"`
	BuyAmt                    string `json:"buy_amt"`
	Cmsn                      string `json:"cmsn"`
	Tax                       string `json:"tax"`
	StkPurCptalLoanAmt        string `json:"stk_pur_cptal_loan_amt"`
	RpEvltAmt                 string `json:"rp_evlt_amt"`
	BdEvltAmt                 string `json:"bd_evlt_amt"`
	ElsevltAmt                string `json:"elsevlt_amt"`
	CrdIntAmt                 string `json:"crd_int_amt"`
	SelPricaGrntLoanIntAmtAmt string `json:"sel_prica_grnt_loan_int_amt_amt"`
	DvidaAmt                  string `json:"dvida_amt"`
	ReturnCode                int    `json:"return_code"`
	ReturnMsg                 string `json:"return_msg"`
}

// GetAccountTodayStatus calls Kiwoom kt00017 — 계좌별당일현황요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetAccountTodayStatus(ctx context.Context, req *AccountTodayStatusRequest) (*AccountTodayStatusResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "kt00017", req)
	if err != nil {
		return nil, err
	}
	var res AccountTodayStatusResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockRealtimeViewRankRequest is the request payload for usa01980 (미국주식 실시간 종목 조회 순위).
type USStockRealtimeViewRankRequest struct {
	SvcType string `json:"svc_type"`
}

// USStockRealtimeViewRankResponse is the response payload for usa01980 (미국주식 실시간 종목 조회 순위).
type USStockRealtimeViewRankResponse struct {
	BaseDate   string                                          `json:"base_date"`
	BaseTime   string                                          `json:"base_time"`
	ResultList []USStockRealtimeViewRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                             `json:"return_code"`
	ReturnMsg  string                                          `json:"return_msg"`
}

// USStockRealtimeViewRankResponseResultListItem is a list row in USStockRealtimeViewRankResponse.
type USStockRealtimeViewRankResponseResultListItem struct {
	Rank            string `json:"rank"`
	StkCd           string `json:"stk_cd"`
	StkNm           string `json:"stk_nm"`
	Sign            string `json:"sign"`
	ChgVal          string `json:"chg_val"`
	CurrPric        string `json:"curr_pric"`
	SignForGjga     string `json:"sign_for_gjga"`
	DiffRateForGjga string `json:"diff_rate_for_gjga"`
	SignForPrev     string `json:"sign_for_prev"`
	DiffRateForPrev string `json:"diff_rate_for_prev"`
	StexTp          string `json:"stex_tp"`
}

// GetUSStockRealtimeViewRank calls Kiwoom usa01980 — 미국주식 실시간 종목 조회 순위.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockRealtimeViewRank(ctx context.Context, req *USStockRealtimeViewRankRequest) (*USStockRealtimeViewRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa01980", req)
	if err != nil {
		return nil, err
	}
	var res USStockRealtimeViewRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockWatchlistRegistrationTopRequest is the request payload for usa01990 (미국주식 관심종목 등록 상위).
type USStockWatchlistRegistrationTopRequest struct {
	DtUnitTp string `json:"dt_unit_tp"`
	StkTp    string `json:"stk_tp"`
}

// USStockWatchlistRegistrationTopResponse is the response payload for usa01990 (미국주식 관심종목 등록 상위).
type USStockWatchlistRegistrationTopResponse struct {
	ResultList []USStockWatchlistRegistrationTopResponseResultListItem `json:"result_list"`
	ReturnCode int                                                     `json:"return_code"`
	ReturnMsg  string                                                  `json:"return_msg"`
}

// USStockWatchlistRegistrationTopResponseResultListItem is a list row in USStockWatchlistRegistrationTopResponse.
type USStockWatchlistRegistrationTopResponseResultListItem struct {
	Rank       string `json:"rank"`
	RankFluSig string `json:"rank_flu_sig"`
	RankFlu    string `json:"rank_flu"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
}

// GetUSStockWatchlistRegistrationTop calls Kiwoom usa01990 — 미국주식 관심종목 등록 상위.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockWatchlistRegistrationTop(ctx context.Context, req *USStockWatchlistRegistrationTopRequest) (*USStockWatchlistRegistrationTopResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa01990", req)
	if err != nil {
		return nil, err
	}
	var res USStockWatchlistRegistrationTopResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockTickChartRequest is the request payload for usa06010 (미국주식 틱 차트).
type USStockTickChartRequest struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	TicScope   string `json:"tic_scope"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// USStockTickChartResponse is the response payload for usa06010 (미국주식 틱 차트).
type USStockTickChartResponse struct {
	ResultList []USStockTickChartResponseResultListItem `json:"result_list"`
	ReturnCode int                                      `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
}

// USStockTickChartResponseResultListItem is a list row in USStockTickChartResponse.
type USStockTickChartResponseResultListItem struct {
	CurPrc     string `json:"cur_prc"`
	TrdeQty    string `json:"trde_qty"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
	CntrTm     string `json:"cntr_tm"`
	BusDt      string `json:"bus_dt"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	UpdRt      string `json:"upd_rt"`
}

// GetUSStockTickChart calls Kiwoom usa06010 — 미국주식 틱 차트.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockTickChart(ctx context.Context, req *USStockTickChartRequest) (*USStockTickChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/chart", "usa06010", req)
	if err != nil {
		return nil, err
	}
	var res USStockTickChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockMinuteChartRequest is the request payload for usa06011 (미국주식 분 차트).
type USStockMinuteChartRequest struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StrtDt     string `json:"strt_dt"`
	TicScope   string `json:"tic_scope"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// USStockMinuteChartResponse is the response payload for usa06011 (미국주식 분 차트).
type USStockMinuteChartResponse struct {
	ResultList []USStockMinuteChartResponseResultListItem `json:"result_list"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// USStockMinuteChartResponseResultListItem is a list row in USStockMinuteChartResponse.
type USStockMinuteChartResponseResultListItem struct {
	CurPrc     string `json:"cur_prc"`
	TrdeQty    string `json:"trde_qty"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
	CntrTm     string `json:"cntr_tm"`
	BusDt      string `json:"bus_dt"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	UpdRt      string `json:"upd_rt"`
}

// GetUSStockMinuteChart calls Kiwoom usa06011 — 미국주식 분 차트.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockMinuteChart(ctx context.Context, req *USStockMinuteChartRequest) (*USStockMinuteChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/chart", "usa06011", req)
	if err != nil {
		return nil, err
	}
	var res USStockMinuteChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockDailyChartRequest is the request payload for usa06012 (미국주식 일 차트).
type USStockDailyChartRequest struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StrtDt     string `json:"strt_dt"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// USStockDailyChartResponse is the response payload for usa06012 (미국주식 일 차트).
type USStockDailyChartResponse struct {
	ResultList []USStockDailyChartResponseResultListItem `json:"result_list"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// USStockDailyChartResponseResultListItem is a list row in USStockDailyChartResponse.
type USStockDailyChartResponseResultListItem struct {
	CurPrc       string `json:"cur_prc"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	AccTrdeQty   string `json:"acc_trde_qty"`
	AccTrdePrica string `json:"acc_trde_prica"`
	OpenPric     string `json:"open_pric"`
	HighPric     string `json:"high_pric"`
	LowPric      string `json:"low_pric"`
	Dt           string `json:"dt"`
	UpdStkpcTp   string `json:"upd_stkpc_tp"`
	UpdRt        string `json:"upd_rt"`
}

// GetUSStockDailyChart calls Kiwoom usa06012 — 미국주식 일 차트.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockDailyChart(ctx context.Context, req *USStockDailyChartRequest) (*USStockDailyChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/chart", "usa06012", req)
	if err != nil {
		return nil, err
	}
	var res USStockDailyChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockWeeklyChartRequest is the request payload for usa06013 (미국주식 주 차트).
type USStockWeeklyChartRequest struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StrtDt     string `json:"strt_dt"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// USStockWeeklyChartResponse is the response payload for usa06013 (미국주식 주 차트).
type USStockWeeklyChartResponse struct {
	ResultList []USStockWeeklyChartResponseResultListItem `json:"result_list"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// USStockWeeklyChartResponseResultListItem is a list row in USStockWeeklyChartResponse.
type USStockWeeklyChartResponseResultListItem struct {
	CurPrc       string `json:"cur_prc"`
	AccTrdeQty   string `json:"acc_trde_qty"`
	AccTrdePrica string `json:"acc_trde_prica"`
	OpenPric     string `json:"open_pric"`
	HighPric     string `json:"high_pric"`
	LowPric      string `json:"low_pric"`
	Dt           string `json:"dt"`
	UpdStkpcTp   string `json:"upd_stkpc_tp"`
	UpdRt        string `json:"upd_rt"`
}

// GetUSStockWeeklyChart calls Kiwoom usa06013 — 미국주식 주 차트.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockWeeklyChart(ctx context.Context, req *USStockWeeklyChartRequest) (*USStockWeeklyChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/chart", "usa06013", req)
	if err != nil {
		return nil, err
	}
	var res USStockWeeklyChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockMonthlyChartRequest is the request payload for usa06014 (미국주식 월 차트).
type USStockMonthlyChartRequest struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StrtDt     string `json:"strt_dt"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// USStockMonthlyChartResponse is the response payload for usa06014 (미국주식 월 차트).
type USStockMonthlyChartResponse struct {
	ResultList []USStockMonthlyChartResponseResultListItem `json:"result_list"`
	ReturnCode int                                         `json:"return_code"`
	ReturnMsg  string                                      `json:"return_msg"`
}

// USStockMonthlyChartResponseResultListItem is a list row in USStockMonthlyChartResponse.
type USStockMonthlyChartResponseResultListItem struct {
	CurPrc       string `json:"cur_prc"`
	AccTrdeQty   string `json:"acc_trde_qty"`
	AccTrdePrica string `json:"acc_trde_prica"`
	OpenPric     string `json:"open_pric"`
	HighPric     string `json:"high_pric"`
	LowPric      string `json:"low_pric"`
	Dt           string `json:"dt"`
	UpdStkpcTp   string `json:"upd_stkpc_tp"`
	UpdRt        string `json:"upd_rt"`
}

// GetUSStockMonthlyChart calls Kiwoom usa06014 — 미국주식 월 차트.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockMonthlyChart(ctx context.Context, req *USStockMonthlyChartRequest) (*USStockMonthlyChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/chart", "usa06014", req)
	if err != nil {
		return nil, err
	}
	var res USStockMonthlyChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockYearlyChartRequest is the request payload for usa06015 (미국주식 년 차트).
type USStockYearlyChartRequest struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StrtDt     string `json:"strt_dt"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// USStockYearlyChartResponse is the response payload for usa06015 (미국주식 년 차트).
type USStockYearlyChartResponse struct {
	ResultList []USStockYearlyChartResponseResultListItem `json:"result_list"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// USStockYearlyChartResponseResultListItem is a list row in USStockYearlyChartResponse.
type USStockYearlyChartResponseResultListItem struct {
	CurPrc       string `json:"cur_prc"`
	AccTrdeQty   string `json:"acc_trde_qty"`
	AccTrdePrica string `json:"acc_trde_prica"`
	OpenPric     string `json:"open_pric"`
	HighPric     string `json:"high_pric"`
	LowPric      string `json:"low_pric"`
	Dt           string `json:"dt"`
	UpdStkpcTp   string `json:"upd_stkpc_tp"`
	UpdRt        string `json:"upd_rt"`
}

// GetUSStockYearlyChart calls Kiwoom usa06015 — 미국주식 년 차트.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockYearlyChart(ctx context.Context, req *USStockYearlyChartRequest) (*USStockYearlyChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/chart", "usa06015", req)
	if err != nil {
		return nil, err
	}
	var res USStockYearlyChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockQuarterlyChartRequest is the request payload for usa06016 (미국주식 분기 차트).
type USStockQuarterlyChartRequest struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StrtDt     string `json:"strt_dt"`
	UpdStkpcTp string `json:"upd_stkpc_tp"`
	ExrtApplTp string `json:"exrt_appl_tp"`
}

// USStockQuarterlyChartResponse is the response payload for usa06016 (미국주식 분기 차트).
type USStockQuarterlyChartResponse struct {
	ResultList []USStockQuarterlyChartResponseResultListItem `json:"result_list"`
	ReturnCode int                                           `json:"return_code"`
	ReturnMsg  string                                        `json:"return_msg"`
}

// USStockQuarterlyChartResponseResultListItem is a list row in USStockQuarterlyChartResponse.
type USStockQuarterlyChartResponseResultListItem struct {
	CurPrc       string `json:"cur_prc"`
	AccTrdeQty   string `json:"acc_trde_qty"`
	AccTrdePrica string `json:"acc_trde_prica"`
	OpenPric     string `json:"open_pric"`
	HighPric     string `json:"high_pric"`
	LowPric      string `json:"low_pric"`
	Dt           string `json:"dt"`
	UpdStkpcTp   string `json:"upd_stkpc_tp"`
	UpdRt        string `json:"upd_rt"`
}

// GetUSStockQuarterlyChart calls Kiwoom usa06016 — 미국주식 분기 차트.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockQuarterlyChart(ctx context.Context, req *USStockQuarterlyChartRequest) (*USStockQuarterlyChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/chart", "usa06016", req)
	if err != nil {
		return nil, err
	}
	var res USStockQuarterlyChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockExchangeTypesRequest is the request payload for usa10098 (미국주식 거래소구분 조회).
type USStockExchangeTypesRequest struct {
	StkCd string `json:"stk_cd"`
}

// USStockExchangeTypesResponse is the response payload for usa10098 (미국주식 거래소구분 조회).
type USStockExchangeTypesResponse struct {
	List       []USStockExchangeTypesResponseListItem `json:"list"`
	ReturnCode int                                    `json:"return_code"`
	ReturnMsg  string                                 `json:"return_msg"`
}

// USStockExchangeTypesResponseListItem is a list row in USStockExchangeTypesResponse.
type USStockExchangeTypesResponseListItem struct {
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
	StkNm  string `json:"stk_nm"`
	StkEnm string `json:"stk_enm"`
	Mkgb   string `json:"mkgb"`
	Upgb   string `json:"upgb"`
	IsEtf  string `json:"isEtf"`
}

// GetUSStockExchangeTypes calls Kiwoom usa10098 — 미국주식 거래소구분 조회.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockExchangeTypes(ctx context.Context, req *USStockExchangeTypesRequest) (*USStockExchangeTypesResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa10098", req)
	if err != nil {
		return nil, err
	}
	var res USStockExchangeTypesResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
