// Code generated by cmd/genapis; DO NOT EDIT.

package kioom

import (
	"context"
	"net/http"
)

// USWatchlistPriceSurgeRequest is the request payload for usa20932 (미국주식 가격급등락(관심종목)).
type USWatchlistPriceSurgeRequest struct {
	StexTp       string `json:"stex_tp"`
	FluTp        string `json:"flu_tp"`
	TmTp         string `json:"tm_tp"`
	Tm           string `json:"tm"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USWatchlistPriceSurgeRequestStkCdItem is a list row in USWatchlistPriceSurgeRequest.
type USWatchlistPriceSurgeRequestStkCdItem struct {
}

// USWatchlistPriceSurgeResponse is the response payload for usa20932 (미국주식 가격급등락(관심종목)).
type USWatchlistPriceSurgeResponse struct {
	ResultList []USWatchlistPriceSurgeResponseResultListItem `json:"result_list"`
	ReturnCode int                                           `json:"return_code"`
	ReturnMsg  string                                        `json:"return_msg"`
}

// USWatchlistPriceSurgeResponseResultListItem is a list row in USWatchlistPriceSurgeResponse.
type USWatchlistPriceSurgeResponseResultListItem struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	BasePric   string `json:"base_pric"`
	CurPrc     string `json:"cur_prc"`
	BasePre    string `json:"base_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SdninRt    string `json:"sdnin_rt"`
}

// GetUSWatchlistPriceSurge calls Kiwoom usa20932 — 미국주식 가격급등락(관심종목).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSWatchlistPriceSurge(ctx context.Context, req *USWatchlistPriceSurgeRequest) (*USWatchlistPriceSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20932", req)
	if err != nil {
		return nil, err
	}
	var res USWatchlistPriceSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockCumulativeChangeRateRankRequest is the request payload for usa20940 (미국주식 누적 등락률 상위(주식/업종)).
type USStockCumulativeChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	SortTp       string `json:"sort_tp"`
	PricCnd1     string `json:"pric_cnd1"`
	PricCnd2     string `json:"pric_cnd2"`
	BaseDt       string `json:"base_dt"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockCumulativeChangeRateRankResponse is the response payload for usa20940 (미국주식 누적 등락률 상위(주식/업종)).
type USStockCumulativeChangeRateRankResponse struct {
	ResultList []USStockCumulativeChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                     `json:"return_code"`
	ReturnMsg  string                                                  `json:"return_msg"`
}

// USStockCumulativeChangeRateRankResponseResultListItem is a list row in USStockCumulativeChangeRateRankResponse.
type USStockCumulativeChangeRateRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	HgstPric   string `json:"hgst_pric"`
	StkHighDt  string `json:"stk_high_dt"`
	LwstPric   string `json:"lwst_pric"`
	StkLowDt   string `json:"stk_low_dt"`
	AccFluRt   string `json:"acc_flu_rt"`
	AccFluAmt  string `json:"acc_flu_amt"`
}

// GetUSStockCumulativeChangeRateRank calls Kiwoom usa20940 — 미국주식 누적 등락률 상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockCumulativeChangeRateRank(ctx context.Context, req *USStockCumulativeChangeRateRankRequest) (*USStockCumulativeChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20940", req)
	if err != nil {
		return nil, err
	}
	var res USStockCumulativeChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFCumulativeChangeRateRankRequest is the request payload for usa20941 (미국주식 누적 등락률 상위(ETF)).
type USETFCumulativeChangeRateRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	SortTp       string `json:"sort_tp"`
	PricCnd1     string `json:"pric_cnd1"`
	PricCnd2     string `json:"pric_cnd2"`
	BaseDt       string `json:"base_dt"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFCumulativeChangeRateRankResponse is the response payload for usa20941 (미국주식 누적 등락률 상위(ETF)).
type USETFCumulativeChangeRateRankResponse struct {
	ResultList []USETFCumulativeChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                   `json:"return_code"`
	ReturnMsg  string                                                `json:"return_msg"`
}

// USETFCumulativeChangeRateRankResponseResultListItem is a list row in USETFCumulativeChangeRateRankResponse.
type USETFCumulativeChangeRateRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	HgstPric   string `json:"hgst_pric"`
	StkHighDt  string `json:"stk_high_dt"`
	LwstPric   string `json:"lwst_pric"`
	StkLowDt   string `json:"stk_low_dt"`
	AccFluRt   string `json:"acc_flu_rt"`
	AccFluAmt  string `json:"acc_flu_amt"`
}

// GetUSETFCumulativeChangeRateRank calls Kiwoom usa20941 — 미국주식 누적 등락률 상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFCumulativeChangeRateRank(ctx context.Context, req *USETFCumulativeChangeRateRankRequest) (*USETFCumulativeChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20941", req)
	if err != nil {
		return nil, err
	}
	var res USETFCumulativeChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockPreviousDayTradingRankRequest is the request payload for usa20960 (미국주식 전일 거래상위(주식/업종)).
type USStockPreviousDayTradingRankRequest struct {
	StexTp string `json:"stex_tp"`
	IndsCd string `json:"inds_cd"`
	StkTp  string `json:"stk_tp"`
	QryTp  string `json:"qry_tp"`
}

// USStockPreviousDayTradingRankResponse is the response payload for usa20960 (미국주식 전일 거래상위(주식/업종)).
type USStockPreviousDayTradingRankResponse struct {
	ResultList []USStockPreviousDayTradingRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                   `json:"return_code"`
	ReturnMsg  string                                                `json:"return_msg"`
}

// USStockPreviousDayTradingRankResponseResultListItem is a list row in USStockPreviousDayTradingRankResponse.
type USStockPreviousDayTradingRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	PredRt     string `json:"pred_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
}

// GetUSStockPreviousDayTradingRank calls Kiwoom usa20960 — 미국주식 전일 거래상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockPreviousDayTradingRank(ctx context.Context, req *USStockPreviousDayTradingRankRequest) (*USStockPreviousDayTradingRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20960", req)
	if err != nil {
		return nil, err
	}
	var res USStockPreviousDayTradingRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFPreviousDayTradingRankRequest is the request payload for usa20961 (미국주식 전일 거래상위(ETF)).
type USETFPreviousDayTradingRankRequest struct {
	StexTp  string `json:"stex_tp"`
	EtfCat1 string `json:"etf_cat1"`
	EtfCat2 string `json:"etf_cat2"`
	QryTp   string `json:"qry_tp"`
}

// USETFPreviousDayTradingRankResponse is the response payload for usa20961 (미국주식 전일 거래상위(ETF)).
type USETFPreviousDayTradingRankResponse struct {
	ResultList []USETFPreviousDayTradingRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                 `json:"return_code"`
	ReturnMsg  string                                              `json:"return_msg"`
}

// USETFPreviousDayTradingRankResponseResultListItem is a list row in USETFPreviousDayTradingRankResponse.
type USETFPreviousDayTradingRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	PredRt     string `json:"pred_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
}

// GetUSETFPreviousDayTradingRank calls Kiwoom usa20961 — 미국주식 전일 거래상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFPreviousDayTradingRank(ctx context.Context, req *USETFPreviousDayTradingRankRequest) (*USETFPreviousDayTradingRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa20961", req)
	if err != nil {
		return nil, err
	}
	var res USETFPreviousDayTradingRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockNearHighLowRequest is the request payload for usa20970 (미국주식 고가/저가 접근(주식/업종)).
type USStockNearHighLowRequest struct {
	StexTp        string `json:"stex_tp"`
	IndsCd        string `json:"inds_cd"`
	StkTp         string `json:"stk_tp"`
	HighLowTp     string `json:"high_low_tp"`
	AlaccRt       string `json:"alacc_rt"`
	StkCnd        string `json:"stk_cnd"`
	PricCndSt     string `json:"pric_cnd_st"`
	PricCndEd     string `json:"pric_cnd_ed"`
	TrdePricCndSt string `json:"trde_pric_cnd_st"`
	TrdeQtyCndFr  string `json:"trde_qty_cnd_fr"`
}

// USStockNearHighLowResponse is the response payload for usa20970 (미국주식 고가/저가 접근(주식/업종)).
type USStockNearHighLowResponse struct {
	ResultList []USStockNearHighLowResponseResultListItem `json:"result_list"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// USStockNearHighLowResponseResultListItem is a list row in USStockNearHighLowResponse.
type USStockNearHighLowResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
}

// GetUSStockNearHighLow calls Kiwoom usa20970 — 미국주식 고가/저가 접근(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockNearHighLow(ctx context.Context, req *USStockNearHighLowRequest) (*USStockNearHighLowResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20970", req)
	if err != nil {
		return nil, err
	}
	var res USStockNearHighLowResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFNearHighLowRequest is the request payload for usa20971 (미국주식 고가/저가 접근(ETF)).
type USETFNearHighLowRequest struct {
	StexTp        string `json:"stex_tp"`
	EtfCat1       string `json:"etf_cat1"`
	EtfCat2       string `json:"etf_cat2"`
	HighLowTp     string `json:"high_low_tp"`
	AlaccRt       string `json:"alacc_rt"`
	StkCnd        string `json:"stk_cnd"`
	PricCndSt     string `json:"pric_cnd_st"`
	PricCndEd     string `json:"pric_cnd_ed"`
	TrdePricCndSt string `json:"trde_pric_cnd_st"`
	TrdeQtyCndFr  string `json:"trde_qty_cnd_fr"`
}

// USETFNearHighLowResponse is the response payload for usa20971 (미국주식 고가/저가 접근(ETF)).
type USETFNearHighLowResponse struct {
	ResultList []USETFNearHighLowResponseResultListItem `json:"result_list"`
	ReturnCode int                                      `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
}

// USETFNearHighLowResponseResultListItem is a list row in USETFNearHighLowResponse.
type USETFNearHighLowResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
}

// GetUSETFNearHighLow calls Kiwoom usa20971 — 미국주식 고가/저가 접근(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFNearHighLow(ctx context.Context, req *USETFNearHighLowRequest) (*USETFNearHighLowResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20971", req)
	if err != nil {
		return nil, err
	}
	var res USETFNearHighLowResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USWatchlistNearHighLowRequest is the request payload for usa20972 (미국주식 고가/저가 접근(관심종목)).
type USWatchlistNearHighLowRequest struct {
	StexTp        string `json:"stex_tp"`
	HighLowTp     string `json:"high_low_tp"`
	AlaccRt       string `json:"alacc_rt"`
	StkCnd        string `json:"stk_cnd"`
	PricCndSt     string `json:"pric_cnd_st"`
	PricCndEd     string `json:"pric_cnd_ed"`
	TrdePricCndSt string `json:"trde_pric_cnd_st"`
	TrdeQtyCndFr  string `json:"trde_qty_cnd_fr"`
}

// USWatchlistNearHighLowRequestStkCdItem is a list row in USWatchlistNearHighLowRequest.
type USWatchlistNearHighLowRequestStkCdItem struct {
}

// USWatchlistNearHighLowResponse is the response payload for usa20972 (미국주식 고가/저가 접근(관심종목)).
type USWatchlistNearHighLowResponse struct {
	ResultList []USWatchlistNearHighLowResponseResultListItem `json:"result_list"`
	ReturnCode int                                            `json:"return_code"`
	ReturnMsg  string                                         `json:"return_msg"`
}

// USWatchlistNearHighLowResponseResultListItem is a list row in USWatchlistNearHighLowResponse.
type USWatchlistNearHighLowResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	Tp         string `json:"tp"`
	FluRt      string `json:"flu_rt"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
}

// GetUSWatchlistNearHighLow calls Kiwoom usa20972 — 미국주식 고가/저가 접근(관심종목).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSWatchlistNearHighLow(ctx context.Context, req *USWatchlistNearHighLowRequest) (*USWatchlistNearHighLowResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa20972", req)
	if err != nil {
		return nil, err
	}
	var res USWatchlistNearHighLowResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockDailyAccountReturnRequest is the request payload for usa21670 (미국주식 일별계좌수익률현황).
type USStockDailyAccountReturnRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// USStockDailyAccountReturnResponse is the response payload for usa21670 (미국주식 일별계좌수익률현황).
type USStockDailyAccountReturnResponse struct {
	ResultList []USStockDailyAccountReturnResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USStockDailyAccountReturnResponseResultListItem is a list row in USStockDailyAccountReturnResponse.
type USStockDailyAccountReturnResponseResultListItem struct {
	BaseDt         string `json:"base_dt"`
	StkEvlta       string `json:"stk_evlta"`
	PlAmt          string `json:"pl_amt"`
	DvidAmt        string `json:"dvid_amt"`
	CmsnTax        string `json:"cmsn_tax"`
	AcumPlAmt      string `json:"acum_pl_amt"`
	PymnAmt        string `json:"pymn_amt"`
	Dast           string `json:"dast"`
	DlyAmt         string `json:"dly_amt"`
	SellAmt        string `json:"sell_amt"`
	BuyAmt         string `json:"buy_amt"`
	PrftRt         string `json:"prft_rt"`
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	FrgnStkInqAmt  string `json:"frgn_stk_inq_amt"`
	InaAmt         string `json:"ina_amt"`
	Exrt           string `json:"exrt"`
}

// GetUSStockDailyAccountReturn calls Kiwoom usa21670 — 미국주식 일별계좌수익률현황.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockDailyAccountReturn(ctx context.Context, req *USStockDailyAccountReturnRequest) (*USStockDailyAccountReturnResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/acnt", "usa21670", req)
	if err != nil {
		return nil, err
	}
	var res USStockDailyAccountReturnResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockMonthlyAccountReturnRequest is the request payload for usa21680 (미국주식 월별계좌수익률현황).
type USStockMonthlyAccountReturnRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// USStockMonthlyAccountReturnResponse is the response payload for usa21680 (미국주식 월별계좌수익률현황).
type USStockMonthlyAccountReturnResponse struct {
	ResultList []USStockMonthlyAccountReturnResponseResultListItem `json:"result_list"`
	ReturnCode int                                                 `json:"return_code"`
	ReturnMsg  string                                              `json:"return_msg"`
}

// USStockMonthlyAccountReturnResponseResultListItem is a list row in USStockMonthlyAccountReturnResponse.
type USStockMonthlyAccountReturnResponseResultListItem struct {
	BaseDt         string `json:"base_dt"`
	StkEvlta       string `json:"stk_evlta"`
	PlAmt          string `json:"pl_amt"`
	DvidAmt        string `json:"dvid_amt"`
	CmsnTax        string `json:"cmsn_tax"`
	AcumPlAmt      string `json:"acum_pl_amt"`
	PymnAmt        string `json:"pymn_amt"`
	Dast           string `json:"dast"`
	DlyAmt         string `json:"dly_amt"`
	SellAmt        string `json:"sell_amt"`
	BuyAmt         string `json:"buy_amt"`
	PrftRt         string `json:"prft_rt"`
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	FrgnStkInqAmt  string `json:"frgn_stk_inq_amt"`
	InaAmt         string `json:"ina_amt"`
	Exrt           string `json:"exrt"`
}

// GetUSStockMonthlyAccountReturn calls Kiwoom usa21680 — 미국주식 월별계좌수익률현황.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockMonthlyAccountReturn(ctx context.Context, req *USStockMonthlyAccountReturnRequest) (*USStockMonthlyAccountReturnResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/acnt", "usa21680", req)
	if err != nil {
		return nil, err
	}
	var res USStockMonthlyAccountReturnResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockYearlyAccountReturnRequest is the request payload for usa21690 (미국주식 연도별계좌수익률현황).
type USStockYearlyAccountReturnRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// USStockYearlyAccountReturnResponse is the response payload for usa21690 (미국주식 연도별계좌수익률현황).
type USStockYearlyAccountReturnResponse struct {
	ResultList []USStockYearlyAccountReturnResponseResultListItem `json:"result_list"`
	ReturnCode int                                                `json:"return_code"`
	ReturnMsg  string                                             `json:"return_msg"`
}

// USStockYearlyAccountReturnResponseResultListItem is a list row in USStockYearlyAccountReturnResponse.
type USStockYearlyAccountReturnResponseResultListItem struct {
	BaseDt         string `json:"base_dt"`
	StkEvlta       string `json:"stk_evlta"`
	PlAmt          string `json:"pl_amt"`
	DvidAmt        string `json:"dvid_amt"`
	CmsnTax        string `json:"cmsn_tax"`
	AcumPlAmt      string `json:"acum_pl_amt"`
	PymnAmt        string `json:"pymn_amt"`
	Dast           string `json:"dast"`
	DlyAmt         string `json:"dly_amt"`
	SellAmt        string `json:"sell_amt"`
	BuyAmt         string `json:"buy_amt"`
	PrftRt         string `json:"prft_rt"`
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	FrgnStkInqAmt  string `json:"frgn_stk_inq_amt"`
	InaAmt         string `json:"ina_amt"`
	Exrt           string `json:"exrt"`
}

// GetUSStockYearlyAccountReturn calls Kiwoom usa21690 — 미국주식 연도별계좌수익률현황.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockYearlyAccountReturn(ctx context.Context, req *USStockYearlyAccountReturnRequest) (*USStockYearlyAccountReturnResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/acnt", "usa21690", req)
	if err != nil {
		return nil, err
	}
	var res USStockYearlyAccountReturnResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockDailyStockReturnRequest is the request payload for usa21730 (미국주식 일별종목수익률현황).
type USStockDailyStockReturnRequest struct {
	From   string `json:"from"`
	To     string `json:"to"`
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockDailyStockReturnResponse is the response payload for usa21730 (미국주식 일별종목수익률현황).
type USStockDailyStockReturnResponse struct {
	ResultList []USStockDailyStockReturnResponseResultListItem `json:"result_list"`
	ReturnCode int                                             `json:"return_code"`
	ReturnMsg  string                                          `json:"return_msg"`
}

// USStockDailyStockReturnResponseResultListItem is a list row in USStockDailyStockReturnResponse.
type USStockDailyStockReturnResponseResultListItem struct {
	StkCd          string `json:"stk_cd"`
	StkNm          string `json:"stk_nm"`
	FrstBaseDt     string `json:"frst_base_dt"`
	LastBaseDt     string `json:"last_base_dt"`
	PlAmt          string `json:"pl_amt"`
	PrftRt         string `json:"prft_rt"`
	FrstStkEvlta   string `json:"frst_stk_evlta"`
	LastStkEvlta   string `json:"last_stk_evlta"`
	FrstQty        string `json:"frst_qty"`
	LastQty        string `json:"last_qty"`
	BuyQty         string `json:"buy_qty"`
	SellQty        string `json:"sell_qty"`
	BuyAmt         string `json:"buy_amt"`
	SellAmt        string `json:"sell_amt"`
	FrgnStkInqAmt  string `json:"frgn_stk_inq_amt"`
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	CmsnTax        string `json:"cmsn_tax"`
	DvidAmt        string `json:"dvid_amt"`
	CrncCode       string `json:"crnc_code"`
}

// GetUSStockDailyStockReturn calls Kiwoom usa21730 — 미국주식 일별종목수익률현황.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockDailyStockReturn(ctx context.Context, req *USStockDailyStockReturnRequest) (*USStockDailyStockReturnResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/acnt", "usa21730", req)
	if err != nil {
		return nil, err
	}
	var res USStockDailyStockReturnResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockMonthlyStockReturnRequest is the request payload for usa21731 (미국주식 월별종목수익률현황).
type USStockMonthlyStockReturnRequest struct {
	From   string `json:"from"`
	To     string `json:"to"`
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockMonthlyStockReturnResponse is the response payload for usa21731 (미국주식 월별종목수익률현황).
type USStockMonthlyStockReturnResponse struct {
	ResultList []USStockMonthlyStockReturnResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USStockMonthlyStockReturnResponseResultListItem is a list row in USStockMonthlyStockReturnResponse.
type USStockMonthlyStockReturnResponseResultListItem struct {
	StkCd          string `json:"stk_cd"`
	StkNm          string `json:"stk_nm"`
	FrstBaseDt     string `json:"frst_base_dt"`
	LastBaseDt     string `json:"last_base_dt"`
	PlAmt          string `json:"pl_amt"`
	PrftRt         string `json:"prft_rt"`
	FrstStkEvlta   string `json:"frst_stk_evlta"`
	LastStkEvlta   string `json:"last_stk_evlta"`
	FrstQty        string `json:"frst_qty"`
	LastQty        string `json:"last_qty"`
	BuyQty         string `json:"buy_qty"`
	SellQty        string `json:"sell_qty"`
	BuyAmt         string `json:"buy_amt"`
	SellAmt        string `json:"sell_amt"`
	FrgnStkInqAmt  string `json:"frgn_stk_inq_amt"`
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	CmsnTax        string `json:"cmsn_tax"`
	DvidAmt        string `json:"dvid_amt"`
	CrncCode       string `json:"crnc_code"`
}

// GetUSStockMonthlyStockReturn calls Kiwoom usa21731 — 미국주식 월별종목수익률현황.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockMonthlyStockReturn(ctx context.Context, req *USStockMonthlyStockReturnRequest) (*USStockMonthlyStockReturnResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/acnt", "usa21731", req)
	if err != nil {
		return nil, err
	}
	var res USStockMonthlyStockReturnResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockYearlyStockReturnRequest is the request payload for usa21732 (미국주식 연도별종목수익률현황).
type USStockYearlyStockReturnRequest struct {
	From   string `json:"from"`
	To     string `json:"to"`
	StexTp string `json:"stex_tp"`
	StkCd  string `json:"stk_cd"`
}

// USStockYearlyStockReturnResponse is the response payload for usa21732 (미국주식 연도별종목수익률현황).
type USStockYearlyStockReturnResponse struct {
	ResultList []USStockYearlyStockReturnResponseResultListItem `json:"result_list"`
	ReturnCode int                                              `json:"return_code"`
	ReturnMsg  string                                           `json:"return_msg"`
}

// USStockYearlyStockReturnResponseResultListItem is a list row in USStockYearlyStockReturnResponse.
type USStockYearlyStockReturnResponseResultListItem struct {
	StkCd          string `json:"stk_cd"`
	StkNm          string `json:"stk_nm"`
	FrstBaseDt     string `json:"frst_base_dt"`
	LastBaseDt     string `json:"last_base_dt"`
	PlAmt          string `json:"pl_amt"`
	PrftRt         string `json:"prft_rt"`
	FrstStkEvlta   string `json:"frst_stk_evlta"`
	LastStkEvlta   string `json:"last_stk_evlta"`
	FrstQty        string `json:"frst_qty"`
	LastQty        string `json:"last_qty"`
	BuyQty         string `json:"buy_qty"`
	SellQty        string `json:"sell_qty"`
	BuyAmt         string `json:"buy_amt"`
	SellAmt        string `json:"sell_amt"`
	FrgnStkInqAmt  string `json:"frgn_stk_inq_amt"`
	FrgnStkOutqAmt string `json:"frgn_stk_outq_amt"`
	CmsnTax        string `json:"cmsn_tax"`
	DvidAmt        string `json:"dvid_amt"`
	CrncCode       string `json:"crnc_code"`
}

// GetUSStockYearlyStockReturn calls Kiwoom usa21732 — 미국주식 연도별종목수익률현황.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockYearlyStockReturn(ctx context.Context, req *USStockYearlyStockReturnRequest) (*USStockYearlyStockReturnResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/acnt", "usa21732", req)
	if err != nil {
		return nil, err
	}
	var res USStockYearlyStockReturnResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockSectorPeriodReturnRequest is the request payload for usa23000 (미국주식 업종별 기간별 수익률 조회).
type USStockSectorPeriodReturnRequest struct {
	StexTp string `json:"stex_tp"`
	IndsCd string `json:"inds_cd"`
}

// USStockSectorPeriodReturnResponse is the response payload for usa23000 (미국주식 업종별 기간별 수익률 조회).
type USStockSectorPeriodReturnResponse struct {
	ResultList []USStockSectorPeriodReturnResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USStockSectorPeriodReturnResponseResultListItem is a list row in USStockSectorPeriodReturnResponse.
type USStockSectorPeriodReturnResponseResultListItem struct {
	IndsCd  string `json:"inds_cd"`
	IndsNm  string `json:"inds_nm"`
	PerfN1d string `json:"perf_1d"`
	PerfN5d string `json:"perf_5d"`
	PerfN1m string `json:"perf_1m"`
	PerfN3m string `json:"perf_3m"`
	PerfN6m string `json:"perf_6m"`
	PerfYtd string `json:"perf_ytd"`
	PerfN1y string `json:"perf_1y"`
}

// GetUSStockSectorPeriodReturn calls Kiwoom usa23000 — 미국주식 업종별 기간별 수익률 조회.
// 업종 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockSectorPeriodReturn(ctx context.Context, req *USStockSectorPeriodReturnRequest) (*USStockSectorPeriodReturnResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/sect", "usa23000", req)
	if err != nil {
		return nil, err
	}
	var res USStockSectorPeriodReturnResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockSectorChangeRateRankRequest is the request payload for usa23100 (미국주식 업종별 등락률 상위/하위 조회).
type USStockSectorChangeRateRankRequest struct {
	StexTp string `json:"stex_tp"`
	SortTp string `json:"sort_tp"`
	IndsCd string `json:"inds_cd"`
}

// USStockSectorChangeRateRankResponse is the response payload for usa23100 (미국주식 업종별 등락률 상위/하위 조회).
type USStockSectorChangeRateRankResponse struct {
	ResultList []USStockSectorChangeRateRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                 `json:"return_code"`
	ReturnMsg  string                                              `json:"return_msg"`
}

// USStockSectorChangeRateRankResponseResultListItem is a list row in USStockSectorChangeRateRankResponse.
type USStockSectorChangeRateRankResponseResultListItem struct {
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	SelBid     string `json:"sel_bid"`
	BuyBid     string `json:"buy_bid"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
	CntrTm     string `json:"cntr_tm"`
}

// GetUSStockSectorChangeRateRank calls Kiwoom usa23100 — 미국주식 업종별 등락률 상위/하위 조회.
// 업종 정보를 확인할 수 있습니다.
func (c *Client) GetUSStockSectorChangeRateRank(ctx context.Context, req *USStockSectorChangeRateRankRequest) (*USStockSectorChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/sect", "usa23100", req)
	if err != nil {
		return nil, err
	}
	var res USStockSectorChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockVolumeRenewalRequest is the request payload for usa23400 (미국주식 거래량갱신(주식/업종)).
type USStockVolumeRenewalRequest struct {
	StexTp       string `json:"stex_tp"`
	StkCd        string `json:"stk_cd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	DtTp         string `json:"dt_tp"`
}

// USStockVolumeRenewalResponse is the response payload for usa23400 (미국주식 거래량갱신(주식/업종)).
type USStockVolumeRenewalResponse struct {
	ResultList []USStockVolumeRenewalResponseResultListItem `json:"result_list"`
	ReturnCode int                                          `json:"return_code"`
	ReturnMsg  string                                       `json:"return_msg"`
}

// USStockVolumeRenewalResponseResultListItem is a list row in USStockVolumeRenewalResponse.
type USStockVolumeRenewalResponseResultListItem struct {
	MgnType     string `json:"mgn_type"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	PrevTrdeQty string `json:"prev_trde_qty"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
}

// GetUSStockVolumeRenewal calls Kiwoom usa23400 — 미국주식 거래량갱신(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockVolumeRenewal(ctx context.Context, req *USStockVolumeRenewalRequest) (*USStockVolumeRenewalResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa23400", req)
	if err != nil {
		return nil, err
	}
	var res USStockVolumeRenewalResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFVolumeRenewalRequest is the request payload for usa23401 (미국주식 거래량갱신(ETF)).
type USETFVolumeRenewalRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	DtTp         string `json:"dt_tp"`
}

// USETFVolumeRenewalResponse is the response payload for usa23401 (미국주식 거래량갱신(ETF)).
type USETFVolumeRenewalResponse struct {
	ResultList []USETFVolumeRenewalResponseResultListItem `json:"result_list"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// USETFVolumeRenewalResponseResultListItem is a list row in USETFVolumeRenewalResponse.
type USETFVolumeRenewalResponseResultListItem struct {
	MgnType     string `json:"mgn_type"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	PrevTrdeQty string `json:"prev_trde_qty"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
}

// GetUSETFVolumeRenewal calls Kiwoom usa23401 — 미국주식 거래량갱신(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFVolumeRenewal(ctx context.Context, req *USETFVolumeRenewalRequest) (*USETFVolumeRenewalResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa23401", req)
	if err != nil {
		return nil, err
	}
	var res USETFVolumeRenewalResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USWatchlistVolumeRenewalRequest is the request payload for usa23402 (미국주식 거래량갱신(관심종목)).
type USWatchlistVolumeRenewalRequest struct {
	StexTp       string `json:"stex_tp"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	DtTp         string `json:"dt_tp"`
}

// USWatchlistVolumeRenewalRequestStkCdItem is a list row in USWatchlistVolumeRenewalRequest.
type USWatchlistVolumeRenewalRequestStkCdItem struct {
}

// USWatchlistVolumeRenewalResponse is the response payload for usa23402 (미국주식 거래량갱신(관심종목)).
type USWatchlistVolumeRenewalResponse struct {
	ResultList []USWatchlistVolumeRenewalResponseResultListItem `json:"result_list"`
	ReturnCode int                                              `json:"return_code"`
	ReturnMsg  string                                           `json:"return_msg"`
}

// USWatchlistVolumeRenewalResponseResultListItem is a list row in USWatchlistVolumeRenewalResponse.
type USWatchlistVolumeRenewalResponseResultListItem struct {
	MgnType     string `json:"mgn_type"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	PrevTrdeQty string `json:"prev_trde_qty"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
}

// GetUSWatchlistVolumeRenewal calls Kiwoom usa23402 — 미국주식 거래량갱신(관심종목).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSWatchlistVolumeRenewal(ctx context.Context, req *USWatchlistVolumeRenewalRequest) (*USWatchlistVolumeRenewalResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa23402", req)
	if err != nil {
		return nil, err
	}
	var res USWatchlistVolumeRenewalResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockNewHighLowRequest is the request payload for usa24100 (미국주식 신고가/신저가(주식/업종)).
type USStockNewHighLowRequest struct {
	StexTp       string `json:"stex_tp"`
	StkTp        string `json:"stk_tp"`
	IndsCd       string `json:"inds_cd"`
	StkCnd       string `json:"stk_cnd"`
	NtlTp        string `json:"ntl_tp"`
	HighLowTp    string `json:"high_low_tp"`
	Dt           string `json:"dt"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockNewHighLowResponse is the response payload for usa24100 (미국주식 신고가/신저가(주식/업종)).
type USStockNewHighLowResponse struct {
	ResultList []USStockNewHighLowResponseResultListItem `json:"result_list"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// USStockNewHighLowResponseResultListItem is a list row in USStockNewHighLowResponse.
type USStockNewHighLowResponseResultListItem struct {
	MgnType     string `json:"mgn_type"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	PreTrdeRt   string `json:"pre_trde_rt"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
	HighPric    string `json:"high_pric"`
	LowPric     string `json:"low_pric"`
	PredTrdeQty string `json:"pred_trde_qty"`
}

// GetUSStockNewHighLow calls Kiwoom usa24100 — 미국주식 신고가/신저가(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockNewHighLow(ctx context.Context, req *USStockNewHighLowRequest) (*USStockNewHighLowResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24100", req)
	if err != nil {
		return nil, err
	}
	var res USStockNewHighLowResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFNewHighLowRequest is the request payload for usa24101 (미국주식 신고가/신저가(ETF)).
type USETFNewHighLowRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	StkCnd       string `json:"stk_cnd"`
	NtlTp        string `json:"ntl_tp"`
	HighLowTp    string `json:"high_low_tp"`
	Dt           string `json:"dt"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFNewHighLowResponse is the response payload for usa24101 (미국주식 신고가/신저가(ETF)).
type USETFNewHighLowResponse struct {
	ResultList []USETFNewHighLowResponseResultListItem `json:"result_list"`
	ReturnCode int                                     `json:"return_code"`
	ReturnMsg  string                                  `json:"return_msg"`
}

// USETFNewHighLowResponseResultListItem is a list row in USETFNewHighLowResponse.
type USETFNewHighLowResponseResultListItem struct {
	MgnType     string `json:"mgn_type"`
	StexTp      string `json:"stex_tp"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	StkEnm      string `json:"stk_enm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	AccTrdeQty  string `json:"acc_trde_qty"`
	PreTrdeRt   string `json:"pre_trde_rt"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
	HighPric    string `json:"high_pric"`
	LowPric     string `json:"low_pric"`
	PredTrdeQty string `json:"pred_trde_qty"`
}

// GetUSETFNewHighLow calls Kiwoom usa24101 — 미국주식 신고가/신저가(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFNewHighLow(ctx context.Context, req *USETFNewHighLowRequest) (*USETFNewHighLowResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24101", req)
	if err != nil {
		return nil, err
	}
	var res USETFNewHighLowResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockFromExtremePriceChangeRequest is the request payload for usa24110 (미국주식 최고최저가대비 상승하락(주식/업종)).
type USStockFromExtremePriceChangeRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	SortTp       string `json:"sort_tp"`
	DtTp         string `json:"dt_tp"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockFromExtremePriceChangeResponse is the response payload for usa24110 (미국주식 최고최저가대비 상승하락(주식/업종)).
type USStockFromExtremePriceChangeResponse struct {
	ResultList []USStockFromExtremePriceChangeResponseResultListItem `json:"result_list"`
	ReturnCode int                                                   `json:"return_code"`
	ReturnMsg  string                                                `json:"return_msg"`
}

// USStockFromExtremePriceChangeResponseResultListItem is a list row in USStockFromExtremePriceChangeResponse.
type USStockFromExtremePriceChangeResponseResultListItem struct {
	Rank          string `json:"rank"`
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	OyrHgst       string `json:"oyr_hgst"`
	OyrLwst       string `json:"oyr_lwst"`
	N52wkHgstPric string `json:"52wk_hgst_pric"`
	N52wkLwstPric string `json:"52wk_lwst_pric"`
	HlPreSig      string `json:"hl_pre_sig"`
	HlPre         string `json:"hl_pre"`
	PreFluRt      string `json:"pre_flu_rt"`
	BaseDt        string `json:"base_dt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
}

// GetUSStockFromExtremePriceChange calls Kiwoom usa24110 — 미국주식 최고최저가대비 상승하락(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockFromExtremePriceChange(ctx context.Context, req *USStockFromExtremePriceChangeRequest) (*USStockFromExtremePriceChangeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24110", req)
	if err != nil {
		return nil, err
	}
	var res USStockFromExtremePriceChangeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFFromExtremePriceChangeRequest is the request payload for usa24111 (미국주식 최고최저가대비 상승하락(ETF)).
type USETFFromExtremePriceChangeRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	SortTp       string `json:"sort_tp"`
	DtTp         string `json:"dt_tp"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFFromExtremePriceChangeResponse is the response payload for usa24111 (미국주식 최고최저가대비 상승하락(ETF)).
type USETFFromExtremePriceChangeResponse struct {
	ResultList []USETFFromExtremePriceChangeResponseResultListItem `json:"result_list"`
	ReturnCode int                                                 `json:"return_code"`
	ReturnMsg  string                                              `json:"return_msg"`
}

// USETFFromExtremePriceChangeResponseResultListItem is a list row in USETFFromExtremePriceChangeResponse.
type USETFFromExtremePriceChangeResponseResultListItem struct {
	Rank          string `json:"rank"`
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	OyrHgst       string `json:"oyr_hgst"`
	OyrLwst       string `json:"oyr_lwst"`
	N52wkHgstPric string `json:"52wk_hgst_pric"`
	N52wkLwstPric string `json:"52wk_lwst_pric"`
	HlPreSig      string `json:"hl_pre_sig"`
	HlPre         string `json:"hl_pre"`
	PreFluRt      string `json:"pre_flu_rt"`
	BaseDt        string `json:"base_dt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
}

// GetUSETFFromExtremePriceChange calls Kiwoom usa24111 — 미국주식 최고최저가대비 상승하락(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFFromExtremePriceChange(ctx context.Context, req *USETFFromExtremePriceChangeRequest) (*USETFFromExtremePriceChangeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24111", req)
	if err != nil {
		return nil, err
	}
	var res USETFFromExtremePriceChangeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockSpecificDateChangeRequest is the request payload for usa24120 (미국주식 특정일자 상승/하락 (주식/업종)).
type USStockSpecificDateChangeRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	BaseDt       string `json:"base_dt"`
	SortTp       string `json:"sort_tp"`
}

// USStockSpecificDateChangeResponse is the response payload for usa24120 (미국주식 특정일자 상승/하락 (주식/업종)).
type USStockSpecificDateChangeResponse struct {
	ResultList []USStockSpecificDateChangeResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USStockSpecificDateChangeResponseResultListItem is a list row in USStockSpecificDateChangeResponse.
type USStockSpecificDateChangeResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	BaseDt     string `json:"base_dt"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	TrdePrica  string `json:"trde_prica"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
	FluRt      string `json:"flu_rt"`
}

// GetUSStockSpecificDateChange calls Kiwoom usa24120 — 미국주식 특정일자 상승/하락 (주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockSpecificDateChange(ctx context.Context, req *USStockSpecificDateChangeRequest) (*USStockSpecificDateChangeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24120", req)
	if err != nil {
		return nil, err
	}
	var res USStockSpecificDateChangeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFSpecificDateChangeRequest is the request payload for usa24121 (미국주식 특정일자 상승/하락(ETF)).
type USETFSpecificDateChangeRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	BaseDt       string `json:"base_dt"`
	SortTp       string `json:"sort_tp"`
}

// USETFSpecificDateChangeResponse is the response payload for usa24121 (미국주식 특정일자 상승/하락(ETF)).
type USETFSpecificDateChangeResponse struct {
	ResultList []USETFSpecificDateChangeResponseResultListItem `json:"result_list"`
	ReturnCode int                                             `json:"return_code"`
	ReturnMsg  string                                          `json:"return_msg"`
}

// USETFSpecificDateChangeResponseResultListItem is a list row in USETFSpecificDateChangeResponse.
type USETFSpecificDateChangeResponseResultListItem struct {
	Rank       string `json:"rank"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	BaseDt     string `json:"base_dt"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	TrdePrica  string `json:"trde_prica"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
	FluRt      string `json:"flu_rt"`
}

// GetUSETFSpecificDateChange calls Kiwoom usa24121 — 미국주식 특정일자 상승/하락(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFSpecificDateChange(ctx context.Context, req *USETFSpecificDateChangeRequest) (*USETFSpecificDateChangeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24121", req)
	if err != nil {
		return nil, err
	}
	var res USETFSpecificDateChangeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockGapUpDownRequest is the request payload for usa24140 (미국주식 갭상승/갭하락(주식/업종)).
type USStockGapUpDownRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	SortTp       string `json:"sort_tp"`
	UpdownTp     string `json:"updown_tp"`
	AlaccRt      string `json:"alacc_rt"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
}

// USStockGapUpDownResponse is the response payload for usa24140 (미국주식 갭상승/갭하락(주식/업종)).
type USStockGapUpDownResponse struct {
	ResultList []USStockGapUpDownResponseResultListItem `json:"result_list"`
	ReturnCode int                                      `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
}

// USStockGapUpDownResponseResultListItem is a list row in USStockGapUpDownResponse.
type USStockGapUpDownResponseResultListItem struct {
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	OpenPric      string `json:"open_pric"`
	BaseClosePric string `json:"base_close_pric"`
	GapRt         string `json:"gap_rt"`
	PreHighPric   string `json:"pre_high_pric"`
	PredTrdeQty   string `json:"pred_trde_qty"`
}

// GetUSStockGapUpDown calls Kiwoom usa24140 — 미국주식 갭상승/갭하락(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockGapUpDown(ctx context.Context, req *USStockGapUpDownRequest) (*USStockGapUpDownResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24140", req)
	if err != nil {
		return nil, err
	}
	var res USStockGapUpDownResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFGapUpDownRequest is the request payload for usa24141 (미국주식 갭상승/갭하락(ETF)).
type USETFGapUpDownRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	SortTp       string `json:"sort_tp"`
	UpdownTp     string `json:"updown_tp"`
	AlaccRt      string `json:"alacc_rt"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
}

// USETFGapUpDownResponse is the response payload for usa24141 (미국주식 갭상승/갭하락(ETF)).
type USETFGapUpDownResponse struct {
	ResultList []USETFGapUpDownResponseResultListItem `json:"result_list"`
	ReturnCode int                                    `json:"return_code"`
	ReturnMsg  string                                 `json:"return_msg"`
}

// USETFGapUpDownResponseResultListItem is a list row in USETFGapUpDownResponse.
type USETFGapUpDownResponseResultListItem struct {
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	OpenPric      string `json:"open_pric"`
	BaseClosePric string `json:"base_close_pric"`
	GapRt         string `json:"gap_rt"`
	PreHighPric   string `json:"pre_high_pric"`
	PredTrdeQty   string `json:"pred_trde_qty"`
}

// GetUSETFGapUpDown calls Kiwoom usa24141 — 미국주식 갭상승/갭하락(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFGapUpDown(ctx context.Context, req *USETFGapUpDownRequest) (*USETFGapUpDownResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24141", req)
	if err != nil {
		return nil, err
	}
	var res USETFGapUpDownResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockTurnoverRankRequest is the request payload for usa24150 (미국주식 회전율 상위(주식/업종)).
type USStockTurnoverRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockTurnoverRankResponse is the response payload for usa24150 (미국주식 회전율 상위(주식/업종)).
type USStockTurnoverRankResponse struct {
	ResultList []USStockTurnoverRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                         `json:"return_code"`
	ReturnMsg  string                                      `json:"return_msg"`
}

// USStockTurnoverRankResponseResultListItem is a list row in USStockTurnoverRankResponse.
type USStockTurnoverRankResponseResultListItem struct {
	Rank          string `json:"rank"`
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	TrdeTernRt    string `json:"trde_tern_rt"`
	N2dAvgTernRt  string `json:"2d_avg_tern_rt"`
	N10dAvgTernRt string `json:"10d_avg_tern_rt"`
	N20dAvgTernRt string `json:"20d_avg_tern_rt"`
}

// GetUSStockTurnoverRank calls Kiwoom usa24150 — 미국주식 회전율 상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockTurnoverRank(ctx context.Context, req *USStockTurnoverRankRequest) (*USStockTurnoverRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24150", req)
	if err != nil {
		return nil, err
	}
	var res USStockTurnoverRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFTurnoverRankRequest is the request payload for usa24151 (미국주식 회전율 상위(ETF)).
type USETFTurnoverRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFTurnoverRankResponse is the response payload for usa24151 (미국주식 회전율 상위(ETF)).
type USETFTurnoverRankResponse struct {
	ResultList []USETFTurnoverRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// USETFTurnoverRankResponseResultListItem is a list row in USETFTurnoverRankResponse.
type USETFTurnoverRankResponseResultListItem struct {
	Rank          string `json:"rank"`
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	TrdeTernRt    string `json:"trde_tern_rt"`
	N2dAvgTernRt  string `json:"2d_avg_tern_rt"`
	N10dAvgTernRt string `json:"10d_avg_tern_rt"`
	N20dAvgTernRt string `json:"20d_avg_tern_rt"`
}

// GetUSETFTurnoverRank calls Kiwoom usa24151 — 미국주식 회전율 상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFTurnoverRank(ctx context.Context, req *USETFTurnoverRankRequest) (*USETFTurnoverRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24151", req)
	if err != nil {
		return nil, err
	}
	var res USETFTurnoverRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockConsecutiveChangeRankRequest is the request payload for usa24160 (미국주식 연속상승/하락 순위(주식/업종)).
type USStockConsecutiveChangeRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	SortTp       string `json:"sort_tp"`
}

// USStockConsecutiveChangeRankResponse is the response payload for usa24160 (미국주식 연속상승/하락 순위(주식/업종)).
type USStockConsecutiveChangeRankResponse struct {
	ResultList []USStockConsecutiveChangeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                  `json:"return_code"`
	ReturnMsg  string                                               `json:"return_msg"`
}

// USStockConsecutiveChangeRankResponseResultListItem is a list row in USStockConsecutiveChangeRankResponse.
type USStockConsecutiveChangeRankResponseResultListItem struct {
	Rank          string `json:"rank"`
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	BaseClosePric string `json:"base_close_pric"`
	BasePreRt     string `json:"base_pre_rt"`
	ContiDt       string `json:"conti_dt"`
}

// GetUSStockConsecutiveChangeRank calls Kiwoom usa24160 — 미국주식 연속상승/하락 순위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockConsecutiveChangeRank(ctx context.Context, req *USStockConsecutiveChangeRankRequest) (*USStockConsecutiveChangeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24160", req)
	if err != nil {
		return nil, err
	}
	var res USStockConsecutiveChangeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFConsecutiveChangeRankRequest is the request payload for usa24161 (미국주식 연속상승/하락 순위(ETF)).
type USETFConsecutiveChangeRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	SortTp       string `json:"sort_tp"`
}

// USETFConsecutiveChangeRankResponse is the response payload for usa24161 (미국주식 연속상승/하락 순위(ETF)).
type USETFConsecutiveChangeRankResponse struct {
	ResultList []USETFConsecutiveChangeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                `json:"return_code"`
	ReturnMsg  string                                             `json:"return_msg"`
}

// USETFConsecutiveChangeRankResponseResultListItem is a list row in USETFConsecutiveChangeRankResponse.
type USETFConsecutiveChangeRankResponseResultListItem struct {
	Rank          string `json:"rank"`
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	BaseClosePric string `json:"base_close_pric"`
	BasePreRt     string `json:"base_pre_rt"`
	ContiDt       string `json:"conti_dt"`
}

// GetUSETFConsecutiveChangeRank calls Kiwoom usa24161 — 미국주식 연속상승/하락 순위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFConsecutiveChangeRank(ctx context.Context, req *USETFConsecutiveChangeRankRequest) (*USETFConsecutiveChangeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24161", req)
	if err != nil {
		return nil, err
	}
	var res USETFConsecutiveChangeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USWatchlistConsecutiveChangeRankRequest is the request payload for usa24162 (미국주식 연속상승/하락 순위(관심종목)).
type USWatchlistConsecutiveChangeRankRequest struct {
	StexTp       string `json:"stex_tp"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	SortTp       string `json:"sort_tp"`
}

// USWatchlistConsecutiveChangeRankRequestStkCdItem is a list row in USWatchlistConsecutiveChangeRankRequest.
type USWatchlistConsecutiveChangeRankRequestStkCdItem struct {
}

// USWatchlistConsecutiveChangeRankResponse is the response payload for usa24162 (미국주식 연속상승/하락 순위(관심종목)).
type USWatchlistConsecutiveChangeRankResponse struct {
	ResultList []USWatchlistConsecutiveChangeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                      `json:"return_code"`
	ReturnMsg  string                                                   `json:"return_msg"`
}

// USWatchlistConsecutiveChangeRankResponseResultListItem is a list row in USWatchlistConsecutiveChangeRankResponse.
type USWatchlistConsecutiveChangeRankResponseResultListItem struct {
	Rank          string `json:"rank"`
	MgnType       string `json:"mgn_type"`
	StexTp        string `json:"stex_tp"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	StkEnm        string `json:"stk_enm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	BaseClosePric string `json:"base_close_pric"`
	BasePreRt     string `json:"base_pre_rt"`
	ContiDt       string `json:"conti_dt"`
}

// GetUSWatchlistConsecutiveChangeRank calls Kiwoom usa24162 — 미국주식 연속상승/하락 순위(관심종목).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSWatchlistConsecutiveChangeRank(ctx context.Context, req *USWatchlistConsecutiveChangeRankRequest) (*USWatchlistConsecutiveChangeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24162", req)
	if err != nil {
		return nil, err
	}
	var res USWatchlistConsecutiveChangeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockQuoteVolumeRankRequest is the request payload for usa24200 (미국주식 호가잔량상위(주식/업종)).
type USStockQuoteVolumeRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	SortTp       string `json:"sort_tp"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockQuoteVolumeRankResponse is the response payload for usa24200 (미국주식 호가잔량상위(주식/업종)).
type USStockQuoteVolumeRankResponse struct {
	ResultList []USStockQuoteVolumeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                            `json:"return_code"`
	ReturnMsg  string                                         `json:"return_msg"`
}

// USStockQuoteVolumeRankResponseResultListItem is a list row in USStockQuoteVolumeRankResponse.
type USStockQuoteVolumeRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	TotSelReq  string `json:"tot_sel_req"`
	TotBuyReq  string `json:"tot_buy_req"`
	BuyReq     string `json:"buy_req"`
	BuyRt      string `json:"buy_rt"`
	SelReq     string `json:"sel_req"`
	SelRt      string `json:"sel_rt"`
	CntrTm     string `json:"cntr_tm"`
}

// GetUSStockQuoteVolumeRank calls Kiwoom usa24200 — 미국주식 호가잔량상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockQuoteVolumeRank(ctx context.Context, req *USStockQuoteVolumeRankRequest) (*USStockQuoteVolumeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24200", req)
	if err != nil {
		return nil, err
	}
	var res USStockQuoteVolumeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFQuoteVolumeRankRequest is the request payload for usa24201 (미국주식 호가잔량상위(ETF)).
type USETFQuoteVolumeRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	SortTp       string `json:"sort_tp"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFQuoteVolumeRankResponse is the response payload for usa24201 (미국주식 호가잔량상위(ETF)).
type USETFQuoteVolumeRankResponse struct {
	ResultList []USETFQuoteVolumeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                          `json:"return_code"`
	ReturnMsg  string                                       `json:"return_msg"`
}

// USETFQuoteVolumeRankResponseResultListItem is a list row in USETFQuoteVolumeRankResponse.
type USETFQuoteVolumeRankResponseResultListItem struct {
	Rank       string `json:"rank"`
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	AccTrdeQty string `json:"acc_trde_qty"`
	TotSelReq  string `json:"tot_sel_req"`
	TotBuyReq  string `json:"tot_buy_req"`
	BuyReq     string `json:"buy_req"`
	BuyRt      string `json:"buy_rt"`
	SelReq     string `json:"sel_req"`
	SelRt      string `json:"sel_rt"`
	CntrTm     string `json:"cntr_tm"`
}

// GetUSETFQuoteVolumeRank calls Kiwoom usa24201 — 미국주식 호가잔량상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFQuoteVolumeRank(ctx context.Context, req *USETFQuoteVolumeRankRequest) (*USETFQuoteVolumeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24201", req)
	if err != nil {
		return nil, err
	}
	var res USETFQuoteVolumeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockRemainingRateSurgeRequest is the request payload for usa24210 (미국주식 잔량률급증(주식/업종)).
type USStockRemainingRateSurgeRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	RtTp         string `json:"rt_tp"`
	StkTp        string `json:"stk_tp"`
	Tm           string `json:"tm"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockRemainingRateSurgeResponse is the response payload for usa24210 (미국주식 잔량률급증(주식/업종)).
type USStockRemainingRateSurgeResponse struct {
	ResultList []USStockRemainingRateSurgeResponseResultListItem `json:"result_list"`
	ReturnCode int                                               `json:"return_code"`
	ReturnMsg  string                                            `json:"return_msg"`
}

// USStockRemainingRateSurgeResponseResultListItem is a list row in USStockRemainingRateSurgeResponse.
type USStockRemainingRateSurgeResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	Int        string `json:"int"`
	NowRt      string `json:"now_rt"`
	SdninRt    string `json:"sdnin_rt"`
	TotSelReq  string `json:"tot_sel_req"`
	TotBuyReq  string `json:"tot_buy_req"`
}

// GetUSStockRemainingRateSurge calls Kiwoom usa24210 — 미국주식 잔량률급증(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockRemainingRateSurge(ctx context.Context, req *USStockRemainingRateSurgeRequest) (*USStockRemainingRateSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24210", req)
	if err != nil {
		return nil, err
	}
	var res USStockRemainingRateSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFRemainingRateSurgeRequest is the request payload for usa24211 (미국주식 잔량률급증(ETF)).
type USETFRemainingRateSurgeRequest struct {
	StexTp       string `json:"stex_tp"`
	RtTp         string `json:"rt_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	Tm           string `json:"tm"`
	StkCnd       string `json:"stk_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFRemainingRateSurgeResponse is the response payload for usa24211 (미국주식 잔량률급증(ETF)).
type USETFRemainingRateSurgeResponse struct {
	ResultList []USETFRemainingRateSurgeResponseResultListItem `json:"result_list"`
	ReturnCode int                                             `json:"return_code"`
	ReturnMsg  string                                          `json:"return_msg"`
}

// USETFRemainingRateSurgeResponseResultListItem is a list row in USETFRemainingRateSurgeResponse.
type USETFRemainingRateSurgeResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	Int        string `json:"int"`
	NowRt      string `json:"now_rt"`
	SdninRt    string `json:"sdnin_rt"`
	TotSelReq  string `json:"tot_sel_req"`
	TotBuyReq  string `json:"tot_buy_req"`
}

// GetUSETFRemainingRateSurge calls Kiwoom usa24211 — 미국주식 잔량률급증(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFRemainingRateSurge(ctx context.Context, req *USETFRemainingRateSurgeRequest) (*USETFRemainingRateSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24211", req)
	if err != nil {
		return nil, err
	}
	var res USETFRemainingRateSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockPriceClusterRequest is the request payload for usa24220 (미국주식 매물대집중(주식/업종)).
type USStockPriceClusterRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	StkTp        string `json:"stk_tp"`
	Dt           string `json:"dt"`
	PrpsCnctrRt  string `json:"prps_cnctr_rt"`
	Cond         string `json:"cond"`
	Prpscnt      string `json:"prpscnt"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USStockPriceClusterResponse is the response payload for usa24220 (미국주식 매물대집중(주식/업종)).
type USStockPriceClusterResponse struct {
	ResultList []USStockPriceClusterResponseResultListItem `json:"result_list"`
	ReturnCode int                                         `json:"return_code"`
	ReturnMsg  string                                      `json:"return_msg"`
}

// USStockPriceClusterResponseResultListItem is a list row in USStockPriceClusterResponse.
type USStockPriceClusterResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	PricCndSt  string `json:"pric_cnd_st"`
	PricCndEd  string `json:"pric_cnd_ed"`
	PrpsQty    string `json:"prps_qty"`
	PrpsRt     string `json:"prps_rt"`
}

// GetUSStockPriceCluster calls Kiwoom usa24220 — 미국주식 매물대집중(주식/업종).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSStockPriceCluster(ctx context.Context, req *USStockPriceClusterRequest) (*USStockPriceClusterResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24220", req)
	if err != nil {
		return nil, err
	}
	var res USStockPriceClusterResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFPriceClusterRequest is the request payload for usa24221 (미국주식 매물대집중(ETF)).
type USETFPriceClusterRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	Dt           string `json:"dt"`
	PrpsCnctrRt  string `json:"prps_cnctr_rt"`
	Cond         string `json:"cond"`
	Prpscnt      string `json:"prpscnt"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
}

// USETFPriceClusterResponse is the response payload for usa24221 (미국주식 매물대집중(ETF)).
type USETFPriceClusterResponse struct {
	ResultList []USETFPriceClusterResponseResultListItem `json:"result_list"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// USETFPriceClusterResponseResultListItem is a list row in USETFPriceClusterResponse.
type USETFPriceClusterResponseResultListItem struct {
	MgnType    string `json:"mgn_type"`
	StexTp     string `json:"stex_tp"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	StkEnm     string `json:"stk_enm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	PricCndSt  string `json:"pric_cnd_st"`
	PricCndEd  string `json:"pric_cnd_ed"`
	PrpsQty    string `json:"prps_qty"`
	PrpsRt     string `json:"prps_rt"`
}

// GetUSETFPriceCluster calls Kiwoom usa24221 — 미국주식 매물대집중(ETF).
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetUSETFPriceCluster(ctx context.Context, req *USETFPriceClusterRequest) (*USETFPriceClusterResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/stkinfo", "usa24221", req)
	if err != nil {
		return nil, err
	}
	var res USETFPriceClusterResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USStockWeeklyDeviationRankRequest is the request payload for usa24290 (미국주식 주간거래 괴리율 상위(주식/업종)).
type USStockWeeklyDeviationRankRequest struct {
	StexTp       string `json:"stex_tp"`
	IndsCd       string `json:"inds_cd"`
	IndsClsTp    string `json:"inds_cls_tp"`
	StkTp        string `json:"stk_tp"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	SortTp       string `json:"sort_tp"`
}

// USStockWeeklyDeviationRankResponse is the response payload for usa24290 (미국주식 주간거래 괴리율 상위(주식/업종)).
type USStockWeeklyDeviationRankResponse struct {
	ResultList []USStockWeeklyDeviationRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                                `json:"return_code"`
	ReturnMsg  string                                             `json:"return_msg"`
}

// USStockWeeklyDeviationRankResponseResultListItem is a list row in USStockWeeklyDeviationRankResponse.
type USStockWeeklyDeviationRankResponseResultListItem struct {
	Rank         string `json:"rank"`
	MgnType      string `json:"mgn_type"`
	StexTp       string `json:"stex_tp"`
	StkCd        string `json:"stk_cd"`
	StkNm        string `json:"stk_nm"`
	StkEnm       string `json:"stk_enm"`
	CurPrc       string `json:"cur_prc"`
	PredPreSig   string `json:"pred_pre_sig"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	RegClosePric string `json:"reg_close_pric"`
	RegPreSig    string `json:"reg_pre_sig"`
	RegPre       string `json:"reg_pre"`
	DisptyRt     string `json:"dispty_rt"`
	CntrTm       string `json:"cntr_tm"`
	CntrStr      string `json:"cntr_str"`
	Cnt          string `json:"cnt"`
}

// GetUSStockWeeklyDeviationRank calls Kiwoom usa24290 — 미국주식 주간거래 괴리율 상위(주식/업종).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSStockWeeklyDeviationRank(ctx context.Context, req *USStockWeeklyDeviationRankRequest) (*USStockWeeklyDeviationRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24290", req)
	if err != nil {
		return nil, err
	}
	var res USStockWeeklyDeviationRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// USETFWeeklyDeviationRankRequest is the request payload for usa24291 (미국주식 주간거래 괴리율 상위(ETF)).
type USETFWeeklyDeviationRankRequest struct {
	StexTp       string `json:"stex_tp"`
	EtfCat1      string `json:"etf_cat1"`
	EtfCat2      string `json:"etf_cat2"`
	StkCnd       string `json:"stk_cnd"`
	PricCnd      string `json:"pric_cnd"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	SortTp       string `json:"sort_tp"`
}

// USETFWeeklyDeviationRankResponse is the response payload for usa24291 (미국주식 주간거래 괴리율 상위(ETF)).
type USETFWeeklyDeviationRankResponse struct {
	ResultList []USETFWeeklyDeviationRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                              `json:"return_code"`
	ReturnMsg  string                                           `json:"return_msg"`
}

// USETFWeeklyDeviationRankResponseResultListItem is a list row in USETFWeeklyDeviationRankResponse.
type USETFWeeklyDeviationRankResponseResultListItem struct {
	Rank         string `json:"rank"`
	MgnType      string `json:"mgn_type"`
	StexTp       string `json:"stex_tp"`
	StkCd        string `json:"stk_cd"`
	StkNm        string `json:"stk_nm"`
	StkEnm       string `json:"stk_enm"`
	CurPrc       string `json:"cur_prc"`
	PredPreSig   string `json:"pred_pre_sig"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	RegClosePric string `json:"reg_close_pric"`
	RegPreSig    string `json:"reg_pre_sig"`
	RegPre       string `json:"reg_pre"`
	SelBid       string `json:"sel_bid"`
	BuyBid       string `json:"buy_bid"`
	DisptyRt     string `json:"dispty_rt"`
	CntrTm       string `json:"cntr_tm"`
	CntrStr      string `json:"cntr_str"`
	Cnt          string `json:"cnt"`
	SelReq       string `json:"sel_req"`
	BuyReq       string `json:"buy_req"`
}

// GetUSETFWeeklyDeviationRank calls Kiwoom usa24291 — 미국주식 주간거래 괴리율 상위(ETF).
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetUSETFWeeklyDeviationRank(ctx context.Context, req *USETFWeeklyDeviationRankRequest) (*USETFWeeklyDeviationRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/us/rkinfo", "usa24291", req)
	if err != nil {
		return nil, err
	}
	var res USETFWeeklyDeviationRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
