// Code generated by cmd/genapis; DO NOT EDIT.

package kioom

import (
	"context"
	"net/http"
)

// BrokerPriceClusterAnalysisRequest is the request payload for ka10043 (거래원매물대분석요청).
type BrokerPriceClusterAnalysisRequest struct {
	StkCd    string `json:"stk_cd"`
	StrtDt   string `json:"strt_dt"`
	EndDt    string `json:"end_dt"`
	QryDtTp  string `json:"qry_dt_tp"`
	PotTp    string `json:"pot_tp"`
	Dt       string `json:"dt"`
	SortBase string `json:"sort_base"`
	MmcmCd   string `json:"mmcm_cd"`
	StexTp   string `json:"stex_tp"`
}

// BrokerPriceClusterAnalysisResponse is the response payload for ka10043 (거래원매물대분석요청).
type BrokerPriceClusterAnalysisResponse struct {
	TrdeOriPrpsAnly []BrokerPriceClusterAnalysisResponseTrdeOriPrpsAnlyItem `json:"trde_ori_prps_anly"`
	ReturnCode      int                                                     `json:"return_code"`
	ReturnMsg       string                                                  `json:"return_msg"`
}

// BrokerPriceClusterAnalysisResponseTrdeOriPrpsAnlyItem is a list row in BrokerPriceClusterAnalysisResponse.
type BrokerPriceClusterAnalysisResponseTrdeOriPrpsAnlyItem struct {
	Dt         string `json:"dt"`
	ClosePric  string `json:"close_pric"`
	PreSig     string `json:"pre_sig"`
	PredPre    string `json:"pred_pre"`
	SelQty     string `json:"sel_qty"`
	BuyQty     string `json:"buy_qty"`
	NetprpsQty string `json:"netprps_qty"`
	TrdeQtySum string `json:"trde_qty_sum"`
	TrdeWght   string `json:"trde_wght"`
}

// GetBrokerPriceClusterAnalysis calls Kiwoom ka10043 — 거래원매물대분석요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetBrokerPriceClusterAnalysis(ctx context.Context, req *BrokerPriceClusterAnalysisRequest) (*BrokerPriceClusterAnalysisResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10043", req)
	if err != nil {
		return nil, err
	}
	var res BrokerPriceClusterAnalysisResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyInstitutionTradingStocksRequest is the request payload for ka10044 (일별기관매매종목요청).
type DailyInstitutionTradingStocksRequest struct {
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
	TrdeTp string `json:"trde_tp"`
	MrktTp string `json:"mrkt_tp"`
	StexTp string `json:"stex_tp"`
}

// DailyInstitutionTradingStocksResponse is the response payload for ka10044 (일별기관매매종목요청).
type DailyInstitutionTradingStocksResponse struct {
	DalyOrgnTrdeStk []DailyInstitutionTradingStocksResponseDalyOrgnTrdeStkItem `json:"daly_orgn_trde_stk"`
	ReturnCode      int                                                        `json:"return_code"`
	ReturnMsg       string                                                     `json:"return_msg"`
}

// DailyInstitutionTradingStocksResponseDalyOrgnTrdeStkItem is a list row in DailyInstitutionTradingStocksResponse.
type DailyInstitutionTradingStocksResponseDalyOrgnTrdeStkItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	NetprpsQty string `json:"netprps_qty"`
	NetprpsAmt string `json:"netprps_amt"`
}

// GetDailyInstitutionTradingStocks calls Kiwoom ka10044 — 일별기관매매종목요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetDailyInstitutionTradingStocks(ctx context.Context, req *DailyInstitutionTradingStocksRequest) (*DailyInstitutionTradingStocksResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10044", req)
	if err != nil {
		return nil, err
	}
	var res DailyInstitutionTradingStocksResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockInstitutionTradingTrendRequest is the request payload for ka10045 (종목별기관매매추이요청).
type StockInstitutionTradingTrendRequest struct {
	StkCd         string `json:"stk_cd"`
	StrtDt        string `json:"strt_dt"`
	EndDt         string `json:"end_dt"`
	OrgnPrsmUnpTp string `json:"orgn_prsm_unp_tp"`
	ForPrsmUnpTp  string `json:"for_prsm_unp_tp"`
}

// StockInstitutionTradingTrendResponse is the response payload for ka10045 (종목별기관매매추이요청).
type StockInstitutionTradingTrendResponse struct {
	OrgnPrsmAvgPric  string                                                     `json:"orgn_prsm_avg_pric"`
	ForPrsmAvgPric   string                                                     `json:"for_prsm_avg_pric"`
	StkOrgnTrdeTrnsn []StockInstitutionTradingTrendResponseStkOrgnTrdeTrnsnItem `json:"stk_orgn_trde_trnsn"`
	ReturnCode       int                                                        `json:"return_code"`
	ReturnMsg        string                                                     `json:"return_msg"`
}

// StockInstitutionTradingTrendResponseStkOrgnTrdeTrnsnItem is a list row in StockInstitutionTradingTrendResponse.
type StockInstitutionTradingTrendResponseStkOrgnTrdeTrnsnItem struct {
	Dt                 string `json:"dt"`
	ClosePric          string `json:"close_pric"`
	PreSig             string `json:"pre_sig"`
	PredPre            string `json:"pred_pre"`
	FluRt              string `json:"flu_rt"`
	TrdeQty            string `json:"trde_qty"`
	OrgnDtAcc          string `json:"orgn_dt_acc"`
	OrgnDalyNettrdeQty string `json:"orgn_daly_nettrde_qty"`
	ForDtAcc           string `json:"for_dt_acc"`
	ForDalyNettrdeQty  string `json:"for_daly_nettrde_qty"`
	LimitExhRt         string `json:"limit_exh_rt"`
}

// GetStockInstitutionTradingTrend calls Kiwoom ka10045 — 종목별기관매매추이요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetStockInstitutionTradingTrend(ctx context.Context, req *StockInstitutionTradingTrendRequest) (*StockInstitutionTradingTrendResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10045", req)
	if err != nil {
		return nil, err
	}
	var res StockInstitutionTradingTrendResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExecutionStrengthIntradayRequest is the request payload for ka10046 (체결강도추이시간별요청).
type ExecutionStrengthIntradayRequest struct {
	StkCd string `json:"stk_cd"`
}

// ExecutionStrengthIntradayResponse is the response payload for ka10046 (체결강도추이시간별요청).
type ExecutionStrengthIntradayResponse struct {
	CntrStrTm  []ExecutionStrengthIntradayResponseCntrStrTmItem `json:"cntr_str_tm"`
	ReturnCode int                                              `json:"return_code"`
	ReturnMsg  string                                           `json:"return_msg"`
}

// ExecutionStrengthIntradayResponseCntrStrTmItem is a list row in ExecutionStrengthIntradayResponse.
type ExecutionStrengthIntradayResponseCntrStrTmItem struct {
	CntrTm        string `json:"cntr_tm"`
	CurPrc        string `json:"cur_prc"`
	PredPre       string `json:"pred_pre"`
	PredPreSig    string `json:"pred_pre_sig"`
	FluRt         string `json:"flu_rt"`
	TrdeQty       string `json:"trde_qty"`
	AccTrdePrica  string `json:"acc_trde_prica"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	CntrStr       string `json:"cntr_str"`
	CntrStrN5min  string `json:"cntr_str_5min"`
	CntrStrN20min string `json:"cntr_str_20min"`
	CntrStrN60min string `json:"cntr_str_60min"`
	StexTp        string `json:"stex_tp"`
}

// GetExecutionStrengthIntraday calls Kiwoom ka10046 — 체결강도추이시간별요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetExecutionStrengthIntraday(ctx context.Context, req *ExecutionStrengthIntradayRequest) (*ExecutionStrengthIntradayResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10046", req)
	if err != nil {
		return nil, err
	}
	var res ExecutionStrengthIntradayResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExecutionStrengthDailyRequest is the request payload for ka10047 (체결강도추이일별요청).
type ExecutionStrengthDailyRequest struct {
	StkCd string `json:"stk_cd"`
}

// ExecutionStrengthDailyResponse is the response payload for ka10047 (체결강도추이일별요청).
type ExecutionStrengthDailyResponse struct {
	CntrStrDaly []ExecutionStrengthDailyResponseCntrStrDalyItem `json:"cntr_str_daly"`
	ReturnCode  int                                             `json:"return_code"`
	ReturnMsg   string                                          `json:"return_msg"`
}

// ExecutionStrengthDailyResponseCntrStrDalyItem is a list row in ExecutionStrengthDailyResponse.
type ExecutionStrengthDailyResponseCntrStrDalyItem struct {
	Dt            string `json:"dt"`
	CurPrc        string `json:"cur_prc"`
	PredPre       string `json:"pred_pre"`
	PredPreSig    string `json:"pred_pre_sig"`
	FluRt         string `json:"flu_rt"`
	TrdeQty       string `json:"trde_qty"`
	AccTrdePrica  string `json:"acc_trde_prica"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	CntrStr       string `json:"cntr_str"`
	CntrStrN5min  string `json:"cntr_str_5min"`
	CntrStrN20min string `json:"cntr_str_20min"`
	CntrStrN60min string `json:"cntr_str_60min"`
}

// GetExecutionStrengthDaily calls Kiwoom ka10047 — 체결강도추이일별요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetExecutionStrengthDaily(ctx context.Context, req *ExecutionStrengthDailyRequest) (*ExecutionStrengthDailyResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10047", req)
	if err != nil {
		return nil, err
	}
	var res ExecutionStrengthDailyResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ELWDailySensitivityRequest is the request payload for ka10048 (ELW일별민감도지표요청).
type ELWDailySensitivityRequest struct {
	StkCd string `json:"stk_cd"`
}

// ELWDailySensitivityResponse is the response payload for ka10048 (ELW일별민감도지표요청).
type ELWDailySensitivityResponse struct {
	ElwdalySnstIx []ELWDailySensitivityResponseElwdalySnstIxItem `json:"elwdaly_snst_ix"`
	ReturnCode    int                                            `json:"return_code"`
	ReturnMsg     string                                         `json:"return_msg"`
}

// ELWDailySensitivityResponseElwdalySnstIxItem is a list row in ELWDailySensitivityResponse.
type ELWDailySensitivityResponseElwdalySnstIxItem struct {
	Dt    string `json:"dt"`
	Iv    string `json:"iv"`
	Delta string `json:"delta"`
	Gam   string `json:"gam"`
	Theta string `json:"theta"`
	Vega  string `json:"vega"`
	Law   string `json:"law"`
	Lp    string `json:"lp"`
}

// GetELWDailySensitivity calls Kiwoom ka10048 — ELW일별민감도지표요청.
// ELW 정보를 확인할 수 있습니다.
func (c *Client) GetELWDailySensitivity(ctx context.Context, req *ELWDailySensitivityRequest) (*ELWDailySensitivityResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/elw", "ka10048", req)
	if err != nil {
		return nil, err
	}
	var res ELWDailySensitivityResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ELWSensitivityRequest is the request payload for ka10050 (ELW민감도지표요청).
type ELWSensitivityRequest struct {
	StkCd string `json:"stk_cd"`
}

// ELWSensitivityResponse is the response payload for ka10050 (ELW민감도지표요청).
type ELWSensitivityResponse struct {
	ElwsnstIxArray []ELWSensitivityResponseElwsnstIxArrayItem `json:"elwsnst_ix_array"`
	ReturnCode     int                                        `json:"return_code"`
	ReturnMsg      string                                     `json:"return_msg"`
}

// ELWSensitivityResponseElwsnstIxArrayItem is a list row in ELWSensitivityResponse.
type ELWSensitivityResponseElwsnstIxArrayItem struct {
	CntrTm        string `json:"cntr_tm"`
	CurPrc        string `json:"cur_prc"`
	ElwtheoryPric string `json:"elwtheory_pric"`
	Iv            string `json:"iv"`
	Delta         string `json:"delta"`
	Gam           string `json:"gam"`
	Theta         string `json:"theta"`
	Vega          string `json:"vega"`
	Law           string `json:"law"`
	Lp            string `json:"lp"`
}

// GetELWSensitivity calls Kiwoom ka10050 — ELW민감도지표요청.
// ELW 정보를 확인할 수 있습니다.
func (c *Client) GetELWSensitivity(ctx context.Context, req *ELWSensitivityRequest) (*ELWSensitivityResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/elw", "ka10050", req)
	if err != nil {
		return nil, err
	}
	var res ELWSensitivityResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SectorInvestorNetBuyRequest is the request payload for ka10051 (업종별투자자순매수요청).
type SectorInvestorNetBuyRequest struct {
	MrktTp   string `json:"mrkt_tp"`
	AmtQtyTp string `json:"amt_qty_tp"`
	BaseDt   string `json:"base_dt"`
	StexTp   string `json:"stex_tp"`
}

// SectorInvestorNetBuyResponse is the response payload for ka10051 (업종별투자자순매수요청).
type SectorInvestorNetBuyResponse struct {
	IndsNetprps []SectorInvestorNetBuyResponseIndsNetprpsItem `json:"inds_netprps"`
	ReturnCode  int                                           `json:"return_code"`
	ReturnMsg   string                                        `json:"return_msg"`
}

// SectorInvestorNetBuyResponseIndsNetprpsItem is a list row in SectorInvestorNetBuyResponse.
type SectorInvestorNetBuyResponseIndsNetprpsItem struct {
	IndsCd                 string `json:"inds_cd"`
	IndsNm                 string `json:"inds_nm"`
	CurPrc                 string `json:"cur_prc"`
	PreSmbol               string `json:"pre_smbol"`
	PredPre                string `json:"pred_pre"`
	FluRt                  string `json:"flu_rt"`
	TrdeQty                string `json:"trde_qty"`
	ScNetprps              string `json:"sc_netprps"`
	InsrncNetprps          string `json:"insrnc_netprps"`
	InvtrtNetprps          string `json:"invtrt_netprps"`
	BankNetprps            string `json:"bank_netprps"`
	JnsinkmNetprps         string `json:"jnsinkm_netprps"`
	EndwNetprps            string `json:"endw_netprps"`
	EtcCorpNetprps         string `json:"etc_corp_netprps"`
	IndNetprps             string `json:"ind_netprps"`
	FrgnrNetprps           string `json:"frgnr_netprps"`
	NativeTrmtFrgnrNetprps string `json:"native_trmt_frgnr_netprps"`
	NatnNetprps            string `json:"natn_netprps"`
	SamoFundNetprps        string `json:"samo_fund_netprps"`
	OrgnNetprps            string `json:"orgn_netprps"`
}

// GetSectorInvestorNetBuy calls Kiwoom ka10051 — 업종별투자자순매수요청.
// 업종 정보를 확인할 수 있습니다.
func (c *Client) GetSectorInvestorNetBuy(ctx context.Context, req *SectorInvestorNetBuyRequest) (*SectorInvestorNetBuyResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/sect", "ka10051", req)
	if err != nil {
		return nil, err
	}
	var res SectorInvestorNetBuyResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// BrokerInstantVolumeRequest is the request payload for ka10052 (거래원순간거래량요청).
type BrokerInstantVolumeRequest struct {
	MmcmCd string `json:"mmcm_cd"`
	StkCd  string `json:"stk_cd"`
	MrktTp string `json:"mrkt_tp"`
	QtyTp  string `json:"qty_tp"`
	PricTp string `json:"pric_tp"`
	StexTp string `json:"stex_tp"`
}

// BrokerInstantVolumeResponse is the response payload for ka10052 (거래원순간거래량요청).
type BrokerInstantVolumeResponse struct {
	TrdeOriMontTrdeQty []BrokerInstantVolumeResponseTrdeOriMontTrdeQtyItem `json:"trde_ori_mont_trde_qty"`
	ReturnCode         int                                                 `json:"return_code"`
	ReturnMsg          string                                              `json:"return_msg"`
}

// BrokerInstantVolumeResponseTrdeOriMontTrdeQtyItem is a list row in BrokerInstantVolumeResponse.
type BrokerInstantVolumeResponseTrdeOriMontTrdeQtyItem struct {
	Tm          string `json:"tm"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	TrdeOriNm   string `json:"trde_ori_nm"`
	Tp          string `json:"tp"`
	MontTrdeQty string `json:"mont_trde_qty"`
	AccNetprps  string `json:"acc_netprps"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
}

// GetBrokerInstantVolume calls Kiwoom ka10052 — 거래원순간거래량요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetBrokerInstantVolume(ctx context.Context, req *BrokerInstantVolumeRequest) (*BrokerInstantVolumeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10052", req)
	if err != nil {
		return nil, err
	}
	var res BrokerInstantVolumeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TodayTopExitBrokerRequest is the request payload for ka10053 (당일상위이탈원요청).
type TodayTopExitBrokerRequest struct {
	StkCd string `json:"stk_cd"`
}

// TodayTopExitBrokerResponse is the response payload for ka10053 (당일상위이탈원요청).
type TodayTopExitBrokerResponse struct {
	TdyUpperScesnOri []TodayTopExitBrokerResponseTdyUpperScesnOriItem `json:"tdy_upper_scesn_ori"`
	ReturnCode       int                                              `json:"return_code"`
	ReturnMsg        string                                           `json:"return_msg"`
}

// TodayTopExitBrokerResponseTdyUpperScesnOriItem is a list row in TodayTopExitBrokerResponse.
type TodayTopExitBrokerResponseTdyUpperScesnOriItem struct {
	SelScesnTm       string `json:"sel_scesn_tm"`
	SellQty          string `json:"sell_qty"`
	SelUpperScesnOri string `json:"sel_upper_scesn_ori"`
	BuyScesnTm       string `json:"buy_scesn_tm"`
	BuyQty           string `json:"buy_qty"`
	BuyUpperScesnOri string `json:"buy_upper_scesn_ori"`
	QryDt            string `json:"qry_dt"`
	QryTm            string `json:"qry_tm"`
}

// GetTodayTopExitBroker calls Kiwoom ka10053 — 당일상위이탈원요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetTodayTopExitBroker(ctx context.Context, req *TodayTopExitBrokerRequest) (*TodayTopExitBrokerResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10053", req)
	if err != nil {
		return nil, err
	}
	var res TodayTopExitBrokerResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// VITriggeredStocksRequest is the request payload for ka10054 (변동성완화장치발동종목요청).
type VITriggeredStocksRequest struct {
	MrktTp       string `json:"mrkt_tp"`
	BfMkrtTp     string `json:"bf_mkrt_tp"`
	StkCd        string `json:"stk_cd"`
	MotnTp       string `json:"motn_tp"`
	SkipStk      string `json:"skip_stk"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	MinTrdeQty   string `json:"min_trde_qty"`
	MaxTrdeQty   string `json:"max_trde_qty"`
	TrdePricaTp  string `json:"trde_prica_tp"`
	MinTrdePrica string `json:"min_trde_prica"`
	MaxTrdePrica string `json:"max_trde_prica"`
	MotnDrc      string `json:"motn_drc"`
	StexTp       string `json:"stex_tp"`
}

// VITriggeredStocksResponse is the response payload for ka10054 (변동성완화장치발동종목요청).
type VITriggeredStocksResponse struct {
	MotnStk    []VITriggeredStocksResponseMotnStkItem `json:"motn_stk"`
	ReturnCode int                                    `json:"return_code"`
	ReturnMsg  string                                 `json:"return_msg"`
}

// VITriggeredStocksResponseMotnStkItem is a list row in VITriggeredStocksResponse.
type VITriggeredStocksResponseMotnStkItem struct {
	StkCd            string `json:"stk_cd"`
	StkNm            string `json:"stk_nm"`
	AccTrdeQty       string `json:"acc_trde_qty"`
	MotnPric         string `json:"motn_pric"`
	DynmDisptyRt     string `json:"dynm_dispty_rt"`
	TrdeCntrProcTime string `json:"trde_cntr_proc_time"`
	VirelisTime      string `json:"virelis_time"`
	ViaplcTp         string `json:"viaplc_tp"`
	DynmStdpc        string `json:"dynm_stdpc"`
	StaticStdpc      string `json:"static_stdpc"`
	StaticDisptyRt   string `json:"static_dispty_rt"`
	OpenPricPreFluRt string `json:"open_pric_pre_flu_rt"`
	VimotnCnt        string `json:"vimotn_cnt"`
	StexTp           string `json:"stex_tp"`
}

// GetVITriggeredStocks calls Kiwoom ka10054 — 변동성완화장치발동종목요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetVITriggeredStocks(ctx context.Context, req *VITriggeredStocksRequest) (*VITriggeredStocksResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10054", req)
	if err != nil {
		return nil, err
	}
	var res VITriggeredStocksResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TodayPreviousVolumeRequest is the request payload for ka10055 (당일전일체결량요청).
type TodayPreviousVolumeRequest struct {
	StkCd   string `json:"stk_cd"`
	TdyPred string `json:"tdy_pred"`
}

// TodayPreviousVolumeResponse is the response payload for ka10055 (당일전일체결량요청).
type TodayPreviousVolumeResponse struct {
	TdyPredCntrQty []TodayPreviousVolumeResponseTdyPredCntrQtyItem `json:"tdy_pred_cntr_qty"`
	ReturnCode     int                                             `json:"return_code"`
	ReturnMsg      string                                          `json:"return_msg"`
}

// TodayPreviousVolumeResponseTdyPredCntrQtyItem is a list row in TodayPreviousVolumeResponse.
type TodayPreviousVolumeResponseTdyPredCntrQtyItem struct {
	CntrTm       string `json:"cntr_tm"`
	CntrPric     string `json:"cntr_pric"`
	PredPreSig   string `json:"pred_pre_sig"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	CntrQty      string `json:"cntr_qty"`
	AccTrdeQty   string `json:"acc_trde_qty"`
	AccTrdePrica string `json:"acc_trde_prica"`
}

// GetTodayPreviousVolume calls Kiwoom ka10055 — 당일전일체결량요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetTodayPreviousVolume(ctx context.Context, req *TodayPreviousVolumeRequest) (*TodayPreviousVolumeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10055", req)
	if err != nil {
		return nil, err
	}
	var res TodayPreviousVolumeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// InvestorDailyTradingStocksRequest is the request payload for ka10058 (투자자별일별매매종목요청).
type InvestorDailyTradingStocksRequest struct {
	StrtDt  string `json:"strt_dt"`
	EndDt   string `json:"end_dt"`
	TrdeTp  string `json:"trde_tp"`
	MrktTp  string `json:"mrkt_tp"`
	InvsrTp string `json:"invsr_tp"`
	StexTp  string `json:"stex_tp"`
}

// InvestorDailyTradingStocksResponse is the response payload for ka10058 (투자자별일별매매종목요청).
type InvestorDailyTradingStocksResponse struct {
	InvsrDalyTrdeStk []InvestorDailyTradingStocksResponseInvsrDalyTrdeStkItem `json:"invsr_daly_trde_stk"`
	ReturnCode       int                                                      `json:"return_code"`
	ReturnMsg        string                                                   `json:"return_msg"`
}

// InvestorDailyTradingStocksResponseInvsrDalyTrdeStkItem is a list row in InvestorDailyTradingStocksResponse.
type InvestorDailyTradingStocksResponseInvsrDalyTrdeStkItem struct {
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	NetslmtQty  string `json:"netslmt_qty"`
	NetslmtAmt  string `json:"netslmt_amt"`
	PrsmAvgPric string `json:"prsm_avg_pric"`
	CurPrc      string `json:"cur_prc"`
	PreSig      string `json:"pre_sig"`
	PredPre     string `json:"pred_pre"`
	AvgPricPre  string `json:"avg_pric_pre"`
	PreRt       string `json:"pre_rt"`
	DtTrdeQty   string `json:"dt_trde_qty"`
}

// GetInvestorDailyTradingStocks calls Kiwoom ka10058 — 투자자별일별매매종목요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetInvestorDailyTradingStocks(ctx context.Context, req *InvestorDailyTradingStocksRequest) (*InvestorDailyTradingStocksResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10058", req)
	if err != nil {
		return nil, err
	}
	var res InvestorDailyTradingStocksResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockInvestorInstitutionRequest is the request payload for ka10059 (종목별투자자기관별요청).
type StockInvestorInstitutionRequest struct {
	Dt       string `json:"dt"`
	StkCd    string `json:"stk_cd"`
	AmtQtyTp string `json:"amt_qty_tp"`
	TrdeTp   string `json:"trde_tp"`
	UnitTp   string `json:"unit_tp"`
}

// StockInvestorInstitutionResponse is the response payload for ka10059 (종목별투자자기관별요청).
type StockInvestorInstitutionResponse struct {
	StkInvsrOrgn []StockInvestorInstitutionResponseStkInvsrOrgnItem `json:"stk_invsr_orgn"`
	ReturnCode   int                                                `json:"return_code"`
	ReturnMsg    string                                             `json:"return_msg"`
}

// StockInvestorInstitutionResponseStkInvsrOrgnItem is a list row in StockInvestorInstitutionResponse.
type StockInvestorInstitutionResponseStkInvsrOrgnItem struct {
	Dt           string `json:"dt"`
	CurPrc       string `json:"cur_prc"`
	PreSig       string `json:"pre_sig"`
	PredPre      string `json:"pred_pre"`
	FluRt        string `json:"flu_rt"`
	AccTrdeQty   string `json:"acc_trde_qty"`
	AccTrdePrica string `json:"acc_trde_prica"`
	IndInvsr     string `json:"ind_invsr"`
	FrgnrInvsr   string `json:"frgnr_invsr"`
	Orgn         string `json:"orgn"`
	FnncInvt     string `json:"fnnc_invt"`
	Insrnc       string `json:"insrnc"`
	Invtrt       string `json:"invtrt"`
	EtcFnnc      string `json:"etc_fnnc"`
	Bank         string `json:"bank"`
	PenfndEtc    string `json:"penfnd_etc"`
	SamoFund     string `json:"samo_fund"`
	Natn         string `json:"natn"`
	EtcCorp      string `json:"etc_corp"`
	Natfor       string `json:"natfor"`
}

// GetStockInvestorInstitution calls Kiwoom ka10059 — 종목별투자자기관별요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetStockInvestorInstitution(ctx context.Context, req *StockInvestorInstitutionRequest) (*StockInvestorInstitutionResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10059", req)
	if err != nil {
		return nil, err
	}
	var res StockInvestorInstitutionResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockInvestorInstitutionChartRequest is the request payload for ka10060 (종목별투자자기관별차트요청).
type StockInvestorInstitutionChartRequest struct {
	Dt       string `json:"dt"`
	StkCd    string `json:"stk_cd"`
	AmtQtyTp string `json:"amt_qty_tp"`
	TrdeTp   string `json:"trde_tp"`
	UnitTp   string `json:"unit_tp"`
}

// StockInvestorInstitutionChartResponse is the response payload for ka10060 (종목별투자자기관별차트요청).
type StockInvestorInstitutionChartResponse struct {
	StkInvsrOrgnChart []StockInvestorInstitutionChartResponseStkInvsrOrgnChartItem `json:"stk_invsr_orgn_chart"`
	ReturnCode        int                                                          `json:"return_code"`
	ReturnMsg         string                                                       `json:"return_msg"`
}

// StockInvestorInstitutionChartResponseStkInvsrOrgnChartItem is a list row in StockInvestorInstitutionChartResponse.
type StockInvestorInstitutionChartResponseStkInvsrOrgnChartItem struct {
	Dt           string `json:"dt"`
	CurPrc       string `json:"cur_prc"`
	PredPre      string `json:"pred_pre"`
	AccTrdePrica string `json:"acc_trde_prica"`
	IndInvsr     string `json:"ind_invsr"`
	FrgnrInvsr   string `json:"frgnr_invsr"`
	Orgn         string `json:"orgn"`
	FnncInvt     string `json:"fnnc_invt"`
	Insrnc       string `json:"insrnc"`
	Invtrt       string `json:"invtrt"`
	EtcFnnc      string `json:"etc_fnnc"`
	Bank         string `json:"bank"`
	PenfndEtc    string `json:"penfnd_etc"`
	SamoFund     string `json:"samo_fund"`
	Natn         string `json:"natn"`
	EtcCorp      string `json:"etc_corp"`
	Natfor       string `json:"natfor"`
}

// GetStockInvestorInstitutionChart calls Kiwoom ka10060 — 종목별투자자기관별차트요청.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetStockInvestorInstitutionChart(ctx context.Context, req *StockInvestorInstitutionChartRequest) (*StockInvestorInstitutionChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/chart", "ka10060", req)
	if err != nil {
		return nil, err
	}
	var res StockInvestorInstitutionChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockInvestorInstitutionTotalRequest is the request payload for ka10061 (종목별투자자기관별합계요청).
type StockInvestorInstitutionTotalRequest struct {
	StkCd    string `json:"stk_cd"`
	StrtDt   string `json:"strt_dt"`
	EndDt    string `json:"end_dt"`
	AmtQtyTp string `json:"amt_qty_tp"`
	TrdeTp   string `json:"trde_tp"`
	UnitTp   string `json:"unit_tp"`
}

// StockInvestorInstitutionTotalResponse is the response payload for ka10061 (종목별투자자기관별합계요청).
type StockInvestorInstitutionTotalResponse struct {
	StkInvsrOrgnTot []StockInvestorInstitutionTotalResponseStkInvsrOrgnTotItem `json:"stk_invsr_orgn_tot"`
	ReturnCode      int                                                        `json:"return_code"`
	ReturnMsg       string                                                     `json:"return_msg"`
}

// StockInvestorInstitutionTotalResponseStkInvsrOrgnTotItem is a list row in StockInvestorInstitutionTotalResponse.
type StockInvestorInstitutionTotalResponseStkInvsrOrgnTotItem struct {
	IndInvsr   string `json:"ind_invsr"`
	FrgnrInvsr string `json:"frgnr_invsr"`
	Orgn       string `json:"orgn"`
	FnncInvt   string `json:"fnnc_invt"`
	Insrnc     string `json:"insrnc"`
	Invtrt     string `json:"invtrt"`
	EtcFnnc    string `json:"etc_fnnc"`
	Bank       string `json:"bank"`
	PenfndEtc  string `json:"penfnd_etc"`
	SamoFund   string `json:"samo_fund"`
	Natn       string `json:"natn"`
	EtcCorp    string `json:"etc_corp"`
	Natfor     string `json:"natfor"`
}

// GetStockInvestorInstitutionTotal calls Kiwoom ka10061 — 종목별투자자기관별합계요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetStockInvestorInstitutionTotal(ctx context.Context, req *StockInvestorInstitutionTotalRequest) (*StockInvestorInstitutionTotalResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10061", req)
	if err != nil {
		return nil, err
	}
	var res StockInvestorInstitutionTotalResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SameNetBuyRankRequest is the request payload for ka10062 (동일순매매순위요청).
type SameNetBuyRankRequest struct {
	StrtDt  string `json:"strt_dt"`
	EndDt   string `json:"end_dt"`
	MrktTp  string `json:"mrkt_tp"`
	TrdeTp  string `json:"trde_tp"`
	SortCnd string `json:"sort_cnd"`
	UnitTp  string `json:"unit_tp"`
	StexTp  string `json:"stex_tp"`
}

// SameNetBuyRankResponse is the response payload for ka10062 (동일순매매순위요청).
type SameNetBuyRankResponse struct {
	EqlNettrdeRank []SameNetBuyRankResponseEqlNettrdeRankItem `json:"eql_nettrde_rank"`
	ReturnCode     int                                        `json:"return_code"`
	ReturnMsg      string                                     `json:"return_msg"`
}

// SameNetBuyRankResponseEqlNettrdeRankItem is a list row in SameNetBuyRankResponse.
type SameNetBuyRankResponseEqlNettrdeRankItem struct {
	StkCd              string `json:"stk_cd"`
	Rank               string `json:"rank"`
	StkNm              string `json:"stk_nm"`
	CurPrc             string `json:"cur_prc"`
	PreSig             string `json:"pre_sig"`
	PredPre            string `json:"pred_pre"`
	FluRt              string `json:"flu_rt"`
	AccTrdeQty         string `json:"acc_trde_qty"`
	OrgnNettrdeQty     string `json:"orgn_nettrde_qty"`
	OrgnNettrdeAmt     string `json:"orgn_nettrde_amt"`
	OrgnNettrdeAvgPric string `json:"orgn_nettrde_avg_pric"`
	ForNettrdeQty      string `json:"for_nettrde_qty"`
	ForNettrdeAmt      string `json:"for_nettrde_amt"`
	ForNettrdeAvgPric  string `json:"for_nettrde_avg_pric"`
	NettrdeQty         string `json:"nettrde_qty"`
	NettrdeAmt         string `json:"nettrde_amt"`
}

// GetSameNetBuyRank calls Kiwoom ka10062 — 동일순매매순위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetSameNetBuyRank(ctx context.Context, req *SameNetBuyRankRequest) (*SameNetBuyRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10062", req)
	if err != nil {
		return nil, err
	}
	var res SameNetBuyRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// IntradayInvestorTradingRequest is the request payload for ka10063 (장중투자자별매매요청).
type IntradayInvestorTradingRequest struct {
	MrktTp        string `json:"mrkt_tp"`
	AmtQtyTp      string `json:"amt_qty_tp"`
	Invsr         string `json:"invsr"`
	FrgnAll       string `json:"frgn_all"`
	SmtmNetprpsTp string `json:"smtm_netprps_tp"`
	StexTp        string `json:"stex_tp"`
}

// IntradayInvestorTradingResponse is the response payload for ka10063 (장중투자자별매매요청).
type IntradayInvestorTradingResponse struct {
	OpmrInvsrTrde []IntradayInvestorTradingResponseOpmrInvsrTrdeItem `json:"opmr_invsr_trde"`
	ReturnCode    int                                                `json:"return_code"`
	ReturnMsg     string                                             `json:"return_msg"`
}

// IntradayInvestorTradingResponseOpmrInvsrTrdeItem is a list row in IntradayInvestorTradingResponse.
type IntradayInvestorTradingResponseOpmrInvsrTrdeItem struct {
	StkCd             string `json:"stk_cd"`
	StkNm             string `json:"stk_nm"`
	CurPrc            string `json:"cur_prc"`
	PreSig            string `json:"pre_sig"`
	PredPre           string `json:"pred_pre"`
	FluRt             string `json:"flu_rt"`
	AccTrdeQty        string `json:"acc_trde_qty"`
	NetprpsAmt        string `json:"netprps_amt"`
	PrevNetprpsAmt    string `json:"prev_netprps_amt"`
	BuyAmt            string `json:"buy_amt"`
	NetprpsAmtIrds    string `json:"netprps_amt_irds"`
	BuyAmtIrds        string `json:"buy_amt_irds"`
	SellAmt           string `json:"sell_amt"`
	SellAmtIrds       string `json:"sell_amt_irds"`
	NetprpsQty        string `json:"netprps_qty"`
	PrevPotNetprpsQty string `json:"prev_pot_netprps_qty"`
	NetprpsIrds       string `json:"netprps_irds"`
	BuyQty            string `json:"buy_qty"`
	BuyQtyIrds        string `json:"buy_qty_irds"`
	SellQty           string `json:"sell_qty"`
	SellQtyIrds       string `json:"sell_qty_irds"`
}

// GetIntradayInvestorTrading calls Kiwoom ka10063 — 장중투자자별매매요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetIntradayInvestorTrading(ctx context.Context, req *IntradayInvestorTradingRequest) (*IntradayInvestorTradingResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10063", req)
	if err != nil {
		return nil, err
	}
	var res IntradayInvestorTradingResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// IntradayInvestorTradingChartRequest is the request payload for ka10064 (장중투자자별매매차트요청).
type IntradayInvestorTradingChartRequest struct {
	MrktTp   string `json:"mrkt_tp"`
	AmtQtyTp string `json:"amt_qty_tp"`
	TrdeTp   string `json:"trde_tp"`
	StkCd    string `json:"stk_cd"`
}

// IntradayInvestorTradingChartResponse is the response payload for ka10064 (장중투자자별매매차트요청).
type IntradayInvestorTradingChartResponse struct {
	OpmrInvsrTrdeChart []IntradayInvestorTradingChartResponseOpmrInvsrTrdeChartItem `json:"opmr_invsr_trde_chart"`
	ReturnCode         int                                                          `json:"return_code"`
	ReturnMsg          string                                                       `json:"return_msg"`
}

// IntradayInvestorTradingChartResponseOpmrInvsrTrdeChartItem is a list row in IntradayInvestorTradingChartResponse.
type IntradayInvestorTradingChartResponseOpmrInvsrTrdeChartItem struct {
	Tm         string `json:"tm"`
	FrgnrInvsr string `json:"frgnr_invsr"`
	Orgn       string `json:"orgn"`
	Invtrt     string `json:"invtrt"`
	Insrnc     string `json:"insrnc"`
	Bank       string `json:"bank"`
	PenfndEtc  string `json:"penfnd_etc"`
	EtcCorp    string `json:"etc_corp"`
	Natn       string `json:"natn"`
}

// GetIntradayInvestorTradingChart calls Kiwoom ka10064 — 장중투자자별매매차트요청.
// 차트 정보를 확인할 수 있습니다.
func (c *Client) GetIntradayInvestorTradingChart(ctx context.Context, req *IntradayInvestorTradingChartRequest) (*IntradayInvestorTradingChartResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/chart", "ka10064", req)
	if err != nil {
		return nil, err
	}
	var res IntradayInvestorTradingChartResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// IntradayInvestorTradingRankRequest is the request payload for ka10065 (장중투자자별매매상위요청).
type IntradayInvestorTradingRankRequest struct {
	TrdeTp   string `json:"trde_tp"`
	MrktTp   string `json:"mrkt_tp"`
	OrgnTp   string `json:"orgn_tp"`
	AmtQtyTp string `json:"amt_qty_tp"`
}

// IntradayInvestorTradingRankResponse is the response payload for ka10065 (장중투자자별매매상위요청).
type IntradayInvestorTradingRankResponse struct {
	OpmrInvsrTrdeUpper []IntradayInvestorTradingRankResponseOpmrInvsrTrdeUpperItem `json:"opmr_invsr_trde_upper"`
	ReturnCode         int                                                         `json:"return_code"`
	ReturnMsg          string                                                      `json:"return_msg"`
}

// IntradayInvestorTradingRankResponseOpmrInvsrTrdeUpperItem is a list row in IntradayInvestorTradingRankResponse.
type IntradayInvestorTradingRankResponseOpmrInvsrTrdeUpperItem struct {
	StkCd   string `json:"stk_cd"`
	StkNm   string `json:"stk_nm"`
	SelQty  string `json:"sel_qty"`
	BuyQty  string `json:"buy_qty"`
	Netslmt string `json:"netslmt"`
}

// GetIntradayInvestorTradingRank calls Kiwoom ka10065 — 장중투자자별매매상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetIntradayInvestorTradingRank(ctx context.Context, req *IntradayInvestorTradingRankRequest) (*IntradayInvestorTradingRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10065", req)
	if err != nil {
		return nil, err
	}
	var res IntradayInvestorTradingRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AfterCloseInvestorTradingRequest is the request payload for ka10066 (장마감후투자자별매매요청).
type AfterCloseInvestorTradingRequest struct {
	MrktTp   string `json:"mrkt_tp"`
	AmtQtyTp string `json:"amt_qty_tp"`
	TrdeTp   string `json:"trde_tp"`
	StexTp   string `json:"stex_tp"`
}

// AfterCloseInvestorTradingResponse is the response payload for ka10066 (장마감후투자자별매매요청).
type AfterCloseInvestorTradingResponse struct {
	OpafInvsrTrde []AfterCloseInvestorTradingResponseOpafInvsrTrdeItem `json:"opaf_invsr_trde"`
	ReturnCode    int                                                  `json:"return_code"`
	ReturnMsg     string                                               `json:"return_msg"`
}

// AfterCloseInvestorTradingResponseOpafInvsrTrdeItem is a list row in AfterCloseInvestorTradingResponse.
type AfterCloseInvestorTradingResponseOpafInvsrTrdeItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PreSig     string `json:"pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	TrdeQty    string `json:"trde_qty"`
	IndInvsr   string `json:"ind_invsr"`
	FrgnrInvsr string `json:"frgnr_invsr"`
	Orgn       string `json:"orgn"`
	FnncInvt   string `json:"fnnc_invt"`
	Insrnc     string `json:"insrnc"`
	Invtrt     string `json:"invtrt"`
	EtcFnnc    string `json:"etc_fnnc"`
	Bank       string `json:"bank"`
	PenfndEtc  string `json:"penfnd_etc"`
	SamoFund   string `json:"samo_fund"`
	Natn       string `json:"natn"`
	EtcCorp    string `json:"etc_corp"`
}

// GetAfterCloseInvestorTrading calls Kiwoom ka10066 — 장마감후투자자별매매요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetAfterCloseInvestorTrading(ctx context.Context, req *AfterCloseInvestorTradingRequest) (*AfterCloseInvestorTradingResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10066", req)
	if err != nil {
		return nil, err
	}
	var res AfterCloseInvestorTradingResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SecuritiesLendingTrendRequest is the request payload for ka10068 (대차거래추이요청).
type SecuritiesLendingTrendRequest struct {
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
	AllTp  string `json:"all_tp"`
}

// SecuritiesLendingTrendResponse is the response payload for ka10068 (대차거래추이요청).
type SecuritiesLendingTrendResponse struct {
	DbrtTrdeTrnsn []SecuritiesLendingTrendResponseDbrtTrdeTrnsnItem `json:"dbrt_trde_trnsn"`
	ReturnCode    int                                               `json:"return_code"`
	ReturnMsg     string                                            `json:"return_msg"`
}

// SecuritiesLendingTrendResponseDbrtTrdeTrnsnItem is a list row in SecuritiesLendingTrendResponse.
type SecuritiesLendingTrendResponseDbrtTrdeTrnsnItem struct {
	Dt              string `json:"dt"`
	DbrtTrdeCntrcnt string `json:"dbrt_trde_cntrcnt"`
	DbrtTrdeRpy     string `json:"dbrt_trde_rpy"`
	DbrtTrdeIrds    string `json:"dbrt_trde_irds"`
	Rmnd            string `json:"rmnd"`
	RemnAmt         string `json:"remn_amt"`
}

// GetSecuritiesLendingTrend calls Kiwoom ka10068 — 대차거래추이요청.
// 대차 거래 정보를 확인할 수 있습니다.
func (c *Client) GetSecuritiesLendingTrend(ctx context.Context, req *SecuritiesLendingTrendRequest) (*SecuritiesLendingTrendResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/slb", "ka10068", req)
	if err != nil {
		return nil, err
	}
	var res SecuritiesLendingTrendResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SecuritiesLendingTop10Request is the request payload for ka10069 (대차거래상위10종목요청).
type SecuritiesLendingTop10Request struct {
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
	MrktTp string `json:"mrkt_tp"`
}

// SecuritiesLendingTop10Response is the response payload for ka10069 (대차거래상위10종목요청).
type SecuritiesLendingTop10Response struct {
	DbrtTrdeCntrcntSum  string                                                  `json:"dbrt_trde_cntrcnt_sum"`
	DbrtTrdeRpySum      string                                                  `json:"dbrt_trde_rpy_sum"`
	RmndSum             string                                                  `json:"rmnd_sum"`
	RemnAmtSum          string                                                  `json:"remn_amt_sum"`
	DbrtTrdeCntrcntRt   string                                                  `json:"dbrt_trde_cntrcnt_rt"`
	DbrtTrdeRpyRt       string                                                  `json:"dbrt_trde_rpy_rt"`
	RmndRt              string                                                  `json:"rmnd_rt"`
	RemnAmtRt           string                                                  `json:"remn_amt_rt"`
	DbrtTrdeUpperN10stk []SecuritiesLendingTop10ResponseDbrtTrdeUpperN10stkItem `json:"dbrt_trde_upper_10stk"`
	ReturnCode          int                                                     `json:"return_code"`
	ReturnMsg           string                                                  `json:"return_msg"`
}

// SecuritiesLendingTop10ResponseDbrtTrdeUpperN10stkItem is a list row in SecuritiesLendingTop10Response.
type SecuritiesLendingTop10ResponseDbrtTrdeUpperN10stkItem struct {
	StkNm           string `json:"stk_nm"`
	StkCd           string `json:"stk_cd"`
	DbrtTrdeCntrcnt string `json:"dbrt_trde_cntrcnt"`
	DbrtTrdeRpy     string `json:"dbrt_trde_rpy"`
	Rmnd            string `json:"rmnd"`
	RemnAmt         string `json:"remn_amt"`
}

// GetSecuritiesLendingTop10 calls Kiwoom ka10069 — 대차거래상위10종목요청.
// 대차 거래 정보를 확인할 수 있습니다.
func (c *Client) GetSecuritiesLendingTop10(ctx context.Context, req *SecuritiesLendingTop10Request) (*SecuritiesLendingTop10Response, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/slb", "ka10069", req)
	if err != nil {
		return nil, err
	}
	var res SecuritiesLendingTop10Response
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyStockRealizedPLByDateRequest is the request payload for ka10072 (일자별종목별실현손익요청_일자).
type DailyStockRealizedPLByDateRequest struct {
	StkCd  string `json:"stk_cd"`
	StrtDt string `json:"strt_dt"`
}

// DailyStockRealizedPLByDateResponse is the response payload for ka10072 (일자별종목별실현손익요청_일자).
type DailyStockRealizedPLByDateResponse struct {
	DtStkDivRlztPl []DailyStockRealizedPLByDateResponseDtStkDivRlztPlItem `json:"dt_stk_div_rlzt_pl"`
	ReturnCode     int                                                    `json:"return_code"`
	ReturnMsg      string                                                 `json:"return_msg"`
}

// DailyStockRealizedPLByDateResponseDtStkDivRlztPlItem is a list row in DailyStockRealizedPLByDateResponse.
type DailyStockRealizedPLByDateResponseDtStkDivRlztPlItem struct {
	StkNm       string `json:"stk_nm"`
	CntrQty     string `json:"cntr_qty"`
	BuyUv       string `json:"buy_uv"`
	CntrPric    string `json:"cntr_pric"`
	TdySelPl    string `json:"tdy_sel_pl"`
	PlRt        string `json:"pl_rt"`
	StkCd       string `json:"stk_cd"`
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	TdyTrdeTax  string `json:"tdy_trde_tax"`
	WthdAlowa   string `json:"wthd_alowa"`
	LoanDt      string `json:"loan_dt"`
	CrdTp       string `json:"crd_tp"`
	StkCdN1     string `json:"stk_cd_1"`
	TdySelPlN1  string `json:"tdy_sel_pl_1"`
}

// GetDailyStockRealizedPLByDate calls Kiwoom ka10072 — 일자별종목별실현손익요청_일자.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetDailyStockRealizedPLByDate(ctx context.Context, req *DailyStockRealizedPLByDateRequest) (*DailyStockRealizedPLByDateResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10072", req)
	if err != nil {
		return nil, err
	}
	var res DailyStockRealizedPLByDateResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyStockRealizedPLByPeriodRequest is the request payload for ka10073 (일자별종목별실현손익요청_기간).
type DailyStockRealizedPLByPeriodRequest struct {
	StkCd  string `json:"stk_cd"`
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
}

// DailyStockRealizedPLByPeriodResponse is the response payload for ka10073 (일자별종목별실현손익요청_기간).
type DailyStockRealizedPLByPeriodResponse struct {
	DtStkRlztPl []DailyStockRealizedPLByPeriodResponseDtStkRlztPlItem `json:"dt_stk_rlzt_pl"`
	ReturnCode  int                                                   `json:"return_code"`
	ReturnMsg   string                                                `json:"return_msg"`
}

// DailyStockRealizedPLByPeriodResponseDtStkRlztPlItem is a list row in DailyStockRealizedPLByPeriodResponse.
type DailyStockRealizedPLByPeriodResponseDtStkRlztPlItem struct {
	Dt            string `json:"dt"`
	TdyHtsselCmsn string `json:"tdy_htssel_cmsn"`
	StkNm         string `json:"stk_nm"`
	CntrQty       string `json:"cntr_qty"`
	BuyUv         string `json:"buy_uv"`
	CntrPric      string `json:"cntr_pric"`
	TdySelPl      string `json:"tdy_sel_pl"`
	PlRt          string `json:"pl_rt"`
	StkCd         string `json:"stk_cd"`
	TdyTrdeCmsn   string `json:"tdy_trde_cmsn"`
	TdyTrdeTax    string `json:"tdy_trde_tax"`
	WthdAlowa     string `json:"wthd_alowa"`
	LoanDt        string `json:"loan_dt"`
	CrdTp         string `json:"crd_tp"`
}

// GetDailyStockRealizedPLByPeriod calls Kiwoom ka10073 — 일자별종목별실현손익요청_기간.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetDailyStockRealizedPLByPeriod(ctx context.Context, req *DailyStockRealizedPLByPeriodRequest) (*DailyStockRealizedPLByPeriodResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10073", req)
	if err != nil {
		return nil, err
	}
	var res DailyStockRealizedPLByPeriodResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyRealizedPLRequest is the request payload for ka10074 (일자별실현손익요청).
type DailyRealizedPLRequest struct {
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
}

// DailyRealizedPLResponse is the response payload for ka10074 (일자별실현손익요청).
type DailyRealizedPLResponse struct {
	TotBuyAmt  string                                `json:"tot_buy_amt"`
	TotSellAmt string                                `json:"tot_sell_amt"`
	RlztPl     string                                `json:"rlzt_pl"`
	TrdeCmsn   string                                `json:"trde_cmsn"`
	TrdeTax    string                                `json:"trde_tax"`
	DtRlztPl   []DailyRealizedPLResponseDtRlztPlItem `json:"dt_rlzt_pl"`
	ReturnCode int                                   `json:"return_code"`
	ReturnMsg  string                                `json:"return_msg"`
}

// DailyRealizedPLResponseDtRlztPlItem is a list row in DailyRealizedPLResponse.
type DailyRealizedPLResponseDtRlztPlItem struct {
	Dt          string `json:"dt"`
	BuyAmt      string `json:"buy_amt"`
	SellAmt     string `json:"sell_amt"`
	TdySelPl    string `json:"tdy_sel_pl"`
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	TdyTrdeTax  string `json:"tdy_trde_tax"`
}

// GetDailyRealizedPL calls Kiwoom ka10074 — 일자별실현손익요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetDailyRealizedPL(ctx context.Context, req *DailyRealizedPLRequest) (*DailyRealizedPLResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10074", req)
	if err != nil {
		return nil, err
	}
	var res DailyRealizedPLResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// OpenOrdersRequest is the request payload for ka10075 (미체결요청).
type OpenOrdersRequest struct {
	AllStkTp string `json:"all_stk_tp"`
	TrdeTp   string `json:"trde_tp"`
	StkCd    string `json:"stk_cd"`
	StexTp   string `json:"stex_tp"`
}

// OpenOrdersResponse is the response payload for ka10075 (미체결요청).
type OpenOrdersResponse struct {
	Oso        []OpenOrdersResponseOsoItem `json:"oso"`
	ReturnCode int                         `json:"return_code"`
	ReturnMsg  string                      `json:"return_msg"`
}

// OpenOrdersResponseOsoItem is a list row in OpenOrdersResponse.
type OpenOrdersResponseOsoItem struct {
	AcntNo       string `json:"acnt_no"`
	OrdNo        string `json:"ord_no"`
	MangEmpno    string `json:"mang_empno"`
	StkCd        string `json:"stk_cd"`
	TskTp        string `json:"tsk_tp"`
	OrdStt       string `json:"ord_stt"`
	StkNm        string `json:"stk_nm"`
	OrdQty       string `json:"ord_qty"`
	OrdPric      string `json:"ord_pric"`
	OsoQty       string `json:"oso_qty"`
	CntrTotAmt   string `json:"cntr_tot_amt"`
	OrigOrdNo    string `json:"orig_ord_no"`
	IoTpNm       string `json:"io_tp_nm"`
	TrdeTp       string `json:"trde_tp"`
	Tm           string `json:"tm"`
	CntrNo       string `json:"cntr_no"`
	CntrPric     string `json:"cntr_pric"`
	CntrQty      string `json:"cntr_qty"`
	CurPrc       string `json:"cur_prc"`
	SelBid       string `json:"sel_bid"`
	BuyBid       string `json:"buy_bid"`
	UnitCntrPric string `json:"unit_cntr_pric"`
	UnitCntrQty  string `json:"unit_cntr_qty"`
	TdyTrdeCmsn  string `json:"tdy_trde_cmsn"`
	TdyTrdeTax   string `json:"tdy_trde_tax"`
	IndInvsr     string `json:"ind_invsr"`
	StexTp       string `json:"stex_tp"`
	StexTpTxt    string `json:"stex_tp_txt"`
	SorYn        string `json:"sor_yn"`
	StopPric     string `json:"stop_pric"`
}

// GetOpenOrders calls Kiwoom ka10075 — 미체결요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetOpenOrders(ctx context.Context, req *OpenOrdersRequest) (*OpenOrdersResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10075", req)
	if err != nil {
		return nil, err
	}
	var res OpenOrdersResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExecutionsRequest is the request payload for ka10076 (체결요청).
type ExecutionsRequest struct {
	StkCd  string `json:"stk_cd"`
	QryTp  string `json:"qry_tp"`
	SellTp string `json:"sell_tp"`
	OrdNo  string `json:"ord_no"`
	StexTp string `json:"stex_tp"`
}

// ExecutionsResponse is the response payload for ka10076 (체결요청).
type ExecutionsResponse struct {
	Cntr       []ExecutionsResponseCntrItem `json:"cntr"`
	ReturnCode int                          `json:"return_code"`
	ReturnMsg  string                       `json:"return_msg"`
}

// ExecutionsResponseCntrItem is a list row in ExecutionsResponse.
type ExecutionsResponseCntrItem struct {
	OrdNo       string `json:"ord_no"`
	StkNm       string `json:"stk_nm"`
	IoTpNm      string `json:"io_tp_nm"`
	OrdPric     string `json:"ord_pric"`
	OrdQty      string `json:"ord_qty"`
	CntrPric    string `json:"cntr_pric"`
	CntrQty     string `json:"cntr_qty"`
	OsoQty      string `json:"oso_qty"`
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	TdyTrdeTax  string `json:"tdy_trde_tax"`
	OrdStt      string `json:"ord_stt"`
	TrdeTp      string `json:"trde_tp"`
	OrigOrdNo   string `json:"orig_ord_no"`
	OrdTm       string `json:"ord_tm"`
	StkCd       string `json:"stk_cd"`
	StexTp      string `json:"stex_tp"`
	StexTpTxt   string `json:"stex_tp_txt"`
	SorYn       string `json:"sor_yn"`
	StopPric    string `json:"stop_pric"`
}

// GetExecutions calls Kiwoom ka10076 — 체결요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetExecutions(ctx context.Context, req *ExecutionsRequest) (*ExecutionsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10076", req)
	if err != nil {
		return nil, err
	}
	var res ExecutionsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TodayRealizedPLDetailRequest is the request payload for ka10077 (당일실현손익상세요청).
type TodayRealizedPLDetailRequest struct {
	StkCd string `json:"stk_cd"`
}

// TodayRealizedPLDetailResponse is the response payload for ka10077 (당일실현손익상세요청).
type TodayRealizedPLDetailResponse struct {
	TdyRlztPl    string                                          `json:"tdy_rlzt_pl"`
	TdyRlztPlDtl []TodayRealizedPLDetailResponseTdyRlztPlDtlItem `json:"tdy_rlzt_pl_dtl"`
	ReturnCode   int                                             `json:"return_code"`
	ReturnMsg    string                                          `json:"return_msg"`
}

// TodayRealizedPLDetailResponseTdyRlztPlDtlItem is a list row in TodayRealizedPLDetailResponse.
type TodayRealizedPLDetailResponseTdyRlztPlDtlItem struct {
	StkNm       string `json:"stk_nm"`
	CntrQty     string `json:"cntr_qty"`
	BuyUv       string `json:"buy_uv"`
	CntrPric    string `json:"cntr_pric"`
	TdySelPl    string `json:"tdy_sel_pl"`
	PlRt        string `json:"pl_rt"`
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	TdyTrdeTax  string `json:"tdy_trde_tax"`
	StkCd       string `json:"stk_cd"`
}

// GetTodayRealizedPLDetail calls Kiwoom ka10077 — 당일실현손익상세요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetTodayRealizedPLDetail(ctx context.Context, req *TodayRealizedPLDetailRequest) (*TodayRealizedPLDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10077", req)
	if err != nil {
		return nil, err
	}
	var res TodayRealizedPLDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SecuritiesFirmStockTradingTrendRequest is the request payload for ka10078 (증권사별종목매매동향요청).
type SecuritiesFirmStockTradingTrendRequest struct {
	MmcmCd string `json:"mmcm_cd"`
	StkCd  string `json:"stk_cd"`
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
}

// SecuritiesFirmStockTradingTrendResponse is the response payload for ka10078 (증권사별종목매매동향요청).
type SecuritiesFirmStockTradingTrendResponse struct {
	SecStkTrdeTrend []SecuritiesFirmStockTradingTrendResponseSecStkTrdeTrendItem `json:"sec_stk_trde_trend"`
	ReturnCode      int                                                          `json:"return_code"`
	ReturnMsg       string                                                       `json:"return_msg"`
}

// SecuritiesFirmStockTradingTrendResponseSecStkTrdeTrendItem is a list row in SecuritiesFirmStockTradingTrendResponse.
type SecuritiesFirmStockTradingTrendResponseSecStkTrdeTrendItem struct {
	Dt         string `json:"dt"`
	CurPrc     string `json:"cur_prc"`
	PreSig     string `json:"pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	AccTrdeQty string `json:"acc_trde_qty"`
	NetprpsQty string `json:"netprps_qty"`
	BuyQty     string `json:"buy_qty"`
	SellQty    string `json:"sell_qty"`
}

// GetSecuritiesFirmStockTradingTrend calls Kiwoom ka10078 — 증권사별종목매매동향요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetSecuritiesFirmStockTradingTrend(ctx context.Context, req *SecuritiesFirmStockTradingTrendRequest) (*SecuritiesFirmStockTradingTrendResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10078", req)
	if err != nil {
		return nil, err
	}
	var res SecuritiesFirmStockTradingTrendResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TodayPreviousExecutionRequest is the request payload for ka10084 (당일전일체결요청).
type TodayPreviousExecutionRequest struct {
	StkCd   string `json:"stk_cd"`
	TdyPred string `json:"tdy_pred"`
	TicMin  string `json:"tic_min"`
	Tm      string `json:"tm"`
}

// TodayPreviousExecutionResponse is the response payload for ka10084 (당일전일체결요청).
type TodayPreviousExecutionResponse struct {
	TdyPredCntr []TodayPreviousExecutionResponseTdyPredCntrItem `json:"tdy_pred_cntr"`
	ReturnCode  int                                             `json:"return_code"`
	ReturnMsg   string                                          `json:"return_msg"`
}

// TodayPreviousExecutionResponseTdyPredCntrItem is a list row in TodayPreviousExecutionResponse.
type TodayPreviousExecutionResponseTdyPredCntrItem struct {
	Tm            string `json:"tm"`
	CurPrc        string `json:"cur_prc"`
	PredPre       string `json:"pred_pre"`
	PreRt         string `json:"pre_rt"`
	PriSelBidUnit string `json:"pri_sel_bid_unit"`
	PriBuyBidUnit string `json:"pri_buy_bid_unit"`
	CntrTrdeQty   string `json:"cntr_trde_qty"`
	Sign          string `json:"sign"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	AccTrdePrica  string `json:"acc_trde_prica"`
	CntrStr       string `json:"cntr_str"`
	StexTp        string `json:"stex_tp"`
}

// GetTodayPreviousExecution calls Kiwoom ka10084 — 당일전일체결요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetTodayPreviousExecution(ctx context.Context, req *TodayPreviousExecutionRequest) (*TodayPreviousExecutionResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10084", req)
	if err != nil {
		return nil, err
	}
	var res TodayPreviousExecutionResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AccountReturnRateRequest is the request payload for ka10085 (계좌수익률요청).
type AccountReturnRateRequest struct {
	StexTp string `json:"stex_tp"`
}

// AccountReturnRateResponse is the response payload for ka10085 (계좌수익률요청).
type AccountReturnRateResponse struct {
	AcntPrftRt []AccountReturnRateResponseAcntPrftRtItem `json:"acnt_prft_rt"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// AccountReturnRateResponseAcntPrftRtItem is a list row in AccountReturnRateResponse.
type AccountReturnRateResponseAcntPrftRtItem struct {
	Dt          string `json:"dt"`
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	CurPrc      string `json:"cur_prc"`
	PurPric     string `json:"pur_pric"`
	PurAmt      string `json:"pur_amt"`
	RmndQty     string `json:"rmnd_qty"`
	TdySelPl    string `json:"tdy_sel_pl"`
	TdyTrdeCmsn string `json:"tdy_trde_cmsn"`
	TdyTrdeTax  string `json:"tdy_trde_tax"`
	CrdTp       string `json:"crd_tp"`
	LoanDt      string `json:"loan_dt"`
	SetlRemn    string `json:"setl_remn"`
	ClrnAlowQty string `json:"clrn_alow_qty"`
	CrdAmt      string `json:"crd_amt"`
	CrdInt      string `json:"crd_int"`
	ExprDt      string `json:"expr_dt"`
}

// GetAccountReturnRate calls Kiwoom ka10085 — 계좌수익률요청.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetAccountReturnRate(ctx context.Context, req *AccountReturnRateRequest) (*AccountReturnRateResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10085", req)
	if err != nil {
		return nil, err
	}
	var res AccountReturnRateResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyStockPriceRequest is the request payload for ka10086 (일별주가요청).
type DailyStockPriceRequest struct {
	StkCd  string `json:"stk_cd"`
	QryDt  string `json:"qry_dt"`
	IndcTp string `json:"indc_tp"`
}

// DailyStockPriceResponse is the response payload for ka10086 (일별주가요청).
type DailyStockPriceResponse struct {
	DalyStkpc  []DailyStockPriceResponseDalyStkpcItem `json:"daly_stkpc"`
	ReturnCode int                                    `json:"return_code"`
	ReturnMsg  string                                 `json:"return_msg"`
}

// DailyStockPriceResponseDalyStkpcItem is a list row in DailyStockPriceResponse.
type DailyStockPriceResponseDalyStkpcItem struct {
	Date        string `json:"date"`
	OpenPric    string `json:"open_pric"`
	HighPric    string `json:"high_pric"`
	LowPric     string `json:"low_pric"`
	ClosePric   string `json:"close_pric"`
	PredRt      string `json:"pred_rt"`
	FluRt       string `json:"flu_rt"`
	TrdeQty     string `json:"trde_qty"`
	AmtMn       string `json:"amt_mn"`
	CrdRt       string `json:"crd_rt"`
	Ind         string `json:"ind"`
	Orgn        string `json:"orgn"`
	ForQty      string `json:"for_qty"`
	Frgn        string `json:"frgn"`
	Prm         string `json:"prm"`
	ForRt       string `json:"for_rt"`
	ForPoss     string `json:"for_poss"`
	ForWght     string `json:"for_wght"`
	ForNetprps  string `json:"for_netprps"`
	OrgnNetprps string `json:"orgn_netprps"`
	IndNetprps  string `json:"ind_netprps"`
	CrdRemnRt   string `json:"crd_remn_rt"`
}

// GetDailyStockPrice calls Kiwoom ka10086 — 일별주가요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetDailyStockPrice(ctx context.Context, req *DailyStockPriceRequest) (*DailyStockPriceResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10086", req)
	if err != nil {
		return nil, err
	}
	var res DailyStockPriceResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AfterHoursSinglePriceRequest is the request payload for ka10087 (시간외단일가요청).
type AfterHoursSinglePriceRequest struct {
	StkCd string `json:"stk_cd"`
}

// AfterHoursSinglePriceResponse is the response payload for ka10087 (시간외단일가요청).
type AfterHoursSinglePriceResponse struct {
	BidReqBaseTm             string `json:"bid_req_base_tm"`
	OvtSigpricSelBidJubPreN5 string `json:"ovt_sigpric_sel_bid_jub_pre_5"`
	OvtSigpricSelBidJubPreN4 string `json:"ovt_sigpric_sel_bid_jub_pre_4"`
	OvtSigpricSelBidJubPreN3 string `json:"ovt_sigpric_sel_bid_jub_pre_3"`
	OvtSigpricSelBidJubPreN2 string `json:"ovt_sigpric_sel_bid_jub_pre_2"`
	OvtSigpricSelBidJubPreN1 string `json:"ovt_sigpric_sel_bid_jub_pre_1"`
	OvtSigpricSelBidQtyN5    string `json:"ovt_sigpric_sel_bid_qty_5"`
	OvtSigpricSelBidQtyN4    string `json:"ovt_sigpric_sel_bid_qty_4"`
	OvtSigpricSelBidQtyN3    string `json:"ovt_sigpric_sel_bid_qty_3"`
	OvtSigpricSelBidQtyN2    string `json:"ovt_sigpric_sel_bid_qty_2"`
	OvtSigpricSelBidQtyN1    string `json:"ovt_sigpric_sel_bid_qty_1"`
	OvtSigpricSelBidN5       string `json:"ovt_sigpric_sel_bid_5"`
	OvtSigpricSelBidN4       string `json:"ovt_sigpric_sel_bid_4"`
	OvtSigpricSelBidN3       string `json:"ovt_sigpric_sel_bid_3"`
	OvtSigpricSelBidN2       string `json:"ovt_sigpric_sel_bid_2"`
	OvtSigpricSelBidN1       string `json:"ovt_sigpric_sel_bid_1"`
	OvtSigpricBuyBidN1       string `json:"ovt_sigpric_buy_bid_1"`
	OvtSigpricBuyBidN2       string `json:"ovt_sigpric_buy_bid_2"`
	OvtSigpricBuyBidN3       string `json:"ovt_sigpric_buy_bid_3"`
	OvtSigpricBuyBidN4       string `json:"ovt_sigpric_buy_bid_4"`
	OvtSigpricBuyBidN5       string `json:"ovt_sigpric_buy_bid_5"`
	OvtSigpricBuyBidQtyN1    string `json:"ovt_sigpric_buy_bid_qty_1"`
	OvtSigpricBuyBidQtyN2    string `json:"ovt_sigpric_buy_bid_qty_2"`
	OvtSigpricBuyBidQtyN3    string `json:"ovt_sigpric_buy_bid_qty_3"`
	OvtSigpricBuyBidQtyN4    string `json:"ovt_sigpric_buy_bid_qty_4"`
	OvtSigpricBuyBidQtyN5    string `json:"ovt_sigpric_buy_bid_qty_5"`
	OvtSigpricBuyBidJubPreN1 string `json:"ovt_sigpric_buy_bid_jub_pre_1"`
	OvtSigpricBuyBidJubPreN2 string `json:"ovt_sigpric_buy_bid_jub_pre_2"`
	OvtSigpricBuyBidJubPreN3 string `json:"ovt_sigpric_buy_bid_jub_pre_3"`
	OvtSigpricBuyBidJubPreN4 string `json:"ovt_sigpric_buy_bid_jub_pre_4"`
	OvtSigpricBuyBidJubPreN5 string `json:"ovt_sigpric_buy_bid_jub_pre_5"`
	OvtSigpricSelBidTotReq   string `json:"ovt_sigpric_sel_bid_tot_req"`
	OvtSigpricBuyBidTotReq   string `json:"ovt_sigpric_buy_bid_tot_req"`
	SelBidTotReqJubPre       string `json:"sel_bid_tot_req_jub_pre"`
	SelBidTotReq             string `json:"sel_bid_tot_req"`
	BuyBidTotReq             string `json:"buy_bid_tot_req"`
	BuyBidTotReqJubPre       string `json:"buy_bid_tot_req_jub_pre"`
	OvtSelBidTotReqJubPre    string `json:"ovt_sel_bid_tot_req_jub_pre"`
	OvtSelBidTotReq          string `json:"ovt_sel_bid_tot_req"`
	OvtBuyBidTotReq          string `json:"ovt_buy_bid_tot_req"`
	OvtBuyBidTotReqJubPre    string `json:"ovt_buy_bid_tot_req_jub_pre"`
	OvtSigpricCurPrc         string `json:"ovt_sigpric_cur_prc"`
	OvtSigpricPredPreSig     string `json:"ovt_sigpric_pred_pre_sig"`
	OvtSigpricPredPre        string `json:"ovt_sigpric_pred_pre"`
	OvtSigpricFluRt          string `json:"ovt_sigpric_flu_rt"`
	OvtSigpricAccTrdeQty     string `json:"ovt_sigpric_acc_trde_qty"`
	ReturnCode               int    `json:"return_code"`
	ReturnMsg                string `json:"return_msg"`
}

// GetAfterHoursSinglePrice calls Kiwoom ka10087 — 시간외단일가요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetAfterHoursSinglePrice(ctx context.Context, req *AfterHoursSinglePriceRequest) (*AfterHoursSinglePriceResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10087", req)
	if err != nil {
		return nil, err
	}
	var res AfterHoursSinglePriceResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// OpenOrderSplitDetailRequest is the request payload for ka10088 (미체결 분할주문 상세).
type OpenOrderSplitDetailRequest struct {
	OrdNo string `json:"ord_no"`
}

// OpenOrderSplitDetailResponse is the response payload for ka10088 (미체결 분할주문 상세).
type OpenOrderSplitDetailResponse struct {
	Osop       []OpenOrderSplitDetailResponseOsopItem `json:"osop"`
	ReturnCode int                                    `json:"return_code"`
	ReturnMsg  string                                 `json:"return_msg"`
}

// OpenOrderSplitDetailResponseOsopItem is a list row in OpenOrderSplitDetailResponse.
type OpenOrderSplitDetailResponseOsopItem struct {
	StkCd     string `json:"stk_cd"`
	StkNm     string `json:"stk_nm"`
	OrdNo     string `json:"ord_no"`
	OrdQty    string `json:"ord_qty"`
	OrdPric   string `json:"ord_pric"`
	OsopQty   string `json:"osop_qty"`
	IoTpNm    string `json:"io_tp_nm"`
	TrdeTp    string `json:"trde_tp"`
	SellTp    string `json:"sell_tp"`
	CntrQty   string `json:"cntr_qty"`
	OrdStt    string `json:"ord_stt"`
	CurPrc    string `json:"cur_prc"`
	StexTp    string `json:"stex_tp"`
	StexTpTxt string `json:"stex_tp_txt"`
}

// GetOpenOrderSplitDetail calls Kiwoom ka10088 — 미체결 분할주문 상세.
// 계좌 정보를 확인할 수 있습니다.
func (c *Client) GetOpenOrderSplitDetail(ctx context.Context, req *OpenOrderSplitDetailRequest) (*OpenOrderSplitDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/acnt", "ka10088", req)
	if err != nil {
		return nil, err
	}
	var res OpenOrderSplitDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DesignatedStockInfoRequest is the request payload for ka10095 (지정종목 정보요청).
type DesignatedStockInfoRequest struct {
	StkCd string `json:"stk_cd"`
}

// DesignatedStockInfoResponse is the response payload for ka10095 (지정종목 정보요청).
type DesignatedStockInfoResponse struct {
	AtnStkInfr []DesignatedStockInfoResponseAtnStkInfrItem `json:"atn_stk_infr"`
	ReturnCode int                                         `json:"return_code"`
	ReturnMsg  string                                      `json:"return_msg"`
}

// DesignatedStockInfoResponseAtnStkInfrItem is a list row in DesignatedStockInfoResponse.
type DesignatedStockInfoResponseAtnStkInfrItem struct {
	StkCd          string `json:"stk_cd"`
	StkNm          string `json:"stk_nm"`
	CurPrc         string `json:"cur_prc"`
	BasePric       string `json:"base_pric"`
	PredPre        string `json:"pred_pre"`
	PredPreSig     string `json:"pred_pre_sig"`
	FluRt          string `json:"flu_rt"`
	TrdeQty        string `json:"trde_qty"`
	TrdePrica      string `json:"trde_prica"`
	CntrQty        string `json:"cntr_qty"`
	CntrStr        string `json:"cntr_str"`
	PredTrdeQtyPre string `json:"pred_trde_qty_pre"`
	SelBid         string `json:"sel_bid"`
	BuyBid         string `json:"buy_bid"`
	SelN1thBid     string `json:"sel_1th_bid"`
	SelN2thBid     string `json:"sel_2th_bid"`
	SelN3thBid     string `json:"sel_3th_bid"`
	SelN4thBid     string `json:"sel_4th_bid"`
	SelN5thBid     string `json:"sel_5th_bid"`
	BuyN1thBid     string `json:"buy_1th_bid"`
	BuyN2thBid     string `json:"buy_2th_bid"`
	BuyN3thBid     string `json:"buy_3th_bid"`
	BuyN4thBid     string `json:"buy_4th_bid"`
	BuyN5thBid     string `json:"buy_5th_bid"`
	UplPric        string `json:"upl_pric"`
	LstPric        string `json:"lst_pric"`
	OpenPric       string `json:"open_pric"`
	HighPric       string `json:"high_pric"`
	LowPric        string `json:"low_pric"`
	ClosePric      string `json:"close_pric"`
	CntrTm         string `json:"cntr_tm"`
	ExpCntrPric    string `json:"exp_cntr_pric"`
	ExpCntrQty     string `json:"exp_cntr_qty"`
	Cap            string `json:"cap"`
	Fav            string `json:"fav"`
	Mac            string `json:"mac"`
	Stkcnt         string `json:"stkcnt"`
	BidTm          string `json:"bid_tm"`
	Dt             string `json:"dt"`
	PriSelReq      string `json:"pri_sel_req"`
	PriBuyReq      string `json:"pri_buy_req"`
	PriSelCnt      string `json:"pri_sel_cnt"`
	PriBuyCnt      string `json:"pri_buy_cnt"`
	TotSelReq      string `json:"tot_sel_req"`
	TotBuyReq      string `json:"tot_buy_req"`
	TotSelCnt      string `json:"tot_sel_cnt"`
	TotBuyCnt      string `json:"tot_buy_cnt"`
	Prty           string `json:"prty"`
	Gear           string `json:"gear"`
	PlQutr         string `json:"pl_qutr"`
	CapSupport     string `json:"cap_support"`
	ElwexecPric    string `json:"elwexec_pric"`
	CnvtRt         string `json:"cnvt_rt"`
	ElwexprDt      string `json:"elwexpr_dt"`
	CntrEngg       string `json:"cntr_engg"`
	CntrPredPre    string `json:"cntr_pred_pre"`
	TheoryPric     string `json:"theory_pric"`
	InnrVltl       string `json:"innr_vltl"`
	Delta          string `json:"delta"`
	Gam            string `json:"gam"`
	Theta          string `json:"theta"`
	Vega           string `json:"vega"`
	Law            string `json:"law"`
}

// GetDesignatedStockInfo calls Kiwoom ka10095 — 지정종목 정보요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetDesignatedStockInfo(ctx context.Context, req *DesignatedStockInfoRequest) (*DesignatedStockInfoResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10095", req)
	if err != nil {
		return nil, err
	}
	var res DesignatedStockInfoResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// AfterHoursSinglePriceChangeRankRequest is the request payload for ka10098 (시간외단일가등락율순위요청).
type AfterHoursSinglePriceChangeRankRequest struct {
	MrktTp     string `json:"mrkt_tp"`
	SortBase   string `json:"sort_base"`
	StkCnd     string `json:"stk_cnd"`
	TrdeQtyCnd string `json:"trde_qty_cnd"`
	CrdCnd     string `json:"crd_cnd"`
	TrdePrica  string `json:"trde_prica"`
}

// AfterHoursSinglePriceChangeRankResponse is the response payload for ka10098 (시간외단일가등락율순위요청).
type AfterHoursSinglePriceChangeRankResponse struct {
	OvtSigpricFluRtRank []AfterHoursSinglePriceChangeRankResponseOvtSigpricFluRtRankItem `json:"ovt_sigpric_flu_rt_rank"`
	ReturnCode          int                                                              `json:"return_code"`
	ReturnMsg           string                                                           `json:"return_msg"`
}

// AfterHoursSinglePriceChangeRankResponseOvtSigpricFluRtRankItem is a list row in AfterHoursSinglePriceChangeRankResponse.
type AfterHoursSinglePriceChangeRankResponseOvtSigpricFluRtRankItem struct {
	Rank              string `json:"rank"`
	StkCd             string `json:"stk_cd"`
	StkNm             string `json:"stk_nm"`
	CurPrc            string `json:"cur_prc"`
	PredPreSig        string `json:"pred_pre_sig"`
	PredPre           string `json:"pred_pre"`
	FluRt             string `json:"flu_rt"`
	SelTotReq         string `json:"sel_tot_req"`
	BuyTotReq         string `json:"buy_tot_req"`
	AccTrdeQty        string `json:"acc_trde_qty"`
	AccTrdePrica      string `json:"acc_trde_prica"`
	TdyClosePric      string `json:"tdy_close_pric"`
	TdyClosePricFluRt string `json:"tdy_close_pric_flu_rt"`
}

// GetAfterHoursSinglePriceChangeRank calls Kiwoom ka10098 — 시간외단일가등락율순위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetAfterHoursSinglePriceChangeRank(ctx context.Context, req *AfterHoursSinglePriceChangeRankRequest) (*AfterHoursSinglePriceChangeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10098", req)
	if err != nil {
		return nil, err
	}
	var res AfterHoursSinglePriceChangeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockInfoListRequest is the request payload for ka10099 (종목정보 리스트).
type StockInfoListRequest struct {
	MrktTp string `json:"mrkt_tp"`
}

// StockInfoListResponse is the response payload for ka10099 (종목정보 리스트).
type StockInfoListResponse struct {
	List       []StockInfoListResponseListItem `json:"list"`
	ReturnCode int                             `json:"return_code"`
	ReturnMsg  string                          `json:"return_msg"`
}

// StockInfoListResponseListItem is a list row in StockInfoListResponse.
type StockInfoListResponseListItem struct {
	Code             string `json:"code"`
	Name             string `json:"name"`
	ListCount        string `json:"listCount"`
	AuditInfo        string `json:"auditInfo"`
	RegDay           string `json:"regDay"`
	LastPrice        string `json:"lastPrice"`
	State            string `json:"state"`
	MarketCode       string `json:"marketCode"`
	MarketName       string `json:"marketName"`
	UpName           string `json:"upName"`
	UpSizeName       string `json:"upSizeName"`
	CompanyClassName string `json:"companyClassName"`
	OrderWarning     string `json:"orderWarning"`
	NxtEnable        string `json:"nxtEnable"`
}

// GetStockInfoList calls Kiwoom ka10099 — 종목정보 리스트.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetStockInfoList(ctx context.Context, req *StockInfoListRequest) (*StockInfoListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10099", req)
	if err != nil {
		return nil, err
	}
	var res StockInfoListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockInfoLookupRequest is the request payload for ka10100 (종목정보 조회).
type StockInfoLookupRequest struct {
	StkCd string `json:"stk_cd"`
}

// StockInfoLookupResponse is the response payload for ka10100 (종목정보 조회).
type StockInfoLookupResponse struct {
	Code             string `json:"code"`
	Name             string `json:"name"`
	ListCount        string `json:"listCount"`
	AuditInfo        string `json:"auditInfo"`
	RegDay           string `json:"regDay"`
	LastPrice        string `json:"lastPrice"`
	State            string `json:"state"`
	MarketCode       string `json:"marketCode"`
	MarketName       string `json:"marketName"`
	UpName           string `json:"upName"`
	UpSizeName       string `json:"upSizeName"`
	CompanyClassName string `json:"companyClassName"`
	OrderWarning     string `json:"orderWarning"`
	NxtEnable        string `json:"nxtEnable"`
	ReturnCode       int    `json:"return_code"`
	ReturnMsg        string `json:"return_msg"`
}

// GetStockInfoLookup calls Kiwoom ka10100 — 종목정보 조회.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetStockInfoLookup(ctx context.Context, req *StockInfoLookupRequest) (*StockInfoLookupResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10100", req)
	if err != nil {
		return nil, err
	}
	var res StockInfoLookupResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SectorCodeListRequest is the request payload for ka10101 (업종코드 리스트).
type SectorCodeListRequest struct {
	MrktTp string `json:"mrkt_tp"`
}

// SectorCodeListResponse is the response payload for ka10101 (업종코드 리스트).
type SectorCodeListResponse struct {
	List       []SectorCodeListResponseListItem `json:"list"`
	ReturnCode int                              `json:"return_code"`
	ReturnMsg  string                           `json:"return_msg"`
}

// SectorCodeListResponseListItem is a list row in SectorCodeListResponse.
type SectorCodeListResponseListItem struct {
	MarketCode string `json:"marketCode"`
	Code       string `json:"code"`
	Name       string `json:"name"`
	Group      string `json:"group"`
}

// GetSectorCodeList calls Kiwoom ka10101 — 업종코드 리스트.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetSectorCodeList(ctx context.Context, req *SectorCodeListRequest) (*SectorCodeListResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10101", req)
	if err != nil {
		return nil, err
	}
	var res SectorCodeListResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
