// Code generated by cmd/genapis; DO NOT EDIT.

package kioom

import (
	"context"
	"net/http"
)

// BlockTradeRankRequest is the request payload for ka00190 (대량체결상위).
type BlockTradeRankRequest struct {
	MrktTp              string `json:"mrkt_tp"`
	SortTp              string `json:"sort_tp"`
	CasePricTp          string `json:"case_pric_tp"`
	TrdePricaTp         string `json:"trde_prica_tp"`
	StkTp               string `json:"stk_tp"`
	TrdeQtyTp           string `json:"trde_qty_tp"`
	CrdTp               string `json:"crd_tp"`
	PricTp              string `json:"pric_tp"`
	MacTp               string `json:"mac_tp"`
	PriceCndTp          string `json:"price_cnd_tp"`
	PriceCndMin         string `json:"price_cnd_min"`
	PriceCndMax         string `json:"price_cnd_max"`
	PriceCndMinSign     string `json:"price_cnd_min_sign"`
	PriceCndMaxSign     string `json:"price_cnd_max_sign"`
	MacCndTp            string `json:"mac_cnd_tp"`
	MacCndMin           string `json:"mac_cnd_min"`
	MacCndMax           string `json:"mac_cnd_max"`
	MacCndMinSign       string `json:"mac_cnd_min_sign"`
	MacCndMaxSign       string `json:"mac_cnd_max_sign"`
	TrdePricaCndTp      string `json:"trde_prica_cnd_tp"`
	TrdePricaCndMin     string `json:"trde_prica_cnd_min"`
	TrdePricaCndMax     string `json:"trde_prica_cnd_max"`
	TrdePricaCndMinSgin string `json:"trde_prica_cnd_min_sgin"`
	TrdePricaCndMaxSign string `json:"trde_prica_cnd_max_sign"`
	TrdeQtyCndTp        string `json:"trde_qty_cnd_tp"`
	TrdeQtyCndMin       string `json:"trde_qty_cnd_min"`
	TrdeQtyCndMax       string `json:"trde_qty_cnd_max"`
	TrdeQtyCndMinSign   string `json:"trde_qty_cnd_min_sign"`
	TrdeQtyCndMaxSign   string `json:"trde_qty_cnd_max_sign"`
	StexTp              string `json:"stex_tp"`
}

// BlockTradeRankResponse is the response payload for ka00190 (대량체결상위).
type BlockTradeRankResponse struct {
	ResultList []BlockTradeRankResponseResultListItem `json:"result_list"`
	ReturnCode int                                    `json:"return_code"`
	ReturnMsg  string                                 `json:"return_msg"`
}

// BlockTradeRankResponseResultListItem is a list row in BlockTradeRankResponse.
type BlockTradeRankResponseResultListItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	TrdeQty    string `json:"trde_qty"`
	BuyCnt     string `json:"buy_cnt"`
	SelCnt     string `json:"sel_cnt"`
	Pre        string `json:"pre"`
	TrdePrica  string `json:"trde_prica"`
}

// GetBlockTradeRank calls Kiwoom ka00190 — 대량체결상위.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetBlockTradeRank(ctx context.Context, req *BlockTradeRankRequest) (*BlockTradeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka00190", req)
	if err != nil {
		return nil, err
	}
	var res BlockTradeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TradeAmountRatioRequest is the request payload for ka00196 (체결금액대별매매비중).
type TradeAmountRatioRequest struct {
	StkCd string `json:"stk_cd"`
}

// TradeAmountRatioResponse is the response payload for ka00196 (체결금액대별매매비중).
type TradeAmountRatioResponse struct {
	ResultList []TradeAmountRatioResponseResultListItem `json:"result_list"`
	ReturnCode int                                      `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
}

// TradeAmountRatioResponseResultListItem is a list row in TradeAmountRatioResponse.
type TradeAmountRatioResponseResultListItem struct {
	SelTrdeQty  string `json:"sel_trde_qty"`
	BuyTrdeQty  string `json:"buy_trde_qty"`
	TotTrdeQty  string `json:"tot_trde_qty"`
	SelCnt      string `json:"sel_cnt"`
	BuyCnt      string `json:"buy_cnt"`
	TotNetCnt   string `json:"tot_net_cnt"`
	SelRt       string `json:"sel_rt"`
	BuyRt       string `json:"buy_rt"`
	TotNetRt    string `json:"tot_net_rt"`
	TotAvgPric  string `json:"tot_avg_pric"`
	MontCntrAmt string `json:"mont_cntr_amt"`
	SelAvgPric  string `json:"sel_avg_pric"`
	BuyAvgPric  string `json:"buy_avg_pric"`
}

// GetTradeAmountRatio calls Kiwoom ka00196 — 체결금액대별매매비중.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetTradeAmountRatio(ctx context.Context, req *TradeAmountRatioRequest) (*TradeAmountRatioResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka00196", req)
	if err != nil {
		return nil, err
	}
	var res TradeAmountRatioResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// WatchlistGroupsRequest is the request payload for ka01300 (관심종목 그룹 리스트 조회).
type WatchlistGroupsRequest struct {
}

// WatchlistGroupsResponse is the response payload for ka01300 (관심종목 그룹 리스트 조회).
type WatchlistGroupsResponse struct {
	Rtcd       string                            `json:"rtcd"`
	Nofi       []WatchlistGroupsResponseNofiItem `json:"nofi"`
	ReturnCode int                               `json:"return_code"`
	ReturnMsg  string                            `json:"return_msg"`
}

// WatchlistGroupsResponseNofiItem is a list row in WatchlistGroupsResponse.
type WatchlistGroupsResponseNofiItem struct {
	Gcod string `json:"gcod"`
	Name string `json:"name"`
}

// GetWatchlistGroups calls Kiwoom ka01300 — 관심종목 그룹 리스트 조회.
// 관심종목 정보를 확인할 수 있습니다.
func (c *Client) GetWatchlistGroups(ctx context.Context, req *WatchlistGroupsRequest) (*WatchlistGroupsResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/watchlist", "ka01300", req)
	if err != nil {
		return nil, err
	}
	var res WatchlistGroupsResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// WatchlistGroupDetailRequest is the request payload for ka01301 (관심종목 그룹 상세 조회).
type WatchlistGroupDetailRequest struct {
	ArnGrpId string `json:"arn_grp_id"`
}

// WatchlistGroupDetailResponse is the response payload for ka01301 (관심종목 그룹 상세 조회).
type WatchlistGroupDetailResponse struct {
	Rtcd       string                                 `json:"rtcd"`
	Nofj       []WatchlistGroupDetailResponseNofjItem `json:"nofj"`
	ReturnCode int                                    `json:"return_code"`
	ReturnMsg  string                                 `json:"return_msg"`
}

// WatchlistGroupDetailResponseNofjItem is a list row in WatchlistGroupDetailResponse.
type WatchlistGroupDetailResponseNofjItem struct {
	Cod2   string `json:"cod2"`
	Bgb    string `json:"bgb"`
	BgbClr string `json:"bgb_clr"`
}

// GetWatchlistGroupDetail calls Kiwoom ka01301 — 관심종목 그룹 상세 조회.
// 관심종목 정보를 확인할 수 있습니다.
func (c *Client) GetWatchlistGroupDetail(ctx context.Context, req *WatchlistGroupDetailRequest) (*WatchlistGroupDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/watchlist", "ka01301", req)
	if err != nil {
		return nil, err
	}
	var res WatchlistGroupDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockBrokerRequest is the request payload for ka10002 (주식거래원요청).
type StockBrokerRequest struct {
	StkCd string `json:"stk_cd"`
}

// StockBrokerResponse is the response payload for ka10002 (주식거래원요청).
type StockBrokerResponse struct {
	StkCd          string `json:"stk_cd"`
	StkNm          string `json:"stk_nm"`
	CurPrc         string `json:"cur_prc"`
	FluSmbol       string `json:"flu_smbol"`
	BasePric       string `json:"base_pric"`
	PredPre        string `json:"pred_pre"`
	FluRt          string `json:"flu_rt"`
	SelTrdeOriNmN1 string `json:"sel_trde_ori_nm_1"`
	SelTrdeOriN1   string `json:"sel_trde_ori_1"`
	SelTrdeQtyN1   string `json:"sel_trde_qty_1"`
	BuyTrdeOriNmN1 string `json:"buy_trde_ori_nm_1"`
	BuyTrdeOriN1   string `json:"buy_trde_ori_1"`
	BuyTrdeQtyN1   string `json:"buy_trde_qty_1"`
	SelTrdeOriNmN2 string `json:"sel_trde_ori_nm_2"`
	SelTrdeOriN2   string `json:"sel_trde_ori_2"`
	SelTrdeQtyN2   string `json:"sel_trde_qty_2"`
	BuyTrdeOriNmN2 string `json:"buy_trde_ori_nm_2"`
	BuyTrdeOriN2   string `json:"buy_trde_ori_2"`
	BuyTrdeQtyN2   string `json:"buy_trde_qty_2"`
	SelTrdeOriNmN3 string `json:"sel_trde_ori_nm_3"`
	SelTrdeOriN3   string `json:"sel_trde_ori_3"`
	SelTrdeQtyN3   string `json:"sel_trde_qty_3"`
	BuyTrdeOriNmN3 string `json:"buy_trde_ori_nm_3"`
	BuyTrdeOriN3   string `json:"buy_trde_ori_3"`
	BuyTrdeQtyN3   string `json:"buy_trde_qty_3"`
	SelTrdeOriNmN4 string `json:"sel_trde_ori_nm_4"`
	SelTrdeOriN4   string `json:"sel_trde_ori_4"`
	SelTrdeQtyN4   string `json:"sel_trde_qty_4"`
	BuyTrdeOriNmN4 string `json:"buy_trde_ori_nm_4"`
	BuyTrdeOriN4   string `json:"buy_trde_ori_4"`
	BuyTrdeQtyN4   string `json:"buy_trde_qty_4"`
	SelTrdeOriNmN5 string `json:"sel_trde_ori_nm_5"`
	SelTrdeOriN5   string `json:"sel_trde_ori_5"`
	SelTrdeQtyN5   string `json:"sel_trde_qty_5"`
	BuyTrdeOriNmN5 string `json:"buy_trde_ori_nm_5"`
	BuyTrdeOriN5   string `json:"buy_trde_ori_5"`
	BuyTrdeQtyN5   string `json:"buy_trde_qty_5"`
	ReturnCode     int    `json:"return_code"`
	ReturnMsg      string `json:"return_msg"`
}

// GetStockBroker calls Kiwoom ka10002 — 주식거래원요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetStockBroker(ctx context.Context, req *StockBrokerRequest) (*StockBrokerResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10002", req)
	if err != nil {
		return nil, err
	}
	var res StockBrokerResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockExecutionInfoRequest is the request payload for ka10003 (체결정보요청).
type StockExecutionInfoRequest struct {
	StkCd string `json:"stk_cd"`
}

// StockExecutionInfoResponse is the response payload for ka10003 (체결정보요청).
type StockExecutionInfoResponse struct {
	CntrInfr   []StockExecutionInfoResponseCntrInfrItem `json:"cntr_infr"`
	ReturnCode int                                      `json:"return_code"`
	ReturnMsg  string                                   `json:"return_msg"`
}

// StockExecutionInfoResponseCntrInfrItem is a list row in StockExecutionInfoResponse.
type StockExecutionInfoResponseCntrInfrItem struct {
	Tm            string `json:"tm"`
	CurPrc        string `json:"cur_prc"`
	PredPre       string `json:"pred_pre"`
	PreRt         string `json:"pre_rt"`
	PriSelBidUnit string `json:"pri_sel_bid_unit"`
	PriBuyBidUnit string `json:"pri_buy_bid_unit"`
	CntrTrdeQty   string `json:"cntr_trde_qty"`
	Sign          string `json:"sign"`
	AccTrdeQty    string `json:"acc_trde_qty"`
	AccTrdePrica  string `json:"acc_trde_prica"`
	CntrStr       string `json:"cntr_str"`
	StexTp        string `json:"stex_tp"`
}

// GetStockExecutionInfo calls Kiwoom ka10003 — 체결정보요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetStockExecutionInfo(ctx context.Context, req *StockExecutionInfoRequest) (*StockExecutionInfoResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10003", req)
	if err != nil {
		return nil, err
	}
	var res StockExecutionInfoResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockQuoteRequest is the request payload for ka10004 (주식호가요청).
type StockQuoteRequest struct {
	StkCd string `json:"stk_cd"`
}

// StockQuoteResponse is the response payload for ka10004 (주식호가요청).
type StockQuoteResponse struct {
	BidReqBaseTm      string `json:"bid_req_base_tm"`
	SelN10thPreReqPre string `json:"sel_10th_pre_req_pre"`
	SelN10thPreReq    string `json:"sel_10th_pre_req"`
	SelN10thPreBid    string `json:"sel_10th_pre_bid"`
	SelN9thPreReqPre  string `json:"sel_9th_pre_req_pre"`
	SelN9thPreReq     string `json:"sel_9th_pre_req"`
	SelN9thPreBid     string `json:"sel_9th_pre_bid"`
	SelN8thPreReqPre  string `json:"sel_8th_pre_req_pre"`
	SelN8thPreReq     string `json:"sel_8th_pre_req"`
	SelN8thPreBid     string `json:"sel_8th_pre_bid"`
	SelN7thPreReqPre  string `json:"sel_7th_pre_req_pre"`
	SelN7thPreReq     string `json:"sel_7th_pre_req"`
	SelN7thPreBid     string `json:"sel_7th_pre_bid"`
	SelN6thPreReqPre  string `json:"sel_6th_pre_req_pre"`
	SelN6thPreReq     string `json:"sel_6th_pre_req"`
	SelN6thPreBid     string `json:"sel_6th_pre_bid"`
	SelN5thPreReqPre  string `json:"sel_5th_pre_req_pre"`
	SelN5thPreReq     string `json:"sel_5th_pre_req"`
	SelN5thPreBid     string `json:"sel_5th_pre_bid"`
	SelN4thPreReqPre  string `json:"sel_4th_pre_req_pre"`
	SelN4thPreReq     string `json:"sel_4th_pre_req"`
	SelN4thPreBid     string `json:"sel_4th_pre_bid"`
	SelN3thPreReqPre  string `json:"sel_3th_pre_req_pre"`
	SelN3thPreReq     string `json:"sel_3th_pre_req"`
	SelN3thPreBid     string `json:"sel_3th_pre_bid"`
	SelN2thPreReqPre  string `json:"sel_2th_pre_req_pre"`
	SelN2thPreReq     string `json:"sel_2th_pre_req"`
	SelN2thPreBid     string `json:"sel_2th_pre_bid"`
	SelN1thPreReqPre  string `json:"sel_1th_pre_req_pre"`
	SelFprReq         string `json:"sel_fpr_req"`
	SelFprBid         string `json:"sel_fpr_bid"`
	BuyFprBid         string `json:"buy_fpr_bid"`
	BuyFprReq         string `json:"buy_fpr_req"`
	BuyN1thPreReqPre  string `json:"buy_1th_pre_req_pre"`
	BuyN2thPreBid     string `json:"buy_2th_pre_bid"`
	BuyN2thPreReq     string `json:"buy_2th_pre_req"`
	BuyN2thPreReqPre  string `json:"buy_2th_pre_req_pre"`
	BuyN3thPreBid     string `json:"buy_3th_pre_bid"`
	BuyN3thPreReq     string `json:"buy_3th_pre_req"`
	BuyN3thPreReqPre  string `json:"buy_3th_pre_req_pre"`
	BuyN4thPreBid     string `json:"buy_4th_pre_bid"`
	BuyN4thPreReq     string `json:"buy_4th_pre_req"`
	BuyN4thPreReqPre  string `json:"buy_4th_pre_req_pre"`
	BuyN5thPreBid     string `json:"buy_5th_pre_bid"`
	BuyN5thPreReq     string `json:"buy_5th_pre_req"`
	BuyN5thPreReqPre  string `json:"buy_5th_pre_req_pre"`
	BuyN6thPreBid     string `json:"buy_6th_pre_bid"`
	BuyN6thPreReq     string `json:"buy_6th_pre_req"`
	BuyN6thPreReqPre  string `json:"buy_6th_pre_req_pre"`
	BuyN7thPreBid     string `json:"buy_7th_pre_bid"`
	BuyN7thPreReq     string `json:"buy_7th_pre_req"`
	BuyN7thPreReqPre  string `json:"buy_7th_pre_req_pre"`
	BuyN8thPreBid     string `json:"buy_8th_pre_bid"`
	BuyN8thPreReq     string `json:"buy_8th_pre_req"`
	BuyN8thPreReqPre  string `json:"buy_8th_pre_req_pre"`
	BuyN9thPreBid     string `json:"buy_9th_pre_bid"`
	BuyN9thPreReq     string `json:"buy_9th_pre_req"`
	BuyN9thPreReqPre  string `json:"buy_9th_pre_req_pre"`
	BuyN10thPreBid    string `json:"buy_10th_pre_bid"`
	BuyN10thPreReq    string `json:"buy_10th_pre_req"`
	BuyN10thPreReqPre string `json:"buy_10th_pre_req_pre"`
	TotSelReqJubPre   string `json:"tot_sel_req_jub_pre"`
	TotSelReq         string `json:"tot_sel_req"`
	TotBuyReq         string `json:"tot_buy_req"`
	TotBuyReqJubPre   string `json:"tot_buy_req_jub_pre"`
	OvtSelReqPre      string `json:"ovt_sel_req_pre"`
	OvtSelReq         string `json:"ovt_sel_req"`
	OvtBuyReq         string `json:"ovt_buy_req"`
	OvtBuyReqPre      string `json:"ovt_buy_req_pre"`
	ReturnCode        int    `json:"return_code"`
	ReturnMsg         string `json:"return_msg"`
}

// GetStockQuote calls Kiwoom ka10004 — 주식호가요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetStockQuote(ctx context.Context, req *StockQuoteRequest) (*StockQuoteResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10004", req)
	if err != nil {
		return nil, err
	}
	var res StockQuoteResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockDailyWeeklyMonthlyMinuteRequest is the request payload for ka10005 (주식일주월시분요청).
type StockDailyWeeklyMonthlyMinuteRequest struct {
	StkCd string `json:"stk_cd"`
}

// StockDailyWeeklyMonthlyMinuteResponse is the response payload for ka10005 (주식일주월시분요청).
type StockDailyWeeklyMonthlyMinuteResponse struct {
	StkDdwkmm  []StockDailyWeeklyMonthlyMinuteResponseStkDdwkmmItem `json:"stk_ddwkmm"`
	ReturnCode int                                                  `json:"return_code"`
	ReturnMsg  string                                               `json:"return_msg"`
}

// StockDailyWeeklyMonthlyMinuteResponseStkDdwkmmItem is a list row in StockDailyWeeklyMonthlyMinuteResponse.
type StockDailyWeeklyMonthlyMinuteResponseStkDdwkmmItem struct {
	Date        string `json:"date"`
	OpenPric    string `json:"open_pric"`
	HighPric    string `json:"high_pric"`
	LowPric     string `json:"low_pric"`
	ClosePric   string `json:"close_pric"`
	Pre         string `json:"pre"`
	FluRt       string `json:"flu_rt"`
	TrdeQty     string `json:"trde_qty"`
	TrdePrica   string `json:"trde_prica"`
	ForPoss     string `json:"for_poss"`
	ForWght     string `json:"for_wght"`
	ForNetprps  string `json:"for_netprps"`
	OrgnNetprps string `json:"orgn_netprps"`
	IndNetprps  string `json:"ind_netprps"`
	CrdRemnRt   string `json:"crd_remn_rt"`
	Frgn        string `json:"frgn"`
	Prm         string `json:"prm"`
}

// GetStockDailyWeeklyMonthlyMinute calls Kiwoom ka10005 — 주식일주월시분요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetStockDailyWeeklyMonthlyMinute(ctx context.Context, req *StockDailyWeeklyMonthlyMinuteRequest) (*StockDailyWeeklyMonthlyMinuteResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10005", req)
	if err != nil {
		return nil, err
	}
	var res StockDailyWeeklyMonthlyMinuteResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockIntradayMinuteRequest is the request payload for ka10006 (주식시분요청).
type StockIntradayMinuteRequest struct {
	StkCd string `json:"stk_cd"`
}

// StockIntradayMinuteResponse is the response payload for ka10006 (주식시분요청).
type StockIntradayMinuteResponse struct {
	Date       string `json:"date"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
	ClosePric  string `json:"close_pric"`
	Pre        string `json:"pre"`
	FluRt      string `json:"flu_rt"`
	TrdeQty    string `json:"trde_qty"`
	TrdePrica  string `json:"trde_prica"`
	CntrStr    string `json:"cntr_str"`
	ReturnCode int    `json:"return_code"`
	ReturnMsg  string `json:"return_msg"`
}

// GetStockIntradayMinute calls Kiwoom ka10006 — 주식시분요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetStockIntradayMinute(ctx context.Context, req *StockIntradayMinuteRequest) (*StockIntradayMinuteResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10006", req)
	if err != nil {
		return nil, err
	}
	var res StockIntradayMinuteResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// QuoteTableInfoRequest is the request payload for ka10007 (시세표성정보요청).
type QuoteTableInfoRequest struct {
	StkCd string `json:"stk_cd"`
}

// QuoteTableInfoResponse is the response payload for ka10007 (시세표성정보요청).
type QuoteTableInfoResponse struct {
	StkNm           string `json:"stk_nm"`
	StkCd           string `json:"stk_cd"`
	Date            string `json:"date"`
	Tm              string `json:"tm"`
	PredClosePric   string `json:"pred_close_pric"`
	PredTrdeQty     string `json:"pred_trde_qty"`
	UplPric         string `json:"upl_pric"`
	LstPric         string `json:"lst_pric"`
	PredTrdePrica   string `json:"pred_trde_prica"`
	FloStkcnt       string `json:"flo_stkcnt"`
	CurPrc          string `json:"cur_prc"`
	Smbol           string `json:"smbol"`
	FluRt           string `json:"flu_rt"`
	PredRt          string `json:"pred_rt"`
	OpenPric        string `json:"open_pric"`
	HighPric        string `json:"high_pric"`
	LowPric         string `json:"low_pric"`
	CntrQty         string `json:"cntr_qty"`
	TrdeQty         string `json:"trde_qty"`
	TrdePrica       string `json:"trde_prica"`
	ExpCntrPric     string `json:"exp_cntr_pric"`
	ExpCntrQty      string `json:"exp_cntr_qty"`
	ExpSelPriBid    string `json:"exp_sel_pri_bid"`
	ExpBuyPriBid    string `json:"exp_buy_pri_bid"`
	TrdeStrtDt      string `json:"trde_strt_dt"`
	ExecPric        string `json:"exec_pric"`
	HgstPric        string `json:"hgst_pric"`
	LwstPric        string `json:"lwst_pric"`
	HgstPricDt      string `json:"hgst_pric_dt"`
	LwstPricDt      string `json:"lwst_pric_dt"`
	SelN1bid        string `json:"sel_1bid"`
	SelN2bid        string `json:"sel_2bid"`
	SelN3bid        string `json:"sel_3bid"`
	SelN4bid        string `json:"sel_4bid"`
	SelN5bid        string `json:"sel_5bid"`
	SelN6bid        string `json:"sel_6bid"`
	SelN7bid        string `json:"sel_7bid"`
	SelN8bid        string `json:"sel_8bid"`
	SelN9bid        string `json:"sel_9bid"`
	SelN10bid       string `json:"sel_10bid"`
	BuyN1bid        string `json:"buy_1bid"`
	BuyN2bid        string `json:"buy_2bid"`
	BuyN3bid        string `json:"buy_3bid"`
	BuyN4bid        string `json:"buy_4bid"`
	BuyN5bid        string `json:"buy_5bid"`
	BuyN6bid        string `json:"buy_6bid"`
	BuyN7bid        string `json:"buy_7bid"`
	BuyN8bid        string `json:"buy_8bid"`
	BuyN9bid        string `json:"buy_9bid"`
	BuyN10bid       string `json:"buy_10bid"`
	SelN1bidReq     string `json:"sel_1bid_req"`
	SelN2bidReq     string `json:"sel_2bid_req"`
	SelN3bidReq     string `json:"sel_3bid_req"`
	SelN4bidReq     string `json:"sel_4bid_req"`
	SelN5bidReq     string `json:"sel_5bid_req"`
	SelN6bidReq     string `json:"sel_6bid_req"`
	SelN7bidReq     string `json:"sel_7bid_req"`
	SelN8bidReq     string `json:"sel_8bid_req"`
	SelN9bidReq     string `json:"sel_9bid_req"`
	SelN10bidReq    string `json:"sel_10bid_req"`
	BuyN1bidReq     string `json:"buy_1bid_req"`
	BuyN2bidReq     string `json:"buy_2bid_req"`
	BuyN3bidReq     string `json:"buy_3bid_req"`
	BuyN4bidReq     string `json:"buy_4bid_req"`
	BuyN5bidReq     string `json:"buy_5bid_req"`
	BuyN6bidReq     string `json:"buy_6bid_req"`
	BuyN7bidReq     string `json:"buy_7bid_req"`
	BuyN8bidReq     string `json:"buy_8bid_req"`
	BuyN9bidReq     string `json:"buy_9bid_req"`
	BuyN10bidReq    string `json:"buy_10bid_req"`
	SelN1bidJubPre  string `json:"sel_1bid_jub_pre"`
	SelN2bidJubPre  string `json:"sel_2bid_jub_pre"`
	SelN3bidJubPre  string `json:"sel_3bid_jub_pre"`
	SelN4bidJubPre  string `json:"sel_4bid_jub_pre"`
	SelN5bidJubPre  string `json:"sel_5bid_jub_pre"`
	SelN6bidJubPre  string `json:"sel_6bid_jub_pre"`
	SelN7bidJubPre  string `json:"sel_7bid_jub_pre"`
	SelN8bidJubPre  string `json:"sel_8bid_jub_pre"`
	SelN9bidJubPre  string `json:"sel_9bid_jub_pre"`
	SelN10bidJubPre string `json:"sel_10bid_jub_pre"`
	BuyN1bidJubPre  string `json:"buy_1bid_jub_pre"`
	BuyN2bidJubPre  string `json:"buy_2bid_jub_pre"`
	BuyN3bidJubPre  string `json:"buy_3bid_jub_pre"`
	BuyN4bidJubPre  string `json:"buy_4bid_jub_pre"`
	BuyN5bidJubPre  string `json:"buy_5bid_jub_pre"`
	BuyN6bidJubPre  string `json:"buy_6bid_jub_pre"`
	BuyN7bidJubPre  string `json:"buy_7bid_jub_pre"`
	BuyN8bidJubPre  string `json:"buy_8bid_jub_pre"`
	BuyN9bidJubPre  string `json:"buy_9bid_jub_pre"`
	BuyN10bidJubPre string `json:"buy_10bid_jub_pre"`
	SelN1bidCnt     string `json:"sel_1bid_cnt"`
	SelN2bidCnt     string `json:"sel_2bid_cnt"`
	SelN3bidCnt     string `json:"sel_3bid_cnt"`
	SelN4bidCnt     string `json:"sel_4bid_cnt"`
	SelN5bidCnt     string `json:"sel_5bid_cnt"`
	BuyN1bidCnt     string `json:"buy_1bid_cnt"`
	BuyN2bidCnt     string `json:"buy_2bid_cnt"`
	BuyN3bidCnt     string `json:"buy_3bid_cnt"`
	BuyN4bidCnt     string `json:"buy_4bid_cnt"`
	BuyN5bidCnt     string `json:"buy_5bid_cnt"`
	LpselN1bidReq   string `json:"lpsel_1bid_req"`
	LpselN2bidReq   string `json:"lpsel_2bid_req"`
	LpselN3bidReq   string `json:"lpsel_3bid_req"`
	LpselN4bidReq   string `json:"lpsel_4bid_req"`
	LpselN5bidReq   string `json:"lpsel_5bid_req"`
	LpselN6bidReq   string `json:"lpsel_6bid_req"`
	LpselN7bidReq   string `json:"lpsel_7bid_req"`
	LpselN8bidReq   string `json:"lpsel_8bid_req"`
	LpselN9bidReq   string `json:"lpsel_9bid_req"`
	LpselN10bidReq  string `json:"lpsel_10bid_req"`
	LpbuyN1bidReq   string `json:"lpbuy_1bid_req"`
	LpbuyN2bidReq   string `json:"lpbuy_2bid_req"`
	LpbuyN3bidReq   string `json:"lpbuy_3bid_req"`
	LpbuyN4bidReq   string `json:"lpbuy_4bid_req"`
	LpbuyN5bidReq   string `json:"lpbuy_5bid_req"`
	LpbuyN6bidReq   string `json:"lpbuy_6bid_req"`
	LpbuyN7bidReq   string `json:"lpbuy_7bid_req"`
	LpbuyN8bidReq   string `json:"lpbuy_8bid_req"`
	LpbuyN9bidReq   string `json:"lpbuy_9bid_req"`
	LpbuyN10bidReq  string `json:"lpbuy_10bid_req"`
	TotBuyReq       string `json:"tot_buy_req"`
	TotSelReq       string `json:"tot_sel_req"`
	TotBuyCnt       string `json:"tot_buy_cnt"`
	TotSelCnt       string `json:"tot_sel_cnt"`
	ReturnCode      int    `json:"return_code"`
	ReturnMsg       string `json:"return_msg"`
}

// GetQuoteTableInfo calls Kiwoom ka10007 — 시세표성정보요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetQuoteTableInfo(ctx context.Context, req *QuoteTableInfoRequest) (*QuoteTableInfoResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10007", req)
	if err != nil {
		return nil, err
	}
	var res QuoteTableInfoResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SectorProgramRequest is the request payload for ka10010 (업종프로그램요청).
type SectorProgramRequest struct {
	StkCd string `json:"stk_cd"`
}

// SectorProgramResponse is the response payload for ka10010 (업종프로그램요청).
type SectorProgramResponse struct {
	DfrtTrstSellQty        string `json:"dfrt_trst_sell_qty"`
	DfrtTrstSellAmt        string `json:"dfrt_trst_sell_amt"`
	DfrtTrstBuyQty         string `json:"dfrt_trst_buy_qty"`
	DfrtTrstBuyAmt         string `json:"dfrt_trst_buy_amt"`
	DfrtTrstNetprpsQty     string `json:"dfrt_trst_netprps_qty"`
	DfrtTrstNetprpsAmt     string `json:"dfrt_trst_netprps_amt"`
	NdiffproTrstSellQty    string `json:"ndiffpro_trst_sell_qty"`
	NdiffproTrstSellAmt    string `json:"ndiffpro_trst_sell_amt"`
	NdiffproTrstBuyQty     string `json:"ndiffpro_trst_buy_qty"`
	NdiffproTrstBuyAmt     string `json:"ndiffpro_trst_buy_amt"`
	NdiffproTrstNetprpsQty string `json:"ndiffpro_trst_netprps_qty"`
	NdiffproTrstNetprpsAmt string `json:"ndiffpro_trst_netprps_amt"`
	AllDfrtTrstSellQty     string `json:"all_dfrt_trst_sell_qty"`
	AllDfrtTrstSellAmt     string `json:"all_dfrt_trst_sell_amt"`
	AllDfrtTrstBuyQty      string `json:"all_dfrt_trst_buy_qty"`
	AllDfrtTrstBuyAmt      string `json:"all_dfrt_trst_buy_amt"`
	AllDfrtTrstNetprpsQty  string `json:"all_dfrt_trst_netprps_qty"`
	AllDfrtTrstNetprpsAmt  string `json:"all_dfrt_trst_netprps_amt"`
	ReturnCode             int    `json:"return_code"`
	ReturnMsg              string `json:"return_msg"`
}

// GetSectorProgram calls Kiwoom ka10010 — 업종프로그램요청.
// 업종 정보를 확인할 수 있습니다.
func (c *Client) GetSectorProgram(ctx context.Context, req *SectorProgramRequest) (*SectorProgramResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/sect", "ka10010", req)
	if err != nil {
		return nil, err
	}
	var res SectorProgramResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// WarrantFullQuoteRequest is the request payload for ka10011 (신주인수권전체시세요청).
type WarrantFullQuoteRequest struct {
	NewstkRecvrhtTp string `json:"newstk_recvrht_tp"`
}

// WarrantFullQuoteResponse is the response payload for ka10011 (신주인수권전체시세요청).
type WarrantFullQuoteResponse struct {
	NewstkRecvrhtMrpr []WarrantFullQuoteResponseNewstkRecvrhtMrprItem `json:"newstk_recvrht_mrpr"`
	ReturnCode        int                                             `json:"return_code"`
	ReturnMsg         string                                          `json:"return_msg"`
}

// WarrantFullQuoteResponseNewstkRecvrhtMrprItem is a list row in WarrantFullQuoteResponse.
type WarrantFullQuoteResponseNewstkRecvrhtMrprItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	FprSelBid  string `json:"fpr_sel_bid"`
	FprBuyBid  string `json:"fpr_buy_bid"`
	AccTrdeQty string `json:"acc_trde_qty"`
	OpenPric   string `json:"open_pric"`
	HighPric   string `json:"high_pric"`
	LowPric    string `json:"low_pric"`
}

// GetWarrantFullQuote calls Kiwoom ka10011 — 신주인수권전체시세요청.
// 시세정보를 확인할 수 있습니다
func (c *Client) GetWarrantFullQuote(ctx context.Context, req *WarrantFullQuoteRequest) (*WarrantFullQuoteResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/mrkcond", "ka10011", req)
	if err != nil {
		return nil, err
	}
	var res WarrantFullQuoteResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CreditTradingTrendRequest is the request payload for ka10013 (신용매매동향요청).
type CreditTradingTrendRequest struct {
	StkCd string `json:"stk_cd"`
	Dt    string `json:"dt"`
	QryTp string `json:"qry_tp"`
}

// CreditTradingTrendResponse is the response payload for ka10013 (신용매매동향요청).
type CreditTradingTrendResponse struct {
	CrdTrdeTrend []CreditTradingTrendResponseCrdTrdeTrendItem `json:"crd_trde_trend"`
	ReturnCode   int                                          `json:"return_code"`
	ReturnMsg    string                                       `json:"return_msg"`
}

// CreditTradingTrendResponseCrdTrdeTrendItem is a list row in CreditTradingTrendResponse.
type CreditTradingTrendResponseCrdTrdeTrendItem struct {
	Dt         string `json:"dt"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	TrdeQty    string `json:"trde_qty"`
	New        string `json:"new"`
	Rpya       string `json:"rpya"`
	Remn       string `json:"remn"`
	Amt        string `json:"amt"`
	Pre        string `json:"pre"`
	ShrRt      string `json:"shr_rt"`
	RemnRt     string `json:"remn_rt"`
}

// GetCreditTradingTrend calls Kiwoom ka10013 — 신용매매동향요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetCreditTradingTrend(ctx context.Context, req *CreditTradingTrendRequest) (*CreditTradingTrendResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10013", req)
	if err != nil {
		return nil, err
	}
	var res CreditTradingTrendResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ShortSellingTrendRequest is the request payload for ka10014 (공매도추이요청).
type ShortSellingTrendRequest struct {
	StkCd  string `json:"stk_cd"`
	TmTp   string `json:"tm_tp"`
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
}

// ShortSellingTrendResponse is the response payload for ka10014 (공매도추이요청).
type ShortSellingTrendResponse struct {
	ShrtsTrnsn []ShortSellingTrendResponseShrtsTrnsnItem `json:"shrts_trnsn"`
	ReturnCode int                                       `json:"return_code"`
	ReturnMsg  string                                    `json:"return_msg"`
}

// ShortSellingTrendResponseShrtsTrnsnItem is a list row in ShortSellingTrendResponse.
type ShortSellingTrendResponseShrtsTrnsnItem struct {
	Dt             string `json:"dt"`
	ClosePric      string `json:"close_pric"`
	PredPreSig     string `json:"pred_pre_sig"`
	PredPre        string `json:"pred_pre"`
	FluRt          string `json:"flu_rt"`
	TrdeQty        string `json:"trde_qty"`
	ShrtsQty       string `json:"shrts_qty"`
	OvrShrtsQty    string `json:"ovr_shrts_qty"`
	TrdeWght       string `json:"trde_wght"`
	ShrtsTrdePrica string `json:"shrts_trde_prica"`
	ShrtsAvgPric   string `json:"shrts_avg_pric"`
}

// GetShortSellingTrend calls Kiwoom ka10014 — 공매도추이요청.
// 공매도 정보를 확인할 수 있습니다.
func (c *Client) GetShortSellingTrend(ctx context.Context, req *ShortSellingTrendRequest) (*ShortSellingTrendResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/shsa", "ka10014", req)
	if err != nil {
		return nil, err
	}
	var res ShortSellingTrendResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// DailyTradeDetailRequest is the request payload for ka10015 (일별거래상세요청).
type DailyTradeDetailRequest struct {
	StkCd  string `json:"stk_cd"`
	StrtDt string `json:"strt_dt"`
}

// DailyTradeDetailResponse is the response payload for ka10015 (일별거래상세요청).
type DailyTradeDetailResponse struct {
	DalyTrdeDtl []DailyTradeDetailResponseDalyTrdeDtlItem `json:"daly_trde_dtl"`
	ReturnCode  int                                       `json:"return_code"`
	ReturnMsg   string                                    `json:"return_msg"`
}

// DailyTradeDetailResponseDalyTrdeDtlItem is a list row in DailyTradeDetailResponse.
type DailyTradeDetailResponseDalyTrdeDtlItem struct {
	Dt                  string `json:"dt"`
	ClosePric           string `json:"close_pric"`
	PredPreSig          string `json:"pred_pre_sig"`
	PredPre             string `json:"pred_pre"`
	FluRt               string `json:"flu_rt"`
	TrdeQty             string `json:"trde_qty"`
	TrdePrica           string `json:"trde_prica"`
	BfMkrtTrdeQty       string `json:"bf_mkrt_trde_qty"`
	BfMkrtTrdeWght      string `json:"bf_mkrt_trde_wght"`
	OpmrTrdeQty         string `json:"opmr_trde_qty"`
	OpmrTrdeWght        string `json:"opmr_trde_wght"`
	AfMkrtTrdeQty       string `json:"af_mkrt_trde_qty"`
	AfMkrtTrdeWght      string `json:"af_mkrt_trde_wght"`
	TotN3               string `json:"tot_3"`
	PridTrdeQty         string `json:"prid_trde_qty"`
	CntrStr             string `json:"cntr_str"`
	ForPoss             string `json:"for_poss"`
	ForWght             string `json:"for_wght"`
	ForNetprps          string `json:"for_netprps"`
	OrgnNetprps         string `json:"orgn_netprps"`
	IndNetprps          string `json:"ind_netprps"`
	Frgn                string `json:"frgn"`
	CrdRemnRt           string `json:"crd_remn_rt"`
	Prm                 string `json:"prm"`
	BfMkrtTrdePrica     string `json:"bf_mkrt_trde_prica"`
	BfMkrtTrdePricaWght string `json:"bf_mkrt_trde_prica_wght"`
	OpmrTrdePrica       string `json:"opmr_trde_prica"`
	OpmrTrdePricaWght   string `json:"opmr_trde_prica_wght"`
	AfMkrtTrdePrica     string `json:"af_mkrt_trde_prica"`
	AfMkrtTrdePricaWght string `json:"af_mkrt_trde_prica_wght"`
}

// GetDailyTradeDetail calls Kiwoom ka10015 — 일별거래상세요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetDailyTradeDetail(ctx context.Context, req *DailyTradeDetailRequest) (*DailyTradeDetailResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10015", req)
	if err != nil {
		return nil, err
	}
	var res DailyTradeDetailResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NewHighLowRequest is the request payload for ka10016 (신고저가요청).
type NewHighLowRequest struct {
	MrktTp         string `json:"mrkt_tp"`
	NtlTp          string `json:"ntl_tp"`
	HighLowCloseTp string `json:"high_low_close_tp"`
	StkCnd         string `json:"stk_cnd"`
	TrdeQtyTp      string `json:"trde_qty_tp"`
	CrdCnd         string `json:"crd_cnd"`
	UpdownIncls    string `json:"updown_incls"`
	Dt             string `json:"dt"`
	StexTp         string `json:"stex_tp"`
}

// NewHighLowResponse is the response payload for ka10016 (신고저가요청).
type NewHighLowResponse struct {
	NtlPric    []NewHighLowResponseNtlPricItem `json:"ntl_pric"`
	ReturnCode int                             `json:"return_code"`
	ReturnMsg  string                          `json:"return_msg"`
}

// NewHighLowResponseNtlPricItem is a list row in NewHighLowResponse.
type NewHighLowResponseNtlPricItem struct {
	StkCd            string `json:"stk_cd"`
	StkNm            string `json:"stk_nm"`
	CurPrc           string `json:"cur_prc"`
	PredPreSig       string `json:"pred_pre_sig"`
	PredPre          string `json:"pred_pre"`
	FluRt            string `json:"flu_rt"`
	TrdeQty          string `json:"trde_qty"`
	PredTrdeQtyPreRt string `json:"pred_trde_qty_pre_rt"`
	SelBid           string `json:"sel_bid"`
	BuyBid           string `json:"buy_bid"`
	HighPric         string `json:"high_pric"`
	LowPric          string `json:"low_pric"`
}

// GetNewHighLow calls Kiwoom ka10016 — 신고저가요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetNewHighLow(ctx context.Context, req *NewHighLowRequest) (*NewHighLowResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10016", req)
	if err != nil {
		return nil, err
	}
	var res NewHighLowResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// LimitUpDownRequest is the request payload for ka10017 (상하한가요청).
type LimitUpDownRequest struct {
	MrktTp     string `json:"mrkt_tp"`
	UpdownTp   string `json:"updown_tp"`
	SortTp     string `json:"sort_tp"`
	StkCnd     string `json:"stk_cnd"`
	TrdeQtyTp  string `json:"trde_qty_tp"`
	CrdCnd     string `json:"crd_cnd"`
	TrdeGoldTp string `json:"trde_gold_tp"`
	StexTp     string `json:"stex_tp"`
}

// LimitUpDownResponse is the response payload for ka10017 (상하한가요청).
type LimitUpDownResponse struct {
	UpdownPric []LimitUpDownResponseUpdownPricItem `json:"updown_pric"`
	ReturnCode int                                 `json:"return_code"`
	ReturnMsg  string                              `json:"return_msg"`
}

// LimitUpDownResponseUpdownPricItem is a list row in LimitUpDownResponse.
type LimitUpDownResponseUpdownPricItem struct {
	StkCd       string `json:"stk_cd"`
	StkInfr     string `json:"stk_infr"`
	StkNm       string `json:"stk_nm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	TrdeQty     string `json:"trde_qty"`
	PredTrdeQty string `json:"pred_trde_qty"`
	SelReq      string `json:"sel_req"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
	BuyReq      string `json:"buy_req"`
	Cnt         string `json:"cnt"`
}

// GetLimitUpDown calls Kiwoom ka10017 — 상하한가요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetLimitUpDown(ctx context.Context, req *LimitUpDownRequest) (*LimitUpDownResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10017", req)
	if err != nil {
		return nil, err
	}
	var res LimitUpDownResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NearHighLowRequest is the request payload for ka10018 (고저가근접요청).
type NearHighLowRequest struct {
	HighLowTp string `json:"high_low_tp"`
	AlaccRt   string `json:"alacc_rt"`
	MrktTp    string `json:"mrkt_tp"`
	TrdeQtyTp string `json:"trde_qty_tp"`
	StkCnd    string `json:"stk_cnd"`
	CrdCnd    string `json:"crd_cnd"`
	StexTp    string `json:"stex_tp"`
}

// NearHighLowResponse is the response payload for ka10018 (고저가근접요청).
type NearHighLowResponse struct {
	HighLowPricAlacc []NearHighLowResponseHighLowPricAlaccItem `json:"high_low_pric_alacc"`
	ReturnCode       int                                       `json:"return_code"`
	ReturnMsg        string                                    `json:"return_msg"`
}

// NearHighLowResponseHighLowPricAlaccItem is a list row in NearHighLowResponse.
type NearHighLowResponseHighLowPricAlaccItem struct {
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	TrdeQty     string `json:"trde_qty"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
	TdyHighPric string `json:"tdy_high_pric"`
	TdyLowPric  string `json:"tdy_low_pric"`
}

// GetNearHighLow calls Kiwoom ka10018 — 고저가근접요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetNearHighLow(ctx context.Context, req *NearHighLowRequest) (*NearHighLowResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10018", req)
	if err != nil {
		return nil, err
	}
	var res NearHighLowResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// PriceSurgeRequest is the request payload for ka10019 (가격급등락요청).
type PriceSurgeRequest struct {
	MrktTp      string `json:"mrkt_tp"`
	FluTp       string `json:"flu_tp"`
	TmTp        string `json:"tm_tp"`
	Tm          string `json:"tm"`
	TrdeQtyTp   string `json:"trde_qty_tp"`
	StkCnd      string `json:"stk_cnd"`
	CrdCnd      string `json:"crd_cnd"`
	PricCnd     string `json:"pric_cnd"`
	UpdownIncls string `json:"updown_incls"`
	StexTp      string `json:"stex_tp"`
}

// PriceSurgeResponse is the response payload for ka10019 (가격급등락요청).
type PriceSurgeResponse struct {
	PricJmpflu []PriceSurgeResponsePricJmpfluItem `json:"pric_jmpflu"`
	ReturnCode int                                `json:"return_code"`
	ReturnMsg  string                             `json:"return_msg"`
}

// PriceSurgeResponsePricJmpfluItem is a list row in PriceSurgeResponse.
type PriceSurgeResponsePricJmpfluItem struct {
	StkCd      string `json:"stk_cd"`
	StkCls     string `json:"stk_cls"`
	StkNm      string `json:"stk_nm"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	BasePric   string `json:"base_pric"`
	CurPrc     string `json:"cur_prc"`
	BasePre    string `json:"base_pre"`
	TrdeQty    string `json:"trde_qty"`
	JmpRt      string `json:"jmp_rt"`
}

// GetPriceSurge calls Kiwoom ka10019 — 가격급등락요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetPriceSurge(ctx context.Context, req *PriceSurgeRequest) (*PriceSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10019", req)
	if err != nil {
		return nil, err
	}
	var res PriceSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// QuoteVolumeRankRequest is the request payload for ka10020 (호가잔량상위요청).
type QuoteVolumeRankRequest struct {
	MrktTp    string `json:"mrkt_tp"`
	SortTp    string `json:"sort_tp"`
	TrdeQtyTp string `json:"trde_qty_tp"`
	StkCnd    string `json:"stk_cnd"`
	CrdCnd    string `json:"crd_cnd"`
	StexTp    string `json:"stex_tp"`
}

// QuoteVolumeRankResponse is the response payload for ka10020 (호가잔량상위요청).
type QuoteVolumeRankResponse struct {
	BidReqUpper []QuoteVolumeRankResponseBidReqUpperItem `json:"bid_req_upper"`
	ReturnCode  int                                      `json:"return_code"`
	ReturnMsg   string                                   `json:"return_msg"`
}

// QuoteVolumeRankResponseBidReqUpperItem is a list row in QuoteVolumeRankResponse.
type QuoteVolumeRankResponseBidReqUpperItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	TrdeQty    string `json:"trde_qty"`
	TotSelReq  string `json:"tot_sel_req"`
	TotBuyReq  string `json:"tot_buy_req"`
	NetprpsReq string `json:"netprps_req"`
	BuyRt      string `json:"buy_rt"`
}

// GetQuoteVolumeRank calls Kiwoom ka10020 — 호가잔량상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetQuoteVolumeRank(ctx context.Context, req *QuoteVolumeRankRequest) (*QuoteVolumeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10020", req)
	if err != nil {
		return nil, err
	}
	var res QuoteVolumeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// QuoteVolumeSurgeRequest is the request payload for ka10021 (호가잔량급증요청).
type QuoteVolumeSurgeRequest struct {
	MrktTp    string `json:"mrkt_tp"`
	TrdeTp    string `json:"trde_tp"`
	SortTp    string `json:"sort_tp"`
	TmTp      string `json:"tm_tp"`
	TrdeQtyTp string `json:"trde_qty_tp"`
	StkCnd    string `json:"stk_cnd"`
	StexTp    string `json:"stex_tp"`
}

// QuoteVolumeSurgeResponse is the response payload for ka10021 (호가잔량급증요청).
type QuoteVolumeSurgeResponse struct {
	BidReqSdnin []QuoteVolumeSurgeResponseBidReqSdninItem `json:"bid_req_sdnin"`
	ReturnCode  int                                       `json:"return_code"`
	ReturnMsg   string                                    `json:"return_msg"`
}

// QuoteVolumeSurgeResponseBidReqSdninItem is a list row in QuoteVolumeSurgeResponse.
type QuoteVolumeSurgeResponseBidReqSdninItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	Int        string `json:"int"`
	Now        string `json:"now"`
	SdninQty   string `json:"sdnin_qty"`
	SdninRt    string `json:"sdnin_rt"`
	TotBuyQty  string `json:"tot_buy_qty"`
}

// GetQuoteVolumeSurge calls Kiwoom ka10021 — 호가잔량급증요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetQuoteVolumeSurge(ctx context.Context, req *QuoteVolumeSurgeRequest) (*QuoteVolumeSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10021", req)
	if err != nil {
		return nil, err
	}
	var res QuoteVolumeSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// RemainingRateSurgeRequest is the request payload for ka10022 (잔량율급증요청).
type RemainingRateSurgeRequest struct {
	MrktTp    string `json:"mrkt_tp"`
	RtTp      string `json:"rt_tp"`
	TmTp      string `json:"tm_tp"`
	TrdeQtyTp string `json:"trde_qty_tp"`
	StkCnd    string `json:"stk_cnd"`
	StexTp    string `json:"stex_tp"`
}

// RemainingRateSurgeResponse is the response payload for ka10022 (잔량율급증요청).
type RemainingRateSurgeResponse struct {
	ReqRtSdnin []RemainingRateSurgeResponseReqRtSdninItem `json:"req_rt_sdnin"`
	ReturnCode int                                        `json:"return_code"`
	ReturnMsg  string                                     `json:"return_msg"`
}

// RemainingRateSurgeResponseReqRtSdninItem is a list row in RemainingRateSurgeResponse.
type RemainingRateSurgeResponseReqRtSdninItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	Int        string `json:"int"`
	NowRt      string `json:"now_rt"`
	SdninRt    string `json:"sdnin_rt"`
	TotSelReq  string `json:"tot_sel_req"`
	TotBuyReq  string `json:"tot_buy_req"`
}

// GetRemainingRateSurge calls Kiwoom ka10022 — 잔량율급증요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetRemainingRateSurge(ctx context.Context, req *RemainingRateSurgeRequest) (*RemainingRateSurgeResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10022", req)
	if err != nil {
		return nil, err
	}
	var res RemainingRateSurgeResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// VolumeRenewalRequest is the request payload for ka10024 (거래량갱신요청).
type VolumeRenewalRequest struct {
	MrktTp    string `json:"mrkt_tp"`
	CycleTp   string `json:"cycle_tp"`
	TrdeQtyTp string `json:"trde_qty_tp"`
	StexTp    string `json:"stex_tp"`
}

// VolumeRenewalResponse is the response payload for ka10024 (거래량갱신요청).
type VolumeRenewalResponse struct {
	TrdeQtyUpdt []VolumeRenewalResponseTrdeQtyUpdtItem `json:"trde_qty_updt"`
	ReturnCode  int                                    `json:"return_code"`
	ReturnMsg   string                                 `json:"return_msg"`
}

// VolumeRenewalResponseTrdeQtyUpdtItem is a list row in VolumeRenewalResponse.
type VolumeRenewalResponseTrdeQtyUpdtItem struct {
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	PrevTrdeQty string `json:"prev_trde_qty"`
	NowTrdeQty  string `json:"now_trde_qty"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
}

// GetVolumeRenewal calls Kiwoom ka10024 — 거래량갱신요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetVolumeRenewal(ctx context.Context, req *VolumeRenewalRequest) (*VolumeRenewalResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10024", req)
	if err != nil {
		return nil, err
	}
	var res VolumeRenewalResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// PriceClusterRequest is the request payload for ka10025 (매물대집중요청).
type PriceClusterRequest struct {
	MrktTp      string `json:"mrkt_tp"`
	PrpsCnctrRt string `json:"prps_cnctr_rt"`
	CurPrcEntry string `json:"cur_prc_entry"`
	Prpscnt     string `json:"prpscnt"`
	CycleTp     string `json:"cycle_tp"`
	StexTp      string `json:"stex_tp"`
}

// PriceClusterResponse is the response payload for ka10025 (매물대집중요청).
type PriceClusterResponse struct {
	PrpsCnctr  []PriceClusterResponsePrpsCnctrItem `json:"prps_cnctr"`
	ReturnCode int                                 `json:"return_code"`
	ReturnMsg  string                              `json:"return_msg"`
}

// PriceClusterResponsePrpsCnctrItem is a list row in PriceClusterResponse.
type PriceClusterResponsePrpsCnctrItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	NowTrdeQty string `json:"now_trde_qty"`
	PricStrt   string `json:"pric_strt"`
	PricEnd    string `json:"pric_end"`
	PrpsQty    string `json:"prps_qty"`
	PrpsRt     string `json:"prps_rt"`
}

// GetPriceCluster calls Kiwoom ka10025 — 매물대집중요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetPriceCluster(ctx context.Context, req *PriceClusterRequest) (*PriceClusterResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10025", req)
	if err != nil {
		return nil, err
	}
	var res PriceClusterResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// HighLowPERRequest is the request payload for ka10026 (고저PER요청).
type HighLowPERRequest struct {
	Pertp  string `json:"pertp"`
	StexTp string `json:"stex_tp"`
}

// HighLowPERResponse is the response payload for ka10026 (고저PER요청).
type HighLowPERResponse struct {
	HighLowPer []HighLowPERResponseHighLowPerItem `json:"high_low_per"`
	ReturnCode int                                `json:"return_code"`
	ReturnMsg  string                             `json:"return_msg"`
}

// HighLowPERResponseHighLowPerItem is a list row in HighLowPERResponse.
type HighLowPERResponseHighLowPerItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	Per        string `json:"per"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	NowTrdeQty string `json:"now_trde_qty"`
	SelBid     string `json:"sel_bid"`
}

// GetHighLowPER calls Kiwoom ka10026 — 고저PER요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetHighLowPER(ctx context.Context, req *HighLowPERRequest) (*HighLowPERResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10026", req)
	if err != nil {
		return nil, err
	}
	var res HighLowPERResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// PreviousDayChangeRateRankRequest is the request payload for ka10027 (전일대비등락률상위요청).
type PreviousDayChangeRateRankRequest struct {
	MrktTp       string `json:"mrkt_tp"`
	SortTp       string `json:"sort_tp"`
	TrdeQtyCnd   string `json:"trde_qty_cnd"`
	StkCnd       string `json:"stk_cnd"`
	CrdCnd       string `json:"crd_cnd"`
	UpdownIncls  string `json:"updown_incls"`
	PricCnd      string `json:"pric_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	StexTp       string `json:"stex_tp"`
}

// PreviousDayChangeRateRankResponse is the response payload for ka10027 (전일대비등락률상위요청).
type PreviousDayChangeRateRankResponse struct {
	PredPreFluRtUpper []PreviousDayChangeRateRankResponsePredPreFluRtUpperItem `json:"pred_pre_flu_rt_upper"`
	ReturnCode        int                                                      `json:"return_code"`
	ReturnMsg         string                                                   `json:"return_msg"`
}

// PreviousDayChangeRateRankResponsePredPreFluRtUpperItem is a list row in PreviousDayChangeRateRankResponse.
type PreviousDayChangeRateRankResponsePredPreFluRtUpperItem struct {
	StkCls     string `json:"stk_cls"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	SelReq     string `json:"sel_req"`
	BuyReq     string `json:"buy_req"`
	NowTrdeQty string `json:"now_trde_qty"`
	CntrStr    string `json:"cntr_str"`
	Cnt        string `json:"cnt"`
}

// GetPreviousDayChangeRateRank calls Kiwoom ka10027 — 전일대비등락률상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetPreviousDayChangeRateRank(ctx context.Context, req *PreviousDayChangeRateRankRequest) (*PreviousDayChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10027", req)
	if err != nil {
		return nil, err
	}
	var res PreviousDayChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// OpenChangeRateRequest is the request payload for ka10028 (시가대비등락률요청).
type OpenChangeRateRequest struct {
	SortTp       string `json:"sort_tp"`
	TrdeQtyCnd   string `json:"trde_qty_cnd"`
	MrktTp       string `json:"mrkt_tp"`
	UpdownIncls  string `json:"updown_incls"`
	StkCnd       string `json:"stk_cnd"`
	CrdCnd       string `json:"crd_cnd"`
	TrdePricaCnd string `json:"trde_prica_cnd"`
	FluCnd       string `json:"flu_cnd"`
	StexTp       string `json:"stex_tp"`
}

// OpenChangeRateResponse is the response payload for ka10028 (시가대비등락률요청).
type OpenChangeRateResponse struct {
	OpenPricPreFluRt []OpenChangeRateResponseOpenPricPreFluRtItem `json:"open_pric_pre_flu_rt"`
	ReturnCode       int                                          `json:"return_code"`
	ReturnMsg        string                                       `json:"return_msg"`
}

// OpenChangeRateResponseOpenPricPreFluRtItem is a list row in OpenChangeRateResponse.
type OpenChangeRateResponseOpenPricPreFluRtItem struct {
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	OpenPric    string `json:"open_pric"`
	HighPric    string `json:"high_pric"`
	LowPric     string `json:"low_pric"`
	OpenPricPre string `json:"open_pric_pre"`
	NowTrdeQty  string `json:"now_trde_qty"`
	CntrStr     string `json:"cntr_str"`
}

// GetOpenChangeRate calls Kiwoom ka10028 — 시가대비등락률요청.
// 종목정보를 확인할 수 있습니다.
func (c *Client) GetOpenChangeRate(ctx context.Context, req *OpenChangeRateRequest) (*OpenChangeRateResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/stkinfo", "ka10028", req)
	if err != nil {
		return nil, err
	}
	var res OpenChangeRateResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ExpectedChangeRateRankRequest is the request payload for ka10029 (예상체결등락률상위요청).
type ExpectedChangeRateRankRequest struct {
	MrktTp     string `json:"mrkt_tp"`
	SortTp     string `json:"sort_tp"`
	TrdeQtyCnd string `json:"trde_qty_cnd"`
	StkCnd     string `json:"stk_cnd"`
	CrdCnd     string `json:"crd_cnd"`
	PricCnd    string `json:"pric_cnd"`
	StexTp     string `json:"stex_tp"`
}

// ExpectedChangeRateRankResponse is the response payload for ka10029 (예상체결등락률상위요청).
type ExpectedChangeRateRankResponse struct {
	ExpCntrFluRtUpper []ExpectedChangeRateRankResponseExpCntrFluRtUpperItem `json:"exp_cntr_flu_rt_upper"`
	ReturnCode        int                                                   `json:"return_code"`
	ReturnMsg         string                                                `json:"return_msg"`
}

// ExpectedChangeRateRankResponseExpCntrFluRtUpperItem is a list row in ExpectedChangeRateRankResponse.
type ExpectedChangeRateRankResponseExpCntrFluRtUpperItem struct {
	StkCd       string `json:"stk_cd"`
	StkNm       string `json:"stk_nm"`
	ExpCntrPric string `json:"exp_cntr_pric"`
	BasePric    string `json:"base_pric"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	ExpCntrQty  string `json:"exp_cntr_qty"`
	SelReq      string `json:"sel_req"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
	BuyReq      string `json:"buy_req"`
}

// GetExpectedChangeRateRank calls Kiwoom ka10029 — 예상체결등락률상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetExpectedChangeRateRank(ctx context.Context, req *ExpectedChangeRateRankRequest) (*ExpectedChangeRateRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10029", req)
	if err != nil {
		return nil, err
	}
	var res ExpectedChangeRateRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TodayVolumeRankRequest is the request payload for ka10030 (당일거래량상위요청).
type TodayVolumeRankRequest struct {
	MrktTp       string `json:"mrkt_tp"`
	SortTp       string `json:"sort_tp"`
	MangStkIncls string `json:"mang_stk_incls"`
	CrdTp        string `json:"crd_tp"`
	TrdeQtyTp    string `json:"trde_qty_tp"`
	PricTp       string `json:"pric_tp"`
	TrdePricaTp  string `json:"trde_prica_tp"`
	MrktOpenTp   string `json:"mrkt_open_tp"`
	StexTp       string `json:"stex_tp"`
}

// TodayVolumeRankResponse is the response payload for ka10030 (당일거래량상위요청).
type TodayVolumeRankResponse struct {
	TdyTrdeQtyUpper []TodayVolumeRankResponseTdyTrdeQtyUpperItem `json:"tdy_trde_qty_upper"`
	ReturnCode      int                                          `json:"return_code"`
	ReturnMsg       string                                       `json:"return_msg"`
}

// TodayVolumeRankResponseTdyTrdeQtyUpperItem is a list row in TodayVolumeRankResponse.
type TodayVolumeRankResponseTdyTrdeQtyUpperItem struct {
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	FluRt         string `json:"flu_rt"`
	TrdeQty       string `json:"trde_qty"`
	PredRt        string `json:"pred_rt"`
	TrdeTernRt    string `json:"trde_tern_rt"`
	TrdeAmt       string `json:"trde_amt"`
	OpmrTrdeQty   string `json:"opmr_trde_qty"`
	OpmrPredRt    string `json:"opmr_pred_rt"`
	OpmrTrdeRt    string `json:"opmr_trde_rt"`
	OpmrTrdeAmt   string `json:"opmr_trde_amt"`
	AfMkrtTrdeQty string `json:"af_mkrt_trde_qty"`
	AfMkrtPredRt  string `json:"af_mkrt_pred_rt"`
	AfMkrtTrdeRt  string `json:"af_mkrt_trde_rt"`
	AfMkrtTrdeAmt string `json:"af_mkrt_trde_amt"`
	BfMkrtTrdeQty string `json:"bf_mkrt_trde_qty"`
	BfMkrtPredRt  string `json:"bf_mkrt_pred_rt"`
	BfMkrtTrdeRt  string `json:"bf_mkrt_trde_rt"`
	BfMkrtTrdeAmt string `json:"bf_mkrt_trde_amt"`
}

// GetTodayVolumeRank calls Kiwoom ka10030 — 당일거래량상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetTodayVolumeRank(ctx context.Context, req *TodayVolumeRankRequest) (*TodayVolumeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10030", req)
	if err != nil {
		return nil, err
	}
	var res TodayVolumeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// PreviousDayVolumeRankRequest is the request payload for ka10031 (전일거래량상위요청).
type PreviousDayVolumeRankRequest struct {
	MrktTp   string `json:"mrkt_tp"`
	QryTp    string `json:"qry_tp"`
	RankStrt string `json:"rank_strt"`
	RankEnd  string `json:"rank_end"`
	StexTp   string `json:"stex_tp"`
}

// PreviousDayVolumeRankResponse is the response payload for ka10031 (전일거래량상위요청).
type PreviousDayVolumeRankResponse struct {
	PredTrdeQtyUpper []PreviousDayVolumeRankResponsePredTrdeQtyUpperItem `json:"pred_trde_qty_upper"`
	ReturnCode       int                                                 `json:"return_code"`
	ReturnMsg        string                                              `json:"return_msg"`
}

// PreviousDayVolumeRankResponsePredTrdeQtyUpperItem is a list row in PreviousDayVolumeRankResponse.
type PreviousDayVolumeRankResponsePredTrdeQtyUpperItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	TrdeQty    string `json:"trde_qty"`
}

// GetPreviousDayVolumeRank calls Kiwoom ka10031 — 전일거래량상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetPreviousDayVolumeRank(ctx context.Context, req *PreviousDayVolumeRankRequest) (*PreviousDayVolumeRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10031", req)
	if err != nil {
		return nil, err
	}
	var res PreviousDayVolumeRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TradingValueRankRequest is the request payload for ka10032 (거래대금상위요청).
type TradingValueRankRequest struct {
	MrktTp       string `json:"mrkt_tp"`
	MangStkIncls string `json:"mang_stk_incls"`
	StexTp       string `json:"stex_tp"`
}

// TradingValueRankResponse is the response payload for ka10032 (거래대금상위요청).
type TradingValueRankResponse struct {
	TrdePricaUpper []TradingValueRankResponseTrdePricaUpperItem `json:"trde_prica_upper"`
	ReturnCode     int                                          `json:"return_code"`
	ReturnMsg      string                                       `json:"return_msg"`
}

// TradingValueRankResponseTrdePricaUpperItem is a list row in TradingValueRankResponse.
type TradingValueRankResponseTrdePricaUpperItem struct {
	StkCd       string `json:"stk_cd"`
	NowRank     string `json:"now_rank"`
	PredRank    string `json:"pred_rank"`
	StkNm       string `json:"stk_nm"`
	CurPrc      string `json:"cur_prc"`
	PredPreSig  string `json:"pred_pre_sig"`
	PredPre     string `json:"pred_pre"`
	FluRt       string `json:"flu_rt"`
	SelBid      string `json:"sel_bid"`
	BuyBid      string `json:"buy_bid"`
	NowTrdeQty  string `json:"now_trde_qty"`
	PredTrdeQty string `json:"pred_trde_qty"`
	TrdePrica   string `json:"trde_prica"`
}

// GetTradingValueRank calls Kiwoom ka10032 — 거래대금상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetTradingValueRank(ctx context.Context, req *TradingValueRankRequest) (*TradingValueRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10032", req)
	if err != nil {
		return nil, err
	}
	var res TradingValueRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// CreditRatioRankRequest is the request payload for ka10033 (신용비율상위요청).
type CreditRatioRankRequest struct {
	MrktTp      string `json:"mrkt_tp"`
	TrdeQtyTp   string `json:"trde_qty_tp"`
	StkCnd      string `json:"stk_cnd"`
	UpdownIncls string `json:"updown_incls"`
	CrdCnd      string `json:"crd_cnd"`
	StexTp      string `json:"stex_tp"`
}

// CreditRatioRankResponse is the response payload for ka10033 (신용비율상위요청).
type CreditRatioRankResponse struct {
	CrdRtUpper []CreditRatioRankResponseCrdRtUpperItem `json:"crd_rt_upper"`
	ReturnCode int                                     `json:"return_code"`
	ReturnMsg  string                                  `json:"return_msg"`
}

// CreditRatioRankResponseCrdRtUpperItem is a list row in CreditRatioRankResponse.
type CreditRatioRankResponseCrdRtUpperItem struct {
	StkInfr    string `json:"stk_infr"`
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	FluRt      string `json:"flu_rt"`
	CrdRt      string `json:"crd_rt"`
	SelReq     string `json:"sel_req"`
	BuyReq     string `json:"buy_req"`
	NowTrdeQty string `json:"now_trde_qty"`
}

// GetCreditRatioRank calls Kiwoom ka10033 — 신용비율상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetCreditRatioRank(ctx context.Context, req *CreditRatioRankRequest) (*CreditRatioRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10033", req)
	if err != nil {
		return nil, err
	}
	var res CreditRatioRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ForeignerPeriodTradingRankRequest is the request payload for ka10034 (외인기간별매매상위요청).
type ForeignerPeriodTradingRankRequest struct {
	MrktTp string `json:"mrkt_tp"`
	TrdeTp string `json:"trde_tp"`
	Dt     string `json:"dt"`
	StexTp string `json:"stex_tp"`
}

// ForeignerPeriodTradingRankResponse is the response payload for ka10034 (외인기간별매매상위요청).
type ForeignerPeriodTradingRankResponse struct {
	ForDtTrdeUpper []ForeignerPeriodTradingRankResponseForDtTrdeUpperItem `json:"for_dt_trde_upper"`
	ReturnCode     int                                                    `json:"return_code"`
	ReturnMsg      string                                                 `json:"return_msg"`
}

// ForeignerPeriodTradingRankResponseForDtTrdeUpperItem is a list row in ForeignerPeriodTradingRankResponse.
type ForeignerPeriodTradingRankResponseForDtTrdeUpperItem struct {
	Rank          string `json:"rank"`
	StkCd         string `json:"stk_cd"`
	StkNm         string `json:"stk_nm"`
	CurPrc        string `json:"cur_prc"`
	PredPreSig    string `json:"pred_pre_sig"`
	PredPre       string `json:"pred_pre"`
	SelBid        string `json:"sel_bid"`
	BuyBid        string `json:"buy_bid"`
	TrdeQty       string `json:"trde_qty"`
	NetprpsQty    string `json:"netprps_qty"`
	GainPosStkcnt string `json:"gain_pos_stkcnt"`
}

// GetForeignerPeriodTradingRank calls Kiwoom ka10034 — 외인기간별매매상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetForeignerPeriodTradingRank(ctx context.Context, req *ForeignerPeriodTradingRankRequest) (*ForeignerPeriodTradingRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10034", req)
	if err != nil {
		return nil, err
	}
	var res ForeignerPeriodTradingRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ForeignerConsecutiveNetBuyRankRequest is the request payload for ka10035 (외인연속순매매상위요청).
type ForeignerConsecutiveNetBuyRankRequest struct {
	MrktTp   string `json:"mrkt_tp"`
	TrdeTp   string `json:"trde_tp"`
	BaseDtTp string `json:"base_dt_tp"`
	StexTp   string `json:"stex_tp"`
}

// ForeignerConsecutiveNetBuyRankResponse is the response payload for ka10035 (외인연속순매매상위요청).
type ForeignerConsecutiveNetBuyRankResponse struct {
	ForContNettrdeUpper []ForeignerConsecutiveNetBuyRankResponseForContNettrdeUpperItem `json:"for_cont_nettrde_upper"`
	ReturnCode          int                                                             `json:"return_code"`
	ReturnMsg           string                                                          `json:"return_msg"`
}

// ForeignerConsecutiveNetBuyRankResponseForContNettrdeUpperItem is a list row in ForeignerConsecutiveNetBuyRankResponse.
type ForeignerConsecutiveNetBuyRankResponseForContNettrdeUpperItem struct {
	StkCd      string `json:"stk_cd"`
	StkNm      string `json:"stk_nm"`
	CurPrc     string `json:"cur_prc"`
	PredPreSig string `json:"pred_pre_sig"`
	PredPre    string `json:"pred_pre"`
	Dm1        string `json:"dm1"`
	Dm2        string `json:"dm2"`
	Dm3        string `json:"dm3"`
	Tot        string `json:"tot"`
	LimitExhRt string `json:"limit_exh_rt"`
	PredPreN1  string `json:"pred_pre_1"`
	PredPreN2  string `json:"pred_pre_2"`
	PredPreN3  string `json:"pred_pre_3"`
}

// GetForeignerConsecutiveNetBuyRank calls Kiwoom ka10035 — 외인연속순매매상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetForeignerConsecutiveNetBuyRank(ctx context.Context, req *ForeignerConsecutiveNetBuyRankRequest) (*ForeignerConsecutiveNetBuyRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10035", req)
	if err != nil {
		return nil, err
	}
	var res ForeignerConsecutiveNetBuyRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ForeignerLimitExhaustionRankRequest is the request payload for ka10036 (외인한도소진율증가상위).
type ForeignerLimitExhaustionRankRequest struct {
	MrktTp string `json:"mrkt_tp"`
	Dt     string `json:"dt"`
	StexTp string `json:"stex_tp"`
}

// ForeignerLimitExhaustionRankResponse is the response payload for ka10036 (외인한도소진율증가상위).
type ForeignerLimitExhaustionRankResponse struct {
	ForLimitExhRtIncrsUpper []ForeignerLimitExhaustionRankResponseForLimitExhRtIncrsUpperItem `json:"for_limit_exh_rt_incrs_upper"`
	ReturnCode              int                                                               `json:"return_code"`
	ReturnMsg               string                                                            `json:"return_msg"`
}

// ForeignerLimitExhaustionRankResponseForLimitExhRtIncrsUpperItem is a list row in ForeignerLimitExhaustionRankResponse.
type ForeignerLimitExhaustionRankResponseForLimitExhRtIncrsUpperItem struct {
	Rank           string `json:"rank"`
	StkCd          string `json:"stk_cd"`
	StkNm          string `json:"stk_nm"`
	CurPrc         string `json:"cur_prc"`
	PredPreSig     string `json:"pred_pre_sig"`
	PredPre        string `json:"pred_pre"`
	TrdeQty        string `json:"trde_qty"`
	PossStkcnt     string `json:"poss_stkcnt"`
	GainPosStkcnt  string `json:"gain_pos_stkcnt"`
	BaseLimitExhRt string `json:"base_limit_exh_rt"`
	LimitExhRt     string `json:"limit_exh_rt"`
	ExhRtIncrs     string `json:"exh_rt_incrs"`
}

// GetForeignerLimitExhaustionRank calls Kiwoom ka10036 — 외인한도소진율증가상위.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetForeignerLimitExhaustionRank(ctx context.Context, req *ForeignerLimitExhaustionRankRequest) (*ForeignerLimitExhaustionRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10036", req)
	if err != nil {
		return nil, err
	}
	var res ForeignerLimitExhaustionRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// ForeignBrokerTradingRankRequest is the request payload for ka10037 (외국계창구매매상위요청).
type ForeignBrokerTradingRankRequest struct {
	MrktTp string `json:"mrkt_tp"`
	Dt     string `json:"dt"`
	TrdeTp string `json:"trde_tp"`
	SortTp string `json:"sort_tp"`
	StexTp string `json:"stex_tp"`
}

// ForeignBrokerTradingRankResponse is the response payload for ka10037 (외국계창구매매상위요청).
type ForeignBrokerTradingRankResponse struct {
	FrgnWicketTrdeUpper []ForeignBrokerTradingRankResponseFrgnWicketTrdeUpperItem `json:"frgn_wicket_trde_upper"`
	ReturnCode          int                                                       `json:"return_code"`
	ReturnMsg           string                                                    `json:"return_msg"`
}

// ForeignBrokerTradingRankResponseFrgnWicketTrdeUpperItem is a list row in ForeignBrokerTradingRankResponse.
type ForeignBrokerTradingRankResponseFrgnWicketTrdeUpperItem struct {
	Rank           string `json:"rank"`
	StkCd          string `json:"stk_cd"`
	StkNm          string `json:"stk_nm"`
	CurPrc         string `json:"cur_prc"`
	PredPreSig     string `json:"pred_pre_sig"`
	PredPre        string `json:"pred_pre"`
	FluRt          string `json:"flu_rt"`
	SelTrdeQty     string `json:"sel_trde_qty"`
	BuyTrdeQty     string `json:"buy_trde_qty"`
	NetprpsTrdeQty string `json:"netprps_trde_qty"`
	NetprpsPrica   string `json:"netprps_prica"`
	TrdeQty        string `json:"trde_qty"`
	TrdePrica      string `json:"trde_prica"`
}

// GetForeignBrokerTradingRank calls Kiwoom ka10037 — 외국계창구매매상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetForeignBrokerTradingRank(ctx context.Context, req *ForeignBrokerTradingRankRequest) (*ForeignBrokerTradingRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10037", req)
	if err != nil {
		return nil, err
	}
	var res ForeignBrokerTradingRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// StockSecuritiesFirmRankRequest is the request payload for ka10038 (종목별증권사순위요청).
type StockSecuritiesFirmRankRequest struct {
	StkCd  string `json:"stk_cd"`
	StrtDt string `json:"strt_dt"`
	EndDt  string `json:"end_dt"`
	QryTp  string `json:"qry_tp"`
	Dt     string `json:"dt"`
}

// StockSecuritiesFirmRankResponse is the response payload for ka10038 (종목별증권사순위요청).
type StockSecuritiesFirmRankResponse struct {
	RankN1      string                                          `json:"rank_1"`
	RankN2      string                                          `json:"rank_2"`
	RankN3      string                                          `json:"rank_3"`
	PridTrdeQty string                                          `json:"prid_trde_qty"`
	StkSecRank  []StockSecuritiesFirmRankResponseStkSecRankItem `json:"stk_sec_rank"`
	ReturnCode  int                                             `json:"return_code"`
	ReturnMsg   string                                          `json:"return_msg"`
}

// StockSecuritiesFirmRankResponseStkSecRankItem is a list row in StockSecuritiesFirmRankResponse.
type StockSecuritiesFirmRankResponseStkSecRankItem struct {
	Rank          string `json:"rank"`
	MmcmNm        string `json:"mmcm_nm"`
	BuyQty        string `json:"buy_qty"`
	SellQty       string `json:"sell_qty"`
	AccNetprpsQty string `json:"acc_netprps_qty"`
}

// GetStockSecuritiesFirmRank calls Kiwoom ka10038 — 종목별증권사순위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetStockSecuritiesFirmRank(ctx context.Context, req *StockSecuritiesFirmRankRequest) (*StockSecuritiesFirmRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10038", req)
	if err != nil {
		return nil, err
	}
	var res StockSecuritiesFirmRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// SecuritiesFirmTradingRankRequest is the request payload for ka10039 (증권사별매매상위요청).
type SecuritiesFirmTradingRankRequest struct {
	MmcmCd    string `json:"mmcm_cd"`
	TrdeQtyTp string `json:"trde_qty_tp"`
	TrdeTp    string `json:"trde_tp"`
	Dt        string `json:"dt"`
	StexTp    string `json:"stex_tp"`
}

// SecuritiesFirmTradingRankResponse is the response payload for ka10039 (증권사별매매상위요청).
type SecuritiesFirmTradingRankResponse struct {
	SecTrdeUpper []SecuritiesFirmTradingRankResponseSecTrdeUpperItem `json:"sec_trde_upper"`
	ReturnCode   int                                                 `json:"return_code"`
	ReturnMsg    string                                              `json:"return_msg"`
}

// SecuritiesFirmTradingRankResponseSecTrdeUpperItem is a list row in SecuritiesFirmTradingRankResponse.
type SecuritiesFirmTradingRankResponseSecTrdeUpperItem struct {
	Rank         string `json:"rank"`
	StkCd        string `json:"stk_cd"`
	StkNm        string `json:"stk_nm"`
	PridStkpcFlu string `json:"prid_stkpc_flu"`
	FluRt        string `json:"flu_rt"`
	PridTrdeQty  string `json:"prid_trde_qty"`
	Netprps      string `json:"netprps"`
	BuyTrdeQty   string `json:"buy_trde_qty"`
	SelTrdeQty   string `json:"sel_trde_qty"`
	NetprpsAmt   string `json:"netprps_amt"`
	BuyAmt       string `json:"buy_amt"`
	SellAmt      string `json:"sell_amt"`
}

// GetSecuritiesFirmTradingRank calls Kiwoom ka10039 — 증권사별매매상위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetSecuritiesFirmTradingRank(ctx context.Context, req *SecuritiesFirmTradingRankRequest) (*SecuritiesFirmTradingRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10039", req)
	if err != nil {
		return nil, err
	}
	var res SecuritiesFirmTradingRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// TodayMainBrokersRequest is the request payload for ka10040 (당일주요거래원요청).
type TodayMainBrokersRequest struct {
	StkCd string `json:"stk_cd"`
}

// TodayMainBrokersResponse is the response payload for ka10040 (당일주요거래원요청).
type TodayMainBrokersResponse struct {
	SelTrdeOriIrdsN1    string                                       `json:"sel_trde_ori_irds_1"`
	SelTrdeOriQtyN1     string                                       `json:"sel_trde_ori_qty_1"`
	SelTrdeOriN1        string                                       `json:"sel_trde_ori_1"`
	SelTrdeOriCdN1      string                                       `json:"sel_trde_ori_cd_1"`
	BuyTrdeOriN1        string                                       `json:"buy_trde_ori_1"`
	BuyTrdeOriCdN1      string                                       `json:"buy_trde_ori_cd_1"`
	BuyTrdeOriQtyN1     string                                       `json:"buy_trde_ori_qty_1"`
	BuyTrdeOriIrdsN1    string                                       `json:"buy_trde_ori_irds_1"`
	SelTrdeOriIrdsN2    string                                       `json:"sel_trde_ori_irds_2"`
	SelTrdeOriQtyN2     string                                       `json:"sel_trde_ori_qty_2"`
	SelTrdeOriN2        string                                       `json:"sel_trde_ori_2"`
	SelTrdeOriCdN2      string                                       `json:"sel_trde_ori_cd_2"`
	BuyTrdeOriN2        string                                       `json:"buy_trde_ori_2"`
	BuyTrdeOriCdN2      string                                       `json:"buy_trde_ori_cd_2"`
	BuyTrdeOriQtyN2     string                                       `json:"buy_trde_ori_qty_2"`
	BuyTrdeOriIrdsN2    string                                       `json:"buy_trde_ori_irds_2"`
	SelTrdeOriIrdsN3    string                                       `json:"sel_trde_ori_irds_3"`
	SelTrdeOriQtyN3     string                                       `json:"sel_trde_ori_qty_3"`
	SelTrdeOriN3        string                                       `json:"sel_trde_ori_3"`
	SelTrdeOriCdN3      string                                       `json:"sel_trde_ori_cd_3"`
	BuyTrdeOriN3        string                                       `json:"buy_trde_ori_3"`
	BuyTrdeOriCdN3      string                                       `json:"buy_trde_ori_cd_3"`
	BuyTrdeOriQtyN3     string                                       `json:"buy_trde_ori_qty_3"`
	BuyTrdeOriIrdsN3    string                                       `json:"buy_trde_ori_irds_3"`
	SelTrdeOriIrdsN4    string                                       `json:"sel_trde_ori_irds_4"`
	SelTrdeOriQtyN4     string                                       `json:"sel_trde_ori_qty_4"`
	SelTrdeOriN4        string                                       `json:"sel_trde_ori_4"`
	SelTrdeOriCdN4      string                                       `json:"sel_trde_ori_cd_4"`
	BuyTrdeOriN4        string                                       `json:"buy_trde_ori_4"`
	BuyTrdeOriCdN4      string                                       `json:"buy_trde_ori_cd_4"`
	BuyTrdeOriQtyN4     string                                       `json:"buy_trde_ori_qty_4"`
	BuyTrdeOriIrdsN4    string                                       `json:"buy_trde_ori_irds_4"`
	SelTrdeOriIrdsN5    string                                       `json:"sel_trde_ori_irds_5"`
	SelTrdeOriQtyN5     string                                       `json:"sel_trde_ori_qty_5"`
	SelTrdeOriN5        string                                       `json:"sel_trde_ori_5"`
	SelTrdeOriCdN5      string                                       `json:"sel_trde_ori_cd_5"`
	BuyTrdeOriN5        string                                       `json:"buy_trde_ori_5"`
	BuyTrdeOriCdN5      string                                       `json:"buy_trde_ori_cd_5"`
	BuyTrdeOriQtyN5     string                                       `json:"buy_trde_ori_qty_5"`
	BuyTrdeOriIrdsN5    string                                       `json:"buy_trde_ori_irds_5"`
	FrgnSelPrsmSumChang string                                       `json:"frgn_sel_prsm_sum_chang"`
	FrgnSelPrsmSum      string                                       `json:"frgn_sel_prsm_sum"`
	FrgnBuyPrsmSum      string                                       `json:"frgn_buy_prsm_sum"`
	FrgnBuyPrsmSumChang string                                       `json:"frgn_buy_prsm_sum_chang"`
	TdyMainTrdeOri      []TodayMainBrokersResponseTdyMainTrdeOriItem `json:"tdy_main_trde_ori"`
	ReturnCode          int                                          `json:"return_code"`
	ReturnMsg           string                                       `json:"return_msg"`
}

// TodayMainBrokersResponseTdyMainTrdeOriItem is a list row in TodayMainBrokersResponse.
type TodayMainBrokersResponseTdyMainTrdeOriItem struct {
	SelScesnTm       string `json:"sel_scesn_tm"`
	SellQty          string `json:"sell_qty"`
	SelUpperScesnOri string `json:"sel_upper_scesn_ori"`
	BuyScesnTm       string `json:"buy_scesn_tm"`
	BuyQty           string `json:"buy_qty"`
	BuyUpperScesnOri string `json:"buy_upper_scesn_ori"`
	QryDt            string `json:"qry_dt"`
	QryTm            string `json:"qry_tm"`
}

// GetTodayMainBrokers calls Kiwoom ka10040 — 당일주요거래원요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetTodayMainBrokers(ctx context.Context, req *TodayMainBrokersRequest) (*TodayMainBrokersResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10040", req)
	if err != nil {
		return nil, err
	}
	var res TodayMainBrokersResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

// NetBuyBrokerRankRequest is the request payload for ka10042 (순매수거래원순위요청).
type NetBuyBrokerRankRequest struct {
	StkCd    string `json:"stk_cd"`
	StrtDt   string `json:"strt_dt"`
	EndDt    string `json:"end_dt"`
	QryDtTp  string `json:"qry_dt_tp"`
	PotTp    string `json:"pot_tp"`
	Dt       string `json:"dt"`
	SortBase string `json:"sort_base"`
}

// NetBuyBrokerRankResponse is the response payload for ka10042 (순매수거래원순위요청).
type NetBuyBrokerRankResponse struct {
	NetprpsTrdeOriRank []NetBuyBrokerRankResponseNetprpsTrdeOriRankItem `json:"netprps_trde_ori_rank"`
	ReturnCode         int                                              `json:"return_code"`
	ReturnMsg          string                                           `json:"return_msg"`
}

// NetBuyBrokerRankResponseNetprpsTrdeOriRankItem is a list row in NetBuyBrokerRankResponse.
type NetBuyBrokerRankResponseNetprpsTrdeOriRankItem struct {
	Rank   string `json:"rank"`
	MmcmCd string `json:"mmcm_cd"`
	MmcmNm string `json:"mmcm_nm"`
}

// GetNetBuyBrokerRank calls Kiwoom ka10042 — 순매수거래원순위요청.
// 순위정보를 확인할 수 있습니다.
func (c *Client) GetNetBuyBrokerRank(ctx context.Context, req *NetBuyBrokerRankRequest) (*NetBuyBrokerRankResponse, error) {
	httpReq, err := c.newRequest(ctx, http.MethodPost, "/api/dostk/rkinfo", "ka10042", req)
	if err != nil {
		return nil, err
	}
	var res NetBuyBrokerRankResponse
	if err := c.do(httpReq, &res); err != nil {
		return nil, err
	}
	return &res, nil
}
