#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# /// script
# requires-python = ">=3.9"
# dependencies = [
#     "pyyaml",
#     "pandas",
#     "matplotlib",
# ]
# ///

"""
Kiwoom Stock Chart Plotter
Parses the stock chart YAML file generated by the go_kioom client and plots a
premium, high-fidelity interactive candlestick chart using matplotlib.

Supports all chart types: tick, min, day, week, month, year.

Usage:
    python3 script/plot_chart.py [yaml_file_path | -] [--days N] [-o output.png]
"""

import sys

# Gracefully handle missing dependencies and provide clear instructions
try:
    import yaml
    import pandas as pd
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates
    import matplotlib.ticker as mticker
except ImportError as e:
    missing_module = str(e).split("'")[-2] if "'" in str(e) else str(e)
    print("\n" + "="*80)
    print(f"❌ Error: Missing required package '{missing_module}'")
    print("Please install the required dependencies using the command below:")
    print("\n    pip install pyyaml pandas matplotlib")
    print("="*80 + "\n")
    sys.exit(1)

import argparse
from datetime import datetime

def parse_arguments():
    parser = argparse.ArgumentParser(description="Plot a premium stock chart from a Kiwoom YAML file.")
    parser.add_argument(
        "yaml_file", 
        nargs="?", 
        default="script/samsung_chart_day.yaml", 
        help="Path to the YAML chart file (default: script/samsung_chart_day.yaml) or '-' for stdin"
    )
    parser.add_argument(
        "--days", 
        type=int, 
        default=120, 
        help="Number of recent trading periods/candles to display on the chart (default: 120)"
    )
    parser.add_argument(
        "-o", "--output", 
        type=str, 
        help="Save the chart to a file (e.g., -o output.png) instead of showing the interactive window"
    )
    return parser.parse_args()

def main():
    args = parse_arguments()

    if args.yaml_file == "-":
        print("📖 Reading chart data from standard input (stdin)...")
        try:
            data = yaml.safe_load(sys.stdin)
        except Exception as e:
            print(f"❌ Error reading YAML from stdin: {e}")
            sys.exit(1)
    else:
        print(f"📖 Reading chart data from: {args.yaml_file}...")
        try:
            with open(args.yaml_file, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f)
        except FileNotFoundError:
            # Fall back to alternative default names if default file not found
            if args.yaml_file == "script/samsung_chart_day.yaml":
                fallback_paths = ["script/samsung_chart.yaml", "script/samsung_chart_week.yaml"]
                for path in fallback_paths:
                    try:
                        with open(path, "r", encoding="utf-8") as f:
                            data = yaml.safe_load(f)
                            print(f"⚠️ Default not found, fell back to loading: {path}")
                            break
                    except FileNotFoundError:
                        continue
                else:
                    print(f"❌ Error: File not found at {args.yaml_file}")
                    sys.exit(1)
            else:
                print(f"❌ Error: File not found at {args.yaml_file}")
                sys.exit(1)
        except Exception as e:
            print(f"❌ Error reading YAML file: {e}")
            sys.exit(1)

    # 1. Define Chart Types Mapping & Fields
    CHART_MAPPING = {
        "stkticchartqry": {
            "name": "Tick",
            "time_key": "cntrtm",
            "time_fmt": "%Y%m%d%H%M%S",
            "lbl_fmt": "%m-%d %H:%M:%S",
        },
        "stkminpolechartqry": {
            "name": "Minute",
            "time_key": "cntrtm",
            "time_fmt": "%Y%m%d%H%M%S",
            "lbl_fmt": "%m-%d %H:%M",
        },
        "stkdtpolechartqry": {
            "name": "Daily",
            "time_key": "dt",
            "time_fmt": "%Y%m%d",
            "lbl_fmt": "%Y-%m-%d",
        },
        "stkstkpolechartqry": {
            "name": "Weekly",
            "time_key": "dt",
            "time_fmt": "%Y%m%d",
            "lbl_fmt": "%Y-%m-%d",
        },
        "stkmthpolechartqry": {
            "name": "Monthly",
            "time_key": "dt",
            "time_fmt": "%Y%m%d",
            "lbl_fmt": "%Y-%m",
        },
        "stkyrpolechartqry": {
            "name": "Yearly",
            "time_key": "dt",
            "time_fmt": "%Y%m%d",
            "lbl_fmt": "%Y",
        },
    }

    # 2. Auto-Detect Chart Type based on YAML keys
    detected_key = None
    for key in CHART_MAPPING:
        if key in data:
            detected_key = key
            break

    if not detected_key:
        print("❌ Error: No recognized chart data section found in the YAML file.")
        print("Expected one of the following root keys:")
        for k in CHART_MAPPING:
            print(f"  - {k}")
        sys.exit(1)

    chart_info = CHART_MAPPING[detected_key]
    chart_name = chart_info["name"]
    time_key = chart_info["time_key"]
    time_fmt = chart_info["time_fmt"]
    lbl_fmt = chart_info["lbl_fmt"]

    stkcd = data.get("stkcd", "Unknown")
    records = data.get(detected_key, [])

    if not records:
        print(f"❌ Error: No chart data found in the '{detected_key}' section of the YAML file.")
        sys.exit(1)

    print(f"📊 Loaded {len(records)} {chart_name} records for Stock Code: {stkcd}")

    # 3. Clean and Parse Columns into pandas DataFrame
    df = pd.DataFrame(records)

    try:
        df["date"] = pd.to_datetime(df[time_key], format=time_fmt)
        df["open"] = df["openpric"].astype(float)
        df["high"] = df["highpric"].astype(float)
        df["low"] = df["lowpric"].astype(float)
        df["close"] = df["curprc"].astype(float)
        df["volume"] = df["trdeqty"].astype(float)
    except KeyError as e:
        print(f"❌ Error: Missing expected column in YAML: {e}")
        print(f"Expected fields: {time_key}, openpric, highpric, lowpric, curprc, trdeqty")
        sys.exit(1)

    # Sort chronologically (oldest to newest)
    df = df.sort_values("date").reset_index(drop=True)

    # 4. Calculate Moving Averages on the *entire* dataset for accuracy
    df["MA5"] = df["close"].rolling(window=5).mean()
    df["MA20"] = df["close"].rolling(window=20).mean()
    df["MA60"] = df["close"].rolling(window=60).mean()
    df["MA120"] = df["close"].rolling(window=120).mean()

    # Filter to the requested number of periods/candles for plotting
    plot_df = df.tail(args.days).copy()
    plot_df = plot_df.reset_index(drop=True)  # Reset index to 0..N-1 for index-based plotting
    
    if len(plot_df) < args.days:
        print(f"⚠️ Warning: Requested {args.days} periods, but only {len(plot_df)} periods are available.")

    latest_close = plot_df["close"].iloc[-1]
    
    if detected_key in ["stkticchartqry", "stkminpolechartqry"]:
        latest_date = plot_df["date"].iloc[-1].strftime("%Y-%m-%d %H:%M:%S")
    else:
        latest_date = plot_df["date"].iloc[-1].strftime("%Y-%m-%d")
        
    prev_close = plot_df["close"].iloc[-2] if len(plot_df) > 1 else latest_close
    change = latest_close - prev_close
    change_pct = (change / prev_close) * 100 if prev_close != 0 else 0

    # 5. Set Premium Dark Theme Style Parameters
    plt.style.use("dark_background")
    fig, (ax1, ax2) = plt.subplots(
        2, 1, 
        figsize=(14, 9), 
        sharex=True, 
        gridspec_kw={"height_ratios": [3, 1]}
    )
    fig.patch.set_facecolor("#0b0c10")
    ax1.set_facecolor("#12131c")
    ax2.set_facecolor("#12131c")

    # KRX Standard Color Scheme: Bullish = Red, Bearish = Blue
    color_bullish = "#f03e3e"  # Vibrant Red
    color_bearish = "#1971c2"   # Vibrant Blue
    width = 0.6  # Candle width in index coordinate space

    # Split into bullish and bearish for vectorized plotting
    bullish = plot_df[plot_df["close"] >= plot_df["open"]]
    bearish = plot_df[plot_df["close"] < plot_df["open"]]

    # 6. Draw Candlesticks on ax1 (Using index-based X coordinates)
    # Shadow lines (High-Low)
    ax1.vlines(bullish.index, bullish["low"], bullish["high"], color=color_bullish, linewidth=1.2, zorder=2)
    ax1.vlines(bearish.index, bearish["low"], bearish["high"], color=color_bearish, linewidth=1.2, zorder=2)

    # Candle bodies (Open-Close)
    ax1.bar(
        bullish.index, 
        bullish["close"] - bullish["open"], 
        bottom=bullish["open"], 
        width=width, 
        color=color_bullish, 
        edgecolor=color_bullish, 
        linewidth=0.5,
        zorder=3,
        label="Bullish"
    )
    ax1.bar(
        bearish.index, 
        bearish["open"] - bearish["close"], 
        bottom=bearish["close"], 
        width=width, 
        color=color_bearish, 
        edgecolor=color_bearish, 
        linewidth=0.5,
        zorder=3,
        label="Bearish"
    )

    # 7. Draw Moving Averages on ax1 (Using index-based X coordinates)
    if plot_df["MA5"].notna().any():
        ax1.plot(plot_df.index, plot_df["MA5"], color="#22c55e", label="MA5", linewidth=1.5, alpha=0.9, zorder=4)
    if plot_df["MA20"].notna().any():
        ax1.plot(plot_df.index, plot_df["MA20"], color="#eab308", label="MA20", linewidth=1.5, alpha=0.9, zorder=4)
    if plot_df["MA60"].notna().any():
        ax1.plot(plot_df.index, plot_df["MA60"], color="#a855f7", label="MA60", linewidth=1.5, alpha=0.9, zorder=4)
    if plot_df["MA120"].notna().any():
        ax1.plot(plot_df.index, plot_df["MA120"], color="#06b6d4", label="MA120", linewidth=1.5, alpha=0.9, zorder=4)

    # Latest Close Price Indicator line & text label
    ax1.axhline(latest_close, color="#868e96", linestyle="--", linewidth=0.8, alpha=0.7)
    
    change_color = color_bullish if change >= 0 else color_bearish
    change_sign = "+" if change >= 0 else ""
    ax1.text(
        len(plot_df) - 1, latest_close, 
        f"  {latest_close:,.0f} ({change_sign}{change:,.0f}, {change_sign}{change_pct:+.2f}%)",
        color="#ffffff", 
        fontsize=10, 
        fontweight="bold",
        verticalalignment="center",
        bbox=dict(facecolor=change_color, alpha=0.85, edgecolor="none", boxstyle="round,pad=0.3")
    )

    # 8. Draw Trading Volume on ax2 (Using index-based X coordinates)
    bullish_vol = plot_df[plot_df["close"] >= plot_df["open"]]
    bearish_vol = plot_df[plot_df["close"] < plot_df["open"]]
    
    ax2.bar(bullish_vol.index, bullish_vol["volume"], width=width, color=color_bullish, alpha=0.75, zorder=3)
    ax2.bar(bearish_vol.index, bearish_vol["volume"], width=width, color=color_bearish, alpha=0.75, zorder=3)

    # Volume Moving Average (5-period Volume MA)
    vol_ma5 = plot_df["volume"].rolling(window=5).mean()
    if vol_ma5.notna().any():
        ax2.plot(plot_df.index, vol_ma5, color="#ced4da", label="Vol MA5", linewidth=1.2, alpha=0.6, linestyle=":")

    # 9. Grid and Styling details
    for ax in [ax1, ax2]:
        ax.grid(True, color="#2d3139", linestyle=":", linewidth=0.5, alpha=0.7)
        ax.tick_params(axis="both", colors="#a5a5a5", labelsize=10)
        # Remove borders
        for spine in ["top", "right", "left", "bottom"]:
            ax.spines[spine].set_color("#2d3139")
            ax.spines[spine].set_linewidth(0.8)

    # Format Y-axis tick values with thousands separators
    ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f"{x:,.0f}"))
    ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f"{x:,.0f}"))

    # Align labels nicely
    ax1.set_ylabel("Price (KRW)", color="#a5a5a5", fontsize=11, fontweight="semibold")
    ax2.set_ylabel("Volume", color="#a5a5a5", fontsize=11, fontweight="semibold")

    # Dynamic date/time formatting on X-axis using index mapper
    def index_date_formatter(x, pos=None):
        idx = int(round(x))
        if 0 <= idx < len(plot_df):
            return plot_df["date"].iloc[idx].strftime(lbl_fmt)
        return ""

    ax2.xaxis.set_major_formatter(mticker.FuncFormatter(index_date_formatter))
    ax2.xaxis.set_major_locator(mticker.MaxNLocator(nbins=10))
    fig.autofmt_xdate()

    # Beautiful legends
    ax1.legend(loc="upper left", facecolor="#0b0c10", edgecolor="#2d3139", fontsize=10, framealpha=0.8)
    ax2.legend(loc="upper left", facecolor="#0b0c10", edgecolor="#2d3139", fontsize=9, framealpha=0.8)

    # Set precise titles & metadata
    title_suffix = f"{chart_name} Candlestick Chart"
    title_text = f"Samsung Electronics ({stkcd}) - {title_suffix}" if stkcd == "005930" else f"Stock ({stkcd}) - {title_suffix}"
    
    plt.suptitle(
        title_text, 
        color="#ffffff", 
        fontsize=16, 
        fontweight="bold", 
        y=0.96
    )
    
    # Subtitle with metadata
    ax1.set_title(
        f"Last Period: {latest_date}  |  Close: {latest_close:,.0f} KRW  |  Plotted Range: {len(plot_df)} Periods",
        color="#a5a5a5", 
        fontsize=11, 
        pad=10
    )

    # Tighten spacing to minimize gaps
    plt.subplots_adjust(hspace=0.08)

    if args.output:
        print(f"💾 Saving chart image to: {args.output}...")
        plt.savefig(args.output, dpi=300, facecolor=fig.get_facecolor(), edgecolor="none", bbox_inches="tight")
        print("✅ Chart image saved successfully!")
    else:
        print("🚀 Rendering interactive chart window...")
        plt.show()

if __name__ == "__main__":
    main()
